Repository istio/tools, pull requests merged in 2019-11, with the labels that each got.

#455 add flame graph perf configuration
  perf/benchmark/README.md
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/S

#494 [release-1.4] Put the branch name on the image tag
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/S

#496 Allow protoc-gen-jsonshim to generate for more Istio types
  cmd/protoc-gen-jsonshim/README.md
  cmd/protoc-gen-jsonshim/jsonshim/plugin.go
  cmd/protoc-gen-jsonshim/test/external.proto
  cmd/protoc-gen-jsonshim/test/generated/external.pb.go
  cmd/protoc-gen-jsonshim/test/generated/external_json.gen.go
  cmd/protoc-gen-jsonshim/test/generated/types.pb.go
  cmd/protoc-gen-jsonshim/test/generated/types_json.gen.go
  cmd/protoc-gen-jsonshim/test/jsonshim_test.go
  cmd/protoc-gen-jsonshim/test/types.proto
  go.sum
Labels: cla: yes, size/L

#497 Generate MarshalJSON for all types
  cmd/protoc-gen-jsonshim/README.md
  cmd/protoc-gen-jsonshim/jsonshim/plugin.go
Labels: cla: yes, size/S

#498 create a seperate dir for saving all those flamegraphs and dump to gcs bucket
  perf/benchmark/flame/flame.sh
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/S

#499 [release-1.4] Flame Graph config cherry-pick for branch 1.4
  perf/benchmark/README.md
  perf/benchmark/flame/flame.sh
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/M

#500 add debugging log for ssh to GCE instance
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#501 [release-1.4] Cherrypick protoc-gen-jsonshim changes
  cmd/protoc-gen-jsonshim/README.md
  cmd/protoc-gen-jsonshim/jsonshim/plugin.go
  cmd/protoc-gen-jsonshim/test/external.proto
  cmd/protoc-gen-jsonshim/test/generated/external.pb.go
  cmd/protoc-gen-jsonshim/test/generated/external_json.gen.go
  cmd/protoc-gen-jsonshim/test/generated/types.pb.go
  cmd/protoc-gen-jsonshim/test/generated/types_json.gen.go
  cmd/protoc-gen-jsonshim/test/jsonshim_test.go
  cmd/protoc-gen-jsonshim/test/types.proto
Labels: cla: yes, size/L

#502 ssh gce instance via username
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#503 Correct current branch command
  docker/build-tools/build-and-push.sh
Labels: cherrypick/release-1.4, cla: yes, size/XS

#504 [release-1.4] Correct current branch command
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/XS

#489 Fix for docker.push not working on mac
  docker/build-tools/Dockerfile
  docker/build-tools/docker-entrypoint.sh
Labels: cla: yes, size/S

#505 Upgrade prow base OS to ubuntu bionic
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#506 Rolling back upgrade to bionic due to failures
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#507 Build image using the correct tools branch
  docker/build-tools/Dockerfile
  docker/build-tools/build-and-push.sh
Labels: cherrypick/release-1.4, cla: yes, size/S

#508 [release-1.4] Build image using the correct tools branch
  docker/build-tools/Dockerfile
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/S

#510 Test plaintext file exists prior to using it
  docker/build-tools/docker-entrypoint.sh
Labels: cla: yes, size/S

#511 Rolling forward prow upgrade to bionic
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#513 fetch latest builds in dev stream
  perf/istio-install/setup_istio_release.sh
Labels: cla: yes, size/S

#514 delete gcloud compute instance logs
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#515 [release 1.4] ssh gce instance via username
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#516 Add a build tools image for istio/proxy
  docker/build-tools/Dockerfile
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/M

#518 fix Unable to use a TTY - input is not a terminal or the right kind of file
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#519 Update to golang 1.13.4
  docker/build-tools/Dockerfile
Labels: cherrypick/release-1.4, cla: yes, size/XS

#520 [release-1.4] Update to golang 1.13.4
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#521 Install ruamel and requests for doc repo
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#512 fix linkerd perf installation issue and add comparison results
  perf/benchmark/linkerd/README.md
  perf/benchmark/linkerd/example-comparison/istio_vs_linkerd.png
  perf/benchmark/linkerd/example-comparison/telemetryv2_vs_linkerd.png
  perf/benchmark/linkerd/setup_linkerd.sh
  perf/benchmark/setup_test.sh
Labels: cla: yes, size/M

#509 Make the benchmark pipeline job easier to configure
  perf/benchmark/README.md
  perf/benchmark/configs/mixer_cpu_mem.yaml
  perf/benchmark/configs/mixer_latency.yaml
  perf/benchmark/configs/nomixer_cpu_mem.yaml
  perf/benchmark/configs/nomixer_latency.yaml
  perf/benchmark/configs/telemetryv2_cpu_mem.yaml
  perf/benchmark/configs/telemetryv2_latency.yaml
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/Pipfile
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/L

#477 kill envoy regardless of how we exit the script
  perf/load/templates/config-changer.yaml
Labels: cla: yes, lifecycle/needs-triage, size/XS

#523 Reverting python changes to build-tools Dockerfile
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#524 copy the whole dir to gcs bucket
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#525 Force the branch to master.
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/XS

#526 add mesh telemetry role
  perf/istio-install/create_sa.sh
Labels: cla: yes, size/XS

#527 Fixing broken build-tools image
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#529 Add All func to annotations
  .gitignore
  cmd/annotations_prep/main.go
Labels: cla: yes, size/S

#530 collect flame graph when all tests is done
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#531 Attempted fix for python on bionic
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#482 Sync operator installation
  perf/istio-install/istio_operator.sha
  perf/istio-install/operator_default.yaml
  perf/istio-install/setup_istio_operator.sh
Labels: cla: yes, size/S

#533 Use default value for config file
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/S

#532 Some fixes to gen tools
  cmd/annotations_prep/main.go
  cmd/protoc-gen-deepcopy/deepcopy/plugin.go
  cmd/protoc-gen-deepcopy/test/deepcopy_test.go
  cmd/protoc-gen-deepcopy/test/generated/types.pb.go
  cmd/protoc-gen-deepcopy/test/generated/types_deepcopy.gen.go
  cmd/protoc-gen-deepcopy/test/types.proto
  go.mod
  go.sum
  licenses/github.com/docopt/docopt-go/LICENSE
Labels: cla: yes, size/M

#517 Improve the root-transition script.
  bin/root-transition.sh
Labels: cla: yes, size/L

#535 Fixing python on bionic
  docker/build-tools/Dockerfile
Labels: cla: yes, size/M

#534 Fix deepcopy gen
  cmd/protoc-gen-deepcopy/README.md
  cmd/protoc-gen-deepcopy/deepcopy/plugin.go
  cmd/protoc-gen-deepcopy/test/deepcopy_test.go
  cmd/protoc-gen-deepcopy/test/generated/types.pb.go
  cmd/protoc-gen-deepcopy/test/generated/types_deepcopy.gen.go
  cmd/protoc-gen-deepcopy/test/types.proto
  go.sum
Labels: cla: yes, size/M

#538 Add ssh to build tools
  docker/build-tools/Dockerfile
Labels: cherrypick/release-1.4, cla: yes, size/XS

#539 [release-1.4] Add ssh to build tools
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#537 Updating common-files
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/S

#540 Release 1.4 benchmark recent updates
  perf/benchmark/README.md
  perf/benchmark/configs/mixer_cpu_mem.yaml
  perf/benchmark/configs/mixer_latency.yaml
  perf/benchmark/configs/nomixer_cpu_mem.yaml
  perf/benchmark/configs/nomixer_latency.yaml
  perf/benchmark/configs/telemetryv2_cpu_mem.yaml
  perf/benchmark/configs/telemetryv2_latency.yaml
  perf/benchmark/linkerd/README.md
  perf/benchmark/linkerd/example-comparison/istio_vs_linkerd.png
  perf/benchmark/linkerd/example-comparison/telemetryv2_vs_linkerd.png
  perf/benchmark/linkerd/setup_linkerd.sh
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/Pipfile
  perf/benchmark/runner/runner.py
  perf/benchmark/setup_test.sh
Labels: cla: yes, size/L

#541 Add telemetry v2 section to README
  perf/benchmark/README.md
Labels: cla: yes, size/XS

#542 Update the weight value for the generated annotations.pb.html file.
  cmd/annotations_prep/main.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#543 [release-1.4] Update the weight value for the generated annotations.pb.html file.
  cmd/annotations_prep/main.go
Labels: cla: yes, size/XS

#544 cherrypick kubetype-gen import fix
  cmd/kubetype-gen/generators/types.go
Labels: cla: yes, size/XS

#545 Remove old benchmark data files
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-165728_193ff770_qps_1000_c_1_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-170128_193ff770_qps_1000_c_1_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-170529_193ff770_qps_1000_c_1_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-170929_193ff770_qps_1000_c_2_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-171329_193ff770_qps_1000_c_2_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-171730_193ff770_qps_1000_c_2_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-172130_193ff770_qps_1000_c_4_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-172530_193ff770_qps_1000_c_4_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-172931_193ff770_qps_1000_c_4_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-173331_193ff770_qps_1000_c_8_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-173731_193ff770_qps_1000_c_8_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-174132_193ff770_qps_1000_c_8_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-174532_193ff770_qps_1000_c_16_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-174932_193ff770_qps_1000_c_16_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-175333_193ff770_qps_1000_c_16_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-175733_193ff770_qps_1000_c_32_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-180134_193ff770_qps_1000_c_32_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-180534_193ff770_qps_1000_c_32_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-180937_193ff770_qps_1000_c_64_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-181337_193ff770_qps_1000_c_64_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-181738_193ff770_qps_1000_c_64_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-182412_7c63ca64_qps_1000_c_1_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-182812_7c63ca64_qps_1000_c_1_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-183212_7c63ca64_qps_1000_c_2_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-183612_7c63ca64_qps_1000_c_2_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-184013_7c63ca64_qps_1000_c_4_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-184413_7c63ca64_qps_1000_c_4_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-184814_7c63ca64_qps_1000_c_8_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-185214_7c63ca64_qps_1000_c_8_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-185614_7c63ca64_qps_1000_c_16_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-190015_7c63ca64_qps_1000_c_16_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-190416_7c63ca64_qps_1000_c_32_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-190816_7c63ca64_qps_1000_c_32_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-191217_7c63ca64_qps_1000_c_64_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-191617_7c63ca64_qps_1000_c_64_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/compiled-results.json
  perf/benchmark/results-istio-1.2.0-fortio/p50.png
  perf/benchmark/results-istio-1.2.0-fortio/p90.png
  perf/benchmark/results-istio-1.2.0-fortio/p99.png
Labels: cla: yes, size/XXL

#546 Update Helm to v2.16.1
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#536 [release-1.4] Improve the root-transition script.
  bin/root-transition.sh
Labels: cla: yes, size/L

#548 get rid of conn=1 since qps cannot reach 1000 which cause data point missing
  perf/benchmark/configs/mixer_latency.yaml
  perf/benchmark/configs/nomixer_latency.yaml
  perf/benchmark/configs/telemetryv2_latency.yaml
Labels: cla: yes, size/XS

#549 Add groupName comment tag in kubetype-gen generated doc.go
  cmd/kubetype-gen/generators/package.go
Labels: cla: yes, ok-to-test, size/XS

#550 only set mixer label for istio
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#553 flush out kubectl command to log for debugging perf
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#554 explicit inject istio or linkerd via ISTIO_INJECT or LINKERD_INJECT
  perf/benchmark/README.md
  perf/benchmark/runner/runner.py
  perf/benchmark/setup_test.sh
  perf/benchmark/values.yaml
Labels: cla: yes, size/S

#556 enable ISTIO_INJECT in run_perf_benchmark script
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#557 Cherry pick #549
  cmd/kubetype-gen/generators/package.go
Labels: cla: yes, ok-to-test, size/XS

#558 fix sidecar injection issue
  perf/benchmark/README.md
  perf/benchmark/linkerd/README.md
  perf/benchmark/setup_test.sh
Labels: cla: yes, size/S

#562 Add some debugging information to flame graph part
  perf/benchmark/runner/runner.py
  perf/benchmark/setup_test.sh
Labels: cla: yes, size/S

#564 Add boskos setup and update benchmark script
  bin/setup_cluster.sh
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/L

#565 Fix flame sh path
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#563 make namespace an env var instead of a fixed name
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/setup_test.sh
  perf/istio-install/setup_istio_new_installer.sh
  perf/load/auto-mtls/setup.sh
  perf/load/pilot/setup.sh
  perf/stability/gateway-bouncer/setup.sh
Labels: cla: yes, size/M

#566 Fix flame output dir path issue
  perf/benchmark/README.md
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/M

#569 Prepare cue-gen for multi version schema
  cmd/cue-gen/build.go
  cmd/cue-gen/crd.go
  cmd/cue-gen/genoapi.go
  go.mod
  go.sum
Labels: cla: yes, size/L

#571 Fix the tools build
  go.mod
  go.sum
Labels: cla: yes, size/S

#568 Upgrade kind to v0.6.0
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#573 add a readme for cue-gen
  cmd/cue-gen/README.md
Labels: cla: yes, size/M

#572 Allow dry run for build tools
  Makefile.core.mk
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/S

#574 Remove unused badge
  README.md
  pkg/checker/README.md
Labels: cla: yes, size/XS

#559 auto mTLS perf test suite enhancement.
  perf/benchmark/runner/runner.py
  perf/istio-install/README.md
  perf/istio-install/automtls.yaml
  perf/istio-install/setup_istio_operator.sh
  perf/istio-install/values-auto-mtls.yaml
  perf/load/auto-mtls/Dockerfile
  perf/load/auto-mtls/README.md
  perf/load/auto-mtls/istio.sh
  perf/load/auto-mtls/scale.py
  perf/load/auto-mtls/setup.sh
  perf/load/auto-mtls/templates/config-changer.yaml
  perf/load/auto-mtls/templates/service-graph.gen.yaml
  perf/load/auto-mtls/values.yaml
  perf/load/loadclient/setup_test.sh
Labels: cla: yes, size/L

#578 Use a more consolidated repo for go-bindata
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#576 Update web site tooling.
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#580 update python environment preparation steps
  perf/benchmark/README.md
Labels: cla: yes, ok-to-test, size/XS

#579 Fix config yaml file bug not found
  perf/benchmark/README.md
Labels: cla: yes, ok-to-test, size/XS

#577 Update perf README and runner.py
  perf/benchmark/README.md
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/S

#582 update perf benchmark to sync with master
  perf/benchmark/README.md
  perf/benchmark/configs/mixer_latency.yaml
  perf/benchmark/configs/nomixer_latency.yaml
  perf/benchmark/configs/telemetryv2_latency.yaml
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/runner.py
  perf/benchmark/setup_test.sh
Labels: cla: yes, size/L

#583 [release-1.4] Add boskos setup and update benchmark script (#564)
  bin/setup_cluster.sh
Labels: cla: yes, size/L

#551 generate istio.io related manifest when ISTIO_INJECT=true
  perf/benchmark/templates/fortio.yaml
Labels: cla: yes, size/XS

#585 Some fix to cue-gen
  cmd/cue-gen/build.go
  cmd/cue-gen/crd.go
  cmd/cue-gen/genoapi.go
  cmd/protoc-gen-deepcopy/README.md
Labels: cla: yes, size/M
