Repository istio/tools, pull requests merged in 2019-07, with the labels that each got.

#208 Added probabilistic call
  isotope/convert/pkg/graph/script/request_command.go
  isotope/service/pkg/srv/executable.go
Labels: cla: yes

#210 Update install-vals
  perf/benchmark/values.yaml
  perf/istio-install/base/templates/als.yaml
  perf/istio-install/base/templates/istio-gateway.yaml
  perf/istio-install/base/values.yaml
  perf/istio-install/create_cluster.sh
  perf/istio-install/values.yaml
  perf/load/common.sh
  perf/load/loadclient/setup_test.sh
  perf/load/loadclient/templates/load_gen.yaml
  perf/load/loadclient/values.yaml
Labels: cla: yes

#203 [perf/benchmark] Adds raw fortio JSON results, Istio 1.2.0
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-165728_193ff770_qps_1000_c_1_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-170128_193ff770_qps_1000_c_1_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-170529_193ff770_qps_1000_c_1_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-170929_193ff770_qps_1000_c_2_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-171329_193ff770_qps_1000_c_2_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-171730_193ff770_qps_1000_c_2_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-172130_193ff770_qps_1000_c_4_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-172530_193ff770_qps_1000_c_4_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-172931_193ff770_qps_1000_c_4_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-173331_193ff770_qps_1000_c_8_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-173731_193ff770_qps_1000_c_8_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-174132_193ff770_qps_1000_c_8_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-174532_193ff770_qps_1000_c_16_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-174932_193ff770_qps_1000_c_16_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-175333_193ff770_qps_1000_c_16_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-175733_193ff770_qps_1000_c_32_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-180134_193ff770_qps_1000_c_32_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-180534_193ff770_qps_1000_c_32_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-180937_193ff770_qps_1000_c_64_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-181337_193ff770_qps_1000_c_64_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-181738_193ff770_qps_1000_c_64_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-182412_7c63ca64_qps_1000_c_1_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-182812_7c63ca64_qps_1000_c_1_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-183212_7c63ca64_qps_1000_c_2_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-183612_7c63ca64_qps_1000_c_2_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-184013_7c63ca64_qps_1000_c_4_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-184413_7c63ca64_qps_1000_c_4_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-184814_7c63ca64_qps_1000_c_8_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-185214_7c63ca64_qps_1000_c_8_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-185614_7c63ca64_qps_1000_c_16_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-190015_7c63ca64_qps_1000_c_16_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-190416_7c63ca64_qps_1000_c_32_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-190816_7c63ca64_qps_1000_c_32_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-191217_7c63ca64_qps_1000_c_64_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-191617_7c63ca64_qps_1000_c_64_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/compiled-results.json
  perf/benchmark/results-istio-1.2.0-fortio/p50.png
  perf/benchmark/results-istio-1.2.0-fortio/p90.png
  perf/benchmark/results-istio-1.2.0-fortio/p99.png
Labels: cla: yes

#211 Add py script to automate dns registration
  bin/update_dns.py
Labels: cla: yes

#191 Update path for installer
  .circleci/config.yml
  Makefile
Labels: cla: yes

#197 Initial check in of genoapi tool for CUE pipeline
  .gitignore
  go.mod
  go.sum
  openapi/cue/assets_dev.go
  openapi/cue/assets_gen.go
  openapi/cue/assets_vfsdata.go
  openapi/cue/build.go
  openapi/cue/doc.cue
  openapi/cue/genoapi.go
Labels: cla: yes

#216 fix linkerd2 benchmark readme
  perf/benchmark/linkerd/README.md
Labels: cla: yes, size/XS

#213 move protoc openapi to openapi directory
  openapi/protoc-gen-openapi/Makefile
  openapi/protoc-gen-openapi/README.md
  openapi/protoc-gen-openapi/integration_test.go
  openapi/protoc-gen-openapi/main.go
  openapi/protoc-gen-openapi/openapiGenerator.go
  openapi/protoc-gen-openapi/testdata/golden/openapiv3.json
  openapi/protoc-gen-openapi/testdata/golden/testRef/openapiv3.json
  openapi/protoc-gen-openapi/testdata/golden/testpkg.json
  openapi/protoc-gen-openapi/testdata/golden/testpkg2.json
  openapi/protoc-gen-openapi/testdata/testpkg/test1.proto
  openapi/protoc-gen-openapi/testdata/testpkg/test2.proto
  openapi/protoc-gen-openapi/testdata/testpkg/test6.proto
  openapi/protoc-gen-openapi/testdata/testpkg2/test3.proto
Labels: cla: yes

#219 Fix cue openapi generator per-file generation filename
  openapi/cue/build.go
Labels: cla: yes, size/S

#201 Add crds definitions creation
  isotope/runner/istio.py
Labels: cla: yes

#221 Optimize description output of the openapi generator
  openapi/cue/genoapi.go
Labels: cla: yes, size/XS

#222 Workaround problem with blackfriday.v2
  go.mod
  go.sum
  protoc-gen-docs/htmlGenerator.go
Labels: cla: yes, size/S

#224 Move these from the istio/api repo.
  cmd/annotations_prep/main.go
  docker/api-build-tools/Dockerfile
  docker/api-build-tools/build-and-push.sh
  docker/protoc/Dockerfile
  docker/protoc/build-and-push.sh
  docker/protolock/Dockerfile
  docker/protolock/build-and-push.sh
Labels: cla: yes, size/L

#226 Add cue image to the docker directory
  docker/cue/Dockerfile
  docker/cue/build-and-push.sh
Labels: cla: yes, size/M

#227 Moving these from the istio.io repo.
  docker/website-tools/Dockerfile
  docker/website-tools/build_and_push.sh
Labels: cla: yes, size/M

#228 Fix missing Instance type.
  cmd/annotations_prep/main.go
  docker/api-build-tools/Dockerfile
Labels: cla: yes, size/S

#229 Make the protoc container much smaller
  docker/protoc/Dockerfile
Labels: cla: yes, size/S

#225 Add stability test for infinite looping
  perf/stability/looper/Chart.yaml
  perf/stability/looper/README.md
  perf/stability/looper/main.go
  perf/stability/looper/templates/client.yaml
  perf/stability/looper/templates/server.yaml
  perf/stability/looper/values.yaml
  perf/stability/stability.mk
Labels: cla: yes, size/L

#230 Unify api-build-tools and tidy Dockerfile
  docker/api-build-tools/Dockerfile
  docker/protoc/Dockerfile
  docker/protoc/build-and-push.sh
  docker/protolock/Dockerfile
  docker/protolock/build-and-push.sh
Labels: cla: yes, size/L

#231 Update container definition.
  docker/api-build-tools/Dockerfile
  go.mod
  go.sum
Labels: cla: yes, size/M

#233 Dockerfile for v1.2.2 (our forked version)
  docker/api-build-tools/Dockerfile
Labels: cla: yes, size/S

#235 Point to the upstream version of gogo/protobuf.
  docker/api-build-tools/Dockerfile
  go.mod
  go.sum
Labels: cla: yes, size/S
