Repository istio/tools, pull requests merged in 2019-12, with the labels that each got.

#587 common-files update master-2019-11-26T07-29-27
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#584 OPERATOR_SHA customizable from caller.
  perf/istio-install/setup_istio_operator.sh
Labels: cla: yes, size/S

#595 Add data for ingress benchmark to generated graph
  perf/benchmark/runner/graph.py
Labels: cla: yes, size/XS

#594 Allow cue-gen to use user-specified schema name
  cmd/cue-gen/build.go
  cmd/cue-gen/genoapi.go
Labels: cla: yes, size/M

#597 move upgrade test to tools
  upgrade/run_upgrade_test.sh
  upgrade/test_crossgrade.sh
Labels: cla: yes, size/XL

#596 Downgrade to golangci-lint 1.19.1
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#598 Fix telemetry v2 filters path
  perf/benchmark/README.md
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/S

#600 Update ruby version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#599 Allow to use https for ingress and set a cacert
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/M

#604 update upgrade script
  go.mod
  go.sum
  upgrade/templates/fortio-cli.yaml
  upgrade/templates/fortio.yaml
  upgrade/templates/gateway.yaml
  upgrade/test_crossgrade.sh
Labels: cla: yes, size/L

#605 Sort the output of cue-gen
  cmd/cue-gen/genoapi.go
Labels: cla: yes, size/S

#547 Improve GCP setup
  perf/istio-install/README.md
  perf/istio-install/create_cluster.sh
  perf/istio-install/create_sa.sh
Labels: cla: yes, size/L

#555 add istioctl installation option and use for perf install
  perf/benchmark/run_benchmark_job.sh
  perf/istio-install/operator_default.yaml
  perf/istio-install/setup_istio.sh
  perf/istio-install/setup_istio_operator.sh
Labels: cla: yes, size/L

#606 fix perf memory metric keyword error
  perf/benchmark/runner/fortio.py
Labels: cla: yes, size/XS

#607 Incorrect configmap name in create_cluster.sh
  perf/istio-install/README.md
  perf/istio-install/create_cluster.sh
Labels: cla: yes, ok-to-test, size/XS

#608 Trigger container build
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#609 Don't use -u when running go get
  docker/build-tools/Dockerfile
Labels: cla: yes, size/M

#610 Upgrade to latest Hugo.
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#612 fix mixer_mode label error for v2-nullvm
  perf/benchmark/configs/telemetryv2_cpu_mem.yaml
Labels: cla: yes, size/XS

#614 remove perf_data repo
  perf_dashboard/perf_data/master.csv
  perf_dashboard/perf_data/perf.csv
  perf_dashboard/perf_data/release-1.4.csv
  perf_dashboard/perf_data/tmp3f9jejbf.csv
Labels: cla: yes, size/L

#613 Use SHA for tools version to pull
  docker/build-tools/Dockerfile
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/S

#611 Fix mason_client fetch
  bin/setup_cluster.sh
Labels: cherrypick/release-1.4, cla: yes, size/XS

#619 [release-1.4] Fix mason_client fetch
  bin/setup_cluster.sh
Labels: cla: yes, size/XS

#620 Add "pr-creator" to build-tools image
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#591 add linkerd run benchmark job script
  perf/benchmark/configs/istio/mixer_cpu_mem.yaml
  perf/benchmark/configs/istio/mixer_latency.yaml
  perf/benchmark/configs/istio/nomixer_cpu_mem.yaml
  perf/benchmark/configs/istio/nomixer_latency.yaml
  perf/benchmark/configs/istio/telemetryv2_cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_latency.yaml
  perf/benchmark/configs/linkerd/linkerd_latency.yaml
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/M

#602 Fail docker build if there is an error
  docker/build-tools/build-and-push.sh
  docker/build-tools/prow-entrypoint.sh
Labels: cla: yes, size/S

#621 Fixing create_cluster.sh
  perf/istio-install/create_cluster.sh
  perf/istio-install/create_sa.sh
Labels: cla: yes, size/L

#617 Dockerize perf dashboard and add installation txt
  perf_dashboard/MVC_pattern.png
  perf_dashboard/README.md
  perf_dashboard/docker-compose.yml
  perf_dashboard/dockerfile
  perf_dashboard/requirements.txt
Labels: cla: yes, size/M

#624 Improve docker entrypoint
  docker/build-tools/prow-entrypoint.sh
Labels: cla: yes, size/S

#623 Add dropdown list feature for latency perf page
  perf_dashboard/README.md
  perf_dashboard/benchmarks/download.py
  perf_dashboard/benchmarks/templates/latency.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/docker-compose.yml
  perf_dashboard/dockerfile
  perf_dashboard/requirements.txt
Labels: cla: yes, size/L

#626 add dropdown list for cpu and memory usage page
  perf_dashboard/benchmarks/templates/cpu-memory.html
  perf_dashboard/benchmarks/views.py
Labels: cla: yes, size/M

#627 pipenv is not available in build tools image
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#625 [release-1.4] cherry-pick recent perf changes in master branch to 1.4
  perf/benchmark/README.md
  perf/benchmark/configs/telemetryv2_cpu_mem.yaml
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/fortio.py
Labels: cla: yes, size/S

#628 Make Artifacts dynamically link to corresponding GCS bucket
  perf_dashboard/__init__.py
  perf_dashboard/artifacts/templates/artifact.html
  perf_dashboard/artifacts/views.py
  perf_dashboard/benchmarks/views.py
  perf_dashboard/helpers/__init__.py
  perf_dashboard/helpers/download.py
Labels: cla: yes, size/L

#630 fix meshexpansion
  perf/istio-install/values-istio-postsubmit.yaml
Labels: cla: yes, size/XS

#631 make days as param configurable in download func
  perf_dashboard/artifacts/views.py
  perf_dashboard/benchmarks/views.py
  perf_dashboard/helpers/download.py
Labels: cla: yes, size/S

#633 Update to latest Hugo
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#635 [release-1.4] fix meshexpansion
  perf/istio-install/values-istio-postsubmit.yaml
Labels: cla: yes, size/XS

#632 implement regression pattern graph
  perf_dashboard/artifacts/templates/artifact.html
  perf_dashboard/artifacts/views.py
  perf_dashboard/assets/js/cur_alert.js
  perf_dashboard/assets/js/master_alert.js
  perf_dashboard/benchmarks/templates/cpu-memory.html
  perf_dashboard/benchmarks/templates/flame_graph.html
  perf_dashboard/benchmarks/templates/latency.html
  perf_dashboard/benchmarks/templates/micro_benchmarks.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/configurations/templates/configurations.html
  perf_dashboard/helpers/download.py
  perf_dashboard/regression_alerts/templates/cur_alert.html
  perf_dashboard/regression_alerts/templates/master_alert.html
  perf_dashboard/regression_alerts/urls.py
  perf_dashboard/regression_alerts/views.py
  perf_dashboard/release_builds/templates/release_builds.html
  perf_dashboard/templates/index.html
Labels: cla: yes, size/XL

#636 add p99 regression pattern graph for both master and current release
  perf_dashboard/assets/js/alert_common_func.js
  perf_dashboard/assets/js/cur_alert.js
  perf_dashboard/assets/js/master_alert.js
  perf_dashboard/helpers/download.py
  perf_dashboard/regression_alerts/templates/cur_alert.html
  perf_dashboard/regression_alerts/templates/master_alert.html
  perf_dashboard/regression_alerts/views.py
  perf_dashboard/templates/base.html
Labels: cla: yes, size/XL

#637 common-files update master-2019-12-15T16-17-48
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/license-lint.yml
Labels: cla: yes, size/S

#638 fix perf benchmark deployment issue
  perf/benchmark/run_benchmark_job.sh
  perf/istio-install/operator_default.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#629 make service port name template
  perf/load/templates/service-graph.gen.yaml
  perf/load/values.yaml
Labels: cla: yes, size/XS

#567 add servicegraph load test job
  perf/benchmark/run_benchmark_job.sh
  perf/load/run_servicegraph_job.sh
Labels: cla: yes, size/L

#561 Add different installation profiles
  perf/istio-install/istio_operator.sha
  perf/istio-install/istioctl_profiles/automtls.yaml
  perf/istio-install/istioctl_profiles/default.yaml
  perf/istio-install/istioctl_profiles/istio-non-sds.yaml
  perf/istio-install/istioctl_profiles/multi-citadel-non-sds.yaml
  perf/istio-install/istioctl_profiles/sds-auth.yaml
  perf/istio-install/setup_istio.sh
  perf/istio-install/setup_istio_operator.sh
Labels: cla: yes, size/M

#640 [release-1.4] fix perf benchmark deployment issue (#638)
  perf/benchmark/run_benchmark_job.sh
  perf/istio-install/operator_default.yaml
Labels: cla: yes, size/M

#639 Kill all docker containers as well
  docker/build-tools/prow-entrypoint.sh
Labels: cla: yes, size/XS

#641 [release-1.4] merge recent create_cluster and run perf script changes to 1.4 branch
  perf/benchmark/run_benchmark_job.sh
  perf/istio-install/create_cluster.sh
  perf/istio-install/create_sa.sh
Labels: cla: yes, size/L

#601 Update docs for cacert argument
  perf/benchmark/README.md
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/M

#643 fix prometheus part
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#642 update benchmark test nomixer and mixer label
  perf/benchmark/README.md
  perf/benchmark/configs/istio/mixer_cpu_mem.yaml
  perf/benchmark/configs/istio/mixer_latency.yaml
  perf/benchmark/configs/istio/none_cpu_mem.yaml
  perf/benchmark/configs/istio/none_latency.yaml
  perf/benchmark/configs/istio/telemetryv2_cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_latency.yaml
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/M

#647 Fix path error for benchmark runner
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#646 deprecate release build page
  perf_dashboard/README.md
  perf_dashboard/artifacts/templates/artifact.html
  perf_dashboard/benchmarks/templates/cpu-memory.html
  perf_dashboard/benchmarks/templates/flame_graph.html
  perf_dashboard/benchmarks/templates/latency.html
  perf_dashboard/benchmarks/templates/micro_benchmarks.html
  perf_dashboard/configurations/templates/configurations.html
  perf_dashboard/perf_dashboard/settings.py
  perf_dashboard/perf_dashboard/urls.py
  perf_dashboard/regression_alerts/templates/cur_alert.html
  perf_dashboard/regression_alerts/templates/master_alert.html
  perf_dashboard/release_builds/__init__.py
  perf_dashboard/release_builds/admin.py
  perf_dashboard/release_builds/apps.py
  perf_dashboard/release_builds/migrations/__init__.py
  perf_dashboard/release_builds/models.py
  perf_dashboard/release_builds/templates/release_builds.html
  perf_dashboard/release_builds/tests.py
  perf_dashboard/release_builds/urls.py
  perf_dashboard/release_builds/views.py
  perf_dashboard/templates/index.html
Labels: cla: yes, size/XL

#648 Release-1.4 cherry pick changes of benchmark
  perf/benchmark/run_benchmark_job.sh
  perf/istio-install/istio_operator.sha
  perf/istio-install/istioctl_profiles/automtls.yaml
  perf/istio-install/istioctl_profiles/default.yaml
  perf/istio-install/istioctl_profiles/istio-non-sds.yaml
  perf/istio-install/istioctl_profiles/multi-citadel-non-sds.yaml
  perf/istio-install/istioctl_profiles/sds-auth.yaml
  perf/istio-install/setup_istio.sh
  perf/istio-install/setup_istio_operator.sh
Labels: cla: yes, size/L

#645 deprecate configuration page in favor of mako tags
  perf_dashboard/README.md
  perf_dashboard/artifacts/templates/artifact.html
  perf_dashboard/benchmarks/templates/cpu-memory.html
  perf_dashboard/benchmarks/templates/flame_graph.html
  perf_dashboard/benchmarks/templates/latency.html
  perf_dashboard/benchmarks/templates/micro_benchmarks.html
  perf_dashboard/configurations/__init__.py
  perf_dashboard/configurations/admin.py
  perf_dashboard/configurations/apps.py
  perf_dashboard/configurations/migrations/__init__.py
  perf_dashboard/configurations/models.py
  perf_dashboard/configurations/tests.py
  perf_dashboard/configurations/urls.py
  perf_dashboard/configurations/views.py
  perf_dashboard/perf_dashboard/settings.py
  perf_dashboard/perf_dashboard/urls.py
  perf_dashboard/regression_alerts/templates/cur_alert.html
  perf_dashboard/regression_alerts/templates/master_alert.html
  perf_dashboard/templates/index.html
Labels: cla: yes, size/L

#651 fix namespace of linkerd test
  perf/benchmark/run_benchmark_job.sh
Labels: cherrypick/release-1.4, cla: yes, size/XS

#650 Fix Makefile regex
  docker/build-tools/bashrc
Labels: cla: yes, size/XS

#654 [release-1.4] perf pipeline fix: get rid of linkerd tests for 1.4
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/M

#656 Allow kubetype gen to register scheme in lower case
  cmd/kubetype-gen/generators/naming.go
  cmd/kubetype-gen/generators/register.go
  go.mod
  go.sum
Labels: cla: yes, size/M

#653 Plain text profile as two pods benchmark testing.
  perf/benchmark/README.md
  perf/benchmark/configs/istio/plaintex_cpu_mem.yaml
  perf/benchmark/configs/istio/plaintext_latency.yaml
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/graph.py
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/L

#649 Fix deployment scaler
  perf/load/templates/config-changer.yaml
Labels: cla: yes, size/XS
