Repository istio/tools, pull requests merged in 2019-09, with the labels that each got.

#320 Enable docker file linting.
  Makefile.core.mk
  perf/docker/Dockerfile.rabbitmq
  perf/docker/Dockerfile.redis
  perf/load/rotate/Dockerfile
Labels: cla: yes, size/S

#322 Add securityyContext to template and cleanup unused variable
  perf/benchmark/templates/fortio.yaml
  perf/benchmark/values.yaml
Labels: cla: yes, size/S

#321 Do a bit of cleanup.
  cmd/cue/assets.gen.go
  cmd/cue/build.go
  cmd/cue/crd.go
  cmd/cue/doc.cue
  cmd/cue/genoapi.go
  cmd/protoc-gen-docs/Makefile
  cmd/protoc-gen-docs/README.md
  cmd/protoc-gen-docs/dictionaries/custom.txt
  cmd/protoc-gen-docs/dictionaries/en-US.aff
  cmd/protoc-gen-docs/dictionaries/en-US.dic
  cmd/protoc-gen-docs/htmlGenerator.go
  cmd/protoc-gen-docs/main.go
  cmd/protoc-gen-docs/testdata/test1.proto
  cmd/protoc-gen-docs/testdata/test2.proto
  cmd/protoc-gen-docs/testdata/test3.proto
  cmd/protoc-gen-docs/testdata/test4.proto
  cmd/protoc-gen-docs/testdata/test6.proto
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#324 Increase prometheus retention to 3d
  perf/prometheus-install/prometheus.yaml
Labels: cla: yes, size/XS

#327 Update perf benchmark docs with clearer examples
  perf/benchmark/README.md
Labels: cla: yes, size/S

#328 fix the sidecarInjectorWebhook name
  perf/istio-install/values-istio-postsubmit.yaml
  perf/istio-install/values-new-installer.yaml
  perf/istio-install/values.yaml
Labels: cla: yes, size/XS

#310 Fix benchmark --perf label errors
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#323 Simplify the port-forward command an cleanup markdown
  perf/benchmark/README.md
Labels: cla: yes, size/M

#329 Fix Flame Graph generation issue by using --perf label
  perf/benchmark/README.md
  perf/benchmark/flame/README.md
  perf/benchmark/flame/flame.sh
  perf/benchmark/runner/fortio.py
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/M

#330 Revert delete the import commit, it should be required
  perf/benchmark/runner/fortio.py
Labels: cla: yes, size/XS

#331 Correct port forward command for Prometheus
  perf/benchmark/README.md
Labels: cla: yes, size/S

#332 Set environment variable for GKE_VERION
  perf/benchmark/README.md
Labels: cla: yes, size/XS

#336 update setup install step
  perf/istio-install/setup_istio.sh
Labels: cla: yes, size/S

#334 Update CODEOWNERS
  CODEOWNERS
Labels: cla: yes, size/XS

#333 Enable script linting.
  Makefile.core.mk
  bin/redeploy.sh
  bin/root-transition.sh
  docker/build-tools/build-and-push.sh
  examples/luacheck/setup.sh
  perf/auto-qual-test/base/deploy_latest_daily.sh
  perf/auto-qual-test/base/redeploy.sh
  perf/benchmark/linkerd/setup_linkerd.sh
  perf/benchmark/setup_test.sh
  perf/istio-install/create_cluster.sh
  perf/istio-install/setup_istio.sh
  perf/istio-install/setup_istio_new_installer.sh
  perf/istio-install/setup_istio_release.sh
  perf/istio-install/setup_prometheus.sh
  perf/load/common.sh
  perf/load/loadclient/setup_test.sh
  perf/load/pilot/setup.sh
  perf/load/setup_large_test.sh
  perf/other/multicluster-vpc/setup.sh
  perf/security/file-mount-tests/non-sds-1/cleanup.sh
  perf/security/file-mount-tests/non-sds-1/setup_test.sh
  perf/security/file-mount-tests/non-sds-2/cleanup.sh
  perf/security/file-mount-tests/non-sds-2/setup_test.sh
  perf/security/sds-tests/citadel-1/cleanup.sh
  perf/security/sds-tests/citadel-1/setup_test.sh
  perf/security/sds-tests/citadel-2/cleanup.sh
  perf/security/sds-tests/citadel-2/setup_test.sh
  perf/security/utils/test-util.sh
  perf/stability/allconfig/setup.sh
  perf/stability/gateway-bouncer/setup.sh
  perf/stability/mysql/setup.sh
  perf/stability/sds-certmanager/setup.sh
  perf/stability/setup_test.sh
  setup/stability-extra/multicluster-vpn/default/setup.sh
  setup/stability-extra/multicluster-vpn/locality-distribute/setup.sh
  setup/stability-extra/multicluster-vpn/locality-failover/setup.sh
  setup/stability-extra/multicluster-vpn/setup.sh
Labels: cla: yes, size/L

#338 Fix most helm linting errors.
  examples/luacheck/Chart.yaml
  perf/benchmark/Chart.yaml
  perf/istio-install/base/Chart.yaml
  perf/load/Chart.yaml
  perf/load/loadclient/Chart.yaml
  perf/load/pilot/Chart.yaml
  perf/load/values.yaml
  perf/security/file-mount-tests/non-sds-2/Chart.yaml
  perf/security/sds-tests/citadel-2/Chart.yaml
  perf/security/workload-deployments/Chart.yaml
  perf/stability/allconfig/Chart.yaml
  perf/stability/gateway-bouncer/Chart.yaml
  perf/stability/gateway-bouncer/values.yaml
  perf/stability/graceful-shutdown/Chart.yaml
  perf/stability/http10/Chart.yaml
  perf/stability/istio-chaos-partial/Chart.yaml
  perf/stability/istio-chaos-total/Chart.yaml
  perf/stability/istio-upgrader/Chart.yaml
  perf/stability/looper/Chart.yaml
  perf/stability/multicluster-vpn/Chart.yaml
  perf/stability/mysql/Chart.yaml
  perf/stability/rabbitmq/Chart.yaml
  perf/stability/rabbitmq/values.yaml
  perf/stability/redis/Chart.yaml
  perf/stability/sds-certmanager/Chart.yaml
  perf/stability/sds-certmanager/values.yaml
Labels: cla: yes, size/M

#339 Update common and fix helm linting
  .gitattributes
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  perf/benchmark/values.yaml
  perf/load/loadclient/values.yaml
  perf/load/templates/_rbac.yaml
  perf/load/values.yaml
  perf/stability/sds-certmanager/values.yaml
Labels: cla: yes, size/M

#326 Cleanup some pylint issues in benchmark Python code
  perf/benchmark/README.md
  perf/benchmark/runner/fortio.py
  perf/benchmark/runner/graph.py
  perf/benchmark/runner/prom.py
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/M

#345 Validate duration for benchmark
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#354 Try to fix the prow job that builds the build-tools container.
  Makefile.core.mk
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#356 Update cuelang to v0.0.11
  go.mod
  go.sum
Labels: cla: yes, size/XS

#357 Update to golang 1.13
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#358 Don't try to upgrade kind
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#351 [Istio AutoMTLS] AutoMTLS stability test.
  perf/istio-install/values-auto-mtls.yaml
  perf/load/auto-mtls/Chart.yaml
  perf/load/auto-mtls/Dockerfile
  perf/load/auto-mtls/README.md
  perf/load/auto-mtls/istio.sh
  perf/load/auto-mtls/scale.py
  perf/load/auto-mtls/setup.sh
  perf/load/auto-mtls/templates/config-changer.yaml
  perf/load/auto-mtls/templates/config-map.yaml
  perf/load/auto-mtls/templates/ingress.yaml
  perf/load/auto-mtls/templates/policy-and-dr.yaml
  perf/load/auto-mtls/templates/service-graph.gen.yaml
  perf/load/auto-mtls/values.yaml
Labels: cla: yes, size/L

#359 Improvements to Cue Generator
  cmd/cue-gen/assets.gen.go
  cmd/cue-gen/genoapi.go
  go.sum
Labels: cla: yes, size/L

#239 Various fixes to istio install setup
  metrics/check_metrics.py
  perf/istio-install/setup_istio.sh
  perf/istio-install/values.yaml
Labels: cla: yes, size/M

#341 make NAMESPACE configurable
  perf/benchmark/README.md
  perf/benchmark/linkerd/README.md
  perf/benchmark/setup_test.sh
Labels: cla: yes, size/S

#360 metadata.go: delete useless append for slice
  cmd/kubetype-gen/metadata/metadata.go
Labels: cla: yes, ok-to-test, size/XS

#344 Add tools to support k8s code generation
  Makefile
  cmd/protoc-gen-deepcopy/Makefile
  cmd/protoc-gen-deepcopy/README.md
  cmd/protoc-gen-deepcopy/deepcopy/plugin.go
  cmd/protoc-gen-deepcopy/main.go
  cmd/protoc-gen-deepcopy/test/Makefile
  cmd/protoc-gen-deepcopy/test/deepcopy_test.go
  cmd/protoc-gen-deepcopy/test/generated/types.pb.go
  cmd/protoc-gen-deepcopy/test/generated/types_deepcopy.gen.go
  cmd/protoc-gen-deepcopy/test/types.proto
  cmd/protoc-gen-docs/htmlGenerator.go
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  docker/build-tools/Dockerfile
  docker/build-tools/build-and-push.sh
  go.mod
  go.sum
Labels: cla: yes, size/XL

#146 Refinements of load tests for CDS in 1K workloads.
  perf/load/pilot/README.md
  perf/load/pilot/load_test.py
Labels: cla: yes, size/L

#364 Run 'go mod tidy'.
  go.sum
Labels: cla: yes, size/L

#365 fix bad version in go.mod
  go.mod
  go.sum
Labels: cla: yes, size/S

#352 Update values for installer
  perf/istio-install/setup_istio_new_installer.sh
  perf/istio-install/values-new-installer.yaml
Labels: cla: yes, size/M

#258 Add Makefile target to create and run Docker container for developer
  Makefile
  docker/istio-dev/.gitignore
  docker/istio-dev/Dockerfile
  docker/istio-dev/README.md
  docker/istio-dev/istio-dev.mk
Labels: cla: yes, size/L

#369 Do not remove deprecated fields in CRD schema
  cmd/cue-gen/genoapi.go
  go.mod
  go.sum
Labels: cla: yes, size/S

#361 Fix issues of running graph
  perf/benchmark/runner/graph.py
Labels: cla: yes, size/M

#355 Add benchmark running script
  perf/benchmark/README.md
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/L

#368 Add mixerless telemetry option
  perf/istio-install/setup_istio.sh
Labels: cla: yes, size/XS

#370 Improve how we set GOROOT/GOPATH/GOCACHE
  docker/build-tools/Dockerfile
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/M

#372 Update to latest Hugo.
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#371 Add intermediary content filtering test
  perf/stability/intermediary/Chart.yaml
  perf/stability/intermediary/README.md
  perf/stability/intermediary/templates/client.yaml
  perf/stability/intermediary/templates/intermediary-config.yaml
  perf/stability/intermediary/templates/intermediary-virtualservice.yaml
  perf/stability/intermediary/templates/intermediary.yaml
  perf/stability/intermediary/templates/server.yaml
  perf/stability/intermediary/values.yaml
Labels: cla: yes, size/L

#373 Add dind support
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#375 Fix GOSUMDB
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#374 Push :latest tag for build tools
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/XS

#376 Add an ENTRYPOINT to dockerd-entrypoint
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#377 add a prow entrypoint script
  docker/build-tools/Dockerfile
  docker/build-tools/prow-entrypoint.sh
Labels: cla: yes, size/M

#378 Fix import issue of http client
  perf/benchmark/runner/prom.py
Labels: cla: yes, size/S

#379 Upgrade to golang 1.13.1
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#381 Revert dind
  docker/build-tools/Dockerfile
  docker/build-tools/prow-entrypoint.sh
Labels: cla: yes, size/M

#382 Add a prow entrypoint script
  docker/build-tools/Dockerfile
  docker/build-tools/prow-entrypoint.sh
Labels: cla: yes, size/S

#383 error in dockerfile
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#384 Fix encoding issue
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#380 Use CronJob for deployment scaler
  perf/load/templates/config-changer.yaml
  perf/load/templates/config-map.yaml
Labels: cla: yes, size/M

#385 Update gogo from a random SHA to 1.3.0
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#386 build-tools container updates.
  cmd/check_licenses/check_license/README.md
  cmd/check_licenses/check_license/get_dep_licenses.go
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XL

#387 Dockerfile with dockerd in it...
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#389 Daemonize dockerd
  docker/build-tools/Dockerfile
  docker/build-tools/prow-entrypoint.sh
Labels: cla: yes, size/XS

#390 Start docker daemon with VFS driver
  docker/build-tools/prow-entrypoint.sh
Labels: cla: yes, size/S

#391 Write a new more robust license checker
  cmd/check_licenses/README.md
  cmd/check_licenses/check_license/README.md
  cmd/check_licenses/check_license/get_dep_licenses.go
  cmd/check_licenses/main.go
  cmd/license-lint/README.md
  cmd/license-lint/analysis.go
  cmd/license-lint/collector.go
  cmd/license-lint/config.go
  cmd/license-lint/main.go
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XXL

#367 Lower CPU requests for istio-proxy
  perf/istio-install/values.yaml
Labels: cla: yes, size/XS

#363 Fix some issues/bugs in perf repo
  perf/benchmark/runner/fortio.py
  perf/benchmark/runner/prom.py
  perf/benchmark/runner/runner.py
  perf/benchmark/setup_test.sh
  perf/istio-install/create_cluster.sh
  perf/istio-install/setup_istio.sh
  perf/istio-install/setup_prometheus.sh
Labels: cla: yes, size/L

#394 Improve license linter output.
  cmd/license-lint/analysis.go
  cmd/license-lint/main.go
Labels: cla: yes, size/L

#393 Don't use VFS for docker
  docker/build-tools/Dockerfile
  docker/build-tools/prow-entrypoint.sh
Labels: cla: yes, size/XS

#392 Update common files.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/gobuild.sh
  common/scripts/report_build_info.sh
Labels: cla: yes, size/L

#395 Add GCR credential helper
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#397 make python version to be compatible with multiple versions
  perf/benchmark/runner/Pipfile
Labels: cla: yes, size/XS
