Repository istio/tools, pull requests merged in 2019-10, with the labels that each got.

#399 Remove python version requirement from Pipfile
  perf/benchmark/runner/Pipfile
Labels: cla: yes, size/XS

#396 fix CRD checking no timeout 60s command issue
  perf/istio-install/setup_prometheus.sh
Labels: cla: yes, size/S

#400 Fix a couple bugs in the reference doc extraction tool.
  cmd/protoc-gen-docs/Makefile
  cmd/protoc-gen-docs/htmlGenerator.go
  cmd/protoc-gen-docs/main.go
Labels: cla: yes, size/M

#401 Add service account directory
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#402 Build su-exec into image
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#403 Properly set SETUID bit on su-exec
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#404 need to explicitly tell the interpreter to run python3 for benchmark scripts
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#405 For f prefix formatting on older version
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#406 Display permissions on su-exec at build stages
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#407 preserve setuid through copy-from in prow
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#408 fix sanity check error for csv file in fortio.py
  perf/benchmark/runner/fortio.py
Labels: cla: yes, size/XS

#410 Improve the license linter.
  cmd/license-lint/main.go
Labels: cla: yes, size/M

#411 Avoid exit directly to make retry go through 60 times when sth fails
  perf/istio-install/setup_prometheus.sh
Labels: cla: yes, size/XS

#412 Add some missing error handling.
  cmd/license-lint/main.go
Labels: cla: yes, size/S

#415 Add fpm to the build-tools container.
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#416 Add gcloud to the build-tools container image.
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#417 Remove cruft thought to be needed by cni but not
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#418 Add a few directories that some build tools need.
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#420 Remove su-exec from buildtools
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#419 Add support for a resource field in annotation definitions.
  cmd/annotations_prep/main.go
Labels: cla: yes, size/XS

#423 Add doc link to schema descriptions in CRDs
  cmd/cue-gen/genoapi.go
  go.mod
  go.sum
Labels: cla: yes, size/M

#424 Trigger container rebuild.
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#425 Fix container paths.
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#426 Emit resource types in generated Go code.
  cmd/annotations_prep/main.go
Labels: cla: yes, size/M

#427 Updates for GOBIN
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#428 Add a docker login
  docker/build-tools/prow-entrypoint.sh
Labels: cla: yes, size/XS

#429 Update common files.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
Labels: cla: yes, size/M

#430 Rebuild the buildtools container
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#422 Fix load tool for k8s 1.16
  perf/load/auto-mtls/templates/config-changer.yaml
  perf/load/templates/bad.yaml
  perf/load/templates/config-changer.yaml
Labels: cla: yes, ok-to-test, size/XS

#431 Add bashrc to build-tools container to enable tab completion for make
  docker/build-tools/Dockerfile
  docker/build-tools/bashrc
Labels: cla: yes, size/S

#434 Collate deprecated entries together at the end of tables.
  cmd/protoc-gen-docs/htmlGenerator.go
  go.mod
  go.sum
Labels: cla: yes, size/L

#435 Generated required as a new column in reference docs
  cmd/protoc-gen-docs/htmlGenerator.go
  go.mod
  go.sum
Labels: cla: yes, size/M

#437 A fix and a feature
  cmd/license-lint/README.md
  cmd/license-lint/main.go
  cmd/protoc-gen-docs/htmlGenerator.go
Labels: cla: yes, size/M

#432 Support dev releases
  perf/istio-install/setup_istio_release.sh
Labels: cla: yes, size/XS

#433 update benchmark script for dev release
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#438 update cue-gen tool to generate short descriptions for fields in CRD generation
  cmd/cue-gen/genoapi.go
  go.mod
  go.sum
Labels: cla: yes, size/M

#439 I'll get this right eventually...
  cmd/protoc-gen-docs/htmlGenerator.go
Labels: cla: yes, size/XS

#436 add missing parameters in enable mixer script
  perf/benchmark/README.md
Labels: cla: yes, ok-to-test, size/XS

#441 Make build-tools image work with `make e2e` in CNI
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#442 Release 1.4 codeowners, common-files, and master branch pointers
  CODEOWNERS
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  examples/luacheck/templates/meshPolicy.yaml
Labels: cla: yes, size/S

#445 abstract checkoutput to work with python2 and python3
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/S

#414 Add mixer mode configuration
  perf/benchmark/README.md
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/Pipfile
  perf/benchmark/runner/graph.py
  perf/benchmark/runner/runner.py
  perf/benchmark/update_mesh_config.py
Labels: cla: yes, size/L

#446 Update k8s code generators to 1.16.2
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#449 [benchmark script]add rollout check for fortio
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/setup_test.sh
Labels: cla: yes, size/XS

#448 Fix cannot generate flame graph due to not waiting for kubectl execution to finish
  perf/benchmark/README.md
  perf/benchmark/flame/README.md
  perf/benchmark/flame/example_flame_graph/example_flagmegraph.svg
  perf/benchmark/flame/example_flame_graph/example_output/15aa0cc9_qps_1000_c_1_1024_mixer_srv_bothsidecars_perf.svg
  perf/benchmark/runner/runner.py
  perf/istio-install/setup_prometheus.sh
Labels: cla: yes, size/XL

#451 add flame graph sample output url
  perf/benchmark/README.md
Labels: cla: yes, size/XS

#450 Update to golang 1.13.2
  docker/build-tools/Dockerfile
Labels: cherrypick/release-1.4, cla: yes, size/XS

#452 [release-1.4] Update to golang 1.13.2
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#453 Update to Golang 1.13.3
  docker/build-tools/Dockerfile
Labels: cherrypick/release-1.4, cla: yes, size/XS

#454 [release-1.4] Update to Golang 1.13.3
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#443 kubetype-gen: prevent import names from conflicting with generated pa…
  cmd/kubetype-gen/generators/types.go
Labels: cla: yes, size/XS

#456 Allow failures in gcr docker auth
  docker/build-tools/prow-entrypoint.sh
Labels: cherrypick/release-1.4, cla: yes, size/XS

#457 [release-1.4] Allow failures in gcr docker auth
  docker/build-tools/prow-entrypoint.sh
Labels: cla: yes, size/XS

#458 fix script path
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#444 Update promethues to match istio
  perf/prometheus-install/prometheus.yaml
Labels: cla: yes, size/XS

#461 Add support for the --mirror option.
  cmd/license-lint/README.md
  cmd/license-lint/main.go
Labels: cla: yes, size/M

#460 Mount user specific secrets in /config
  docker/build-tools/Dockerfile
  docker/build-tools/docker-entrypoint.sh
Labels: cla: yes, size/M

#462 add H2UPGRADE param for namespace in service graph
  perf/load/common.sh
  perf/load/templates/h2upgrade.yaml
  perf/load/values.yaml
Labels: cla: yes, size/M

#459 [release-1.4] cherry pick benchmark scripts updates
  perf/benchmark/README.md
  perf/benchmark/flame/README.md
  perf/benchmark/flame/example_flame_graph/example_flagmegraph.svg
  perf/benchmark/flame/example_flame_graph/example_output/15aa0cc9_qps_1000_c_1_1024_mixer_srv_bothsidecars_perf.svg
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/Pipfile
  perf/benchmark/runner/graph.py
  perf/benchmark/runner/runner.py
  perf/benchmark/setup_test.sh
  perf/benchmark/update_mesh_config.py
  perf/istio-install/setup_prometheus.sh
Labels: cla: yes, size/XL

#463 [release-1.4] Add support for the --mirror option.
  cmd/license-lint/README.md
  cmd/license-lint/main.go
Labels: cla: yes, size/M

#464 [release-1.4] Update k8s code generators to 1.16.2
  docker/build-tools/Dockerfile
Labels: cla: no, size/XS

#466 Add /home/.gsutil directory.
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#467 Add some debugging information
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/fortio.py
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/M

#465 Update golangci-lint to v1.21
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#469 Update dev release urls
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#440 support set sidecar.istio.io/interceptionMode for perf test
  perf/benchmark/README.md
  perf/benchmark/setup_test.sh
  perf/benchmark/templates/fortio.yaml
  perf/benchmark/values-istio-auth.yaml
  perf/benchmark/values.yaml
Labels: cla: yes, size/XS

#468 Tool fixes.
  cmd/license-lint/collector.go
  cmd/protoc-gen-docs/htmlGenerator.go
Labels: cherrypick/release-1.4, cla: yes, size/M

#470 [release-1.4] Tool fixes.
  cmd/license-lint/collector.go
  cmd/protoc-gen-docs/htmlGenerator.go
Labels: cla: yes, size/M

#473 improve stability of benchmark scripts
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/templates/fortio.yaml
Labels: cla: yes, size/S

#474 [Release 1.4] cherry pick perf update
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/fortio.py
  perf/benchmark/runner/runner.py
  perf/benchmark/templates/fortio.yaml
Labels: cla: yes, size/M

#475 Fix the --mirror option to correctly handle modules with multiple licenses
  cmd/license-lint/main.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#471 Clean up docker after job shutdown
  docker/build-tools/prow-entrypoint.sh
Labels: cla: yes, size/XS

#476 [release-1.4] Fix the --mirror option to correctly handle modules with multiple licenses
  cmd/license-lint/main.go
Labels: cla: yes, size/S

#480 Update the gen and gen-check targets to implement expected semantics.
  Makefile.core.mk
Labels: cla: yes, size/XS

#481 Fix cronjob deadlock
  perf/load/templates/config-changer.yaml
Labels: cla: yes, size/XS

#483 Add yq to build-tools container
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#487 Mention Istio API in the generated comment
  cmd/cue-gen/genoapi.go
Labels: cla: yes, size/XS

#488 Use updated url for v2 envoyfilter
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/S

#492 Create_cluster can add a service account and create regional cluster
  perf/istio-install/create_cluster.sh
  perf/istio-install/create_sa.sh
  perf/istio-install/setup_istio.sh
  perf/istio-install/values.yaml
Labels: cla: yes, size/M

#491 [release-1.4] Use correct url for envoyfilter (#488)
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/S

#486 Put the branch name on the image tag
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/S

#493 Add gen in the openapi file names
  cmd/cue-gen/build.go
Labels: cla: yes, size/XS

#495 fix tracing perms
  perf/istio-install/create_sa.sh
Labels: cla: yes, size/XS
