Repository istio/tools, pull requests merged in 2020-09, with the labels that each got.

#1188 Add AccessLogPolicy Config as a selective perf test run
  perf/benchmark/configs/istio/telemetryv2_sd_full_accesslogpolicy/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full_accesslogpolicy/installation.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full_accesslogpolicy/latency.yaml
  perf/benchmark/configs/run_perf_test.conf
Labels: cla: yes, size/M

#1191 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#1192 Pin GN version
  docker/build-tools/Dockerfile.centos
Labels: cla: yes, size/XS

#1193 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1195 Add jq to build-tools-proxy
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1185 Update bucket resolution to make it suitable for the actual perf number
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#1196 Add the user in docker-entrypoint.sh
  docker/build-tools/docker-entrypoint.sh
Labels: cla: yes, size/XS

#1197 Remove policy and telemetry fields in overlay
  perf/istio-install/istioctl_profiles/default-overlay.yaml
Labels: cla: yes, size/S

#1198 Clarify action requirement
  cmd/gen-release-notes/note.go
Labels: cla: yes, size/XS

#1200 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1199 Add p99.9 in benchmark data fetching script and dashboard
  perf/benchmark/README.md
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/fortio.py
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/static/js/latency_common_func.js
Labels: cla: yes, size/L

#1201 Remove telemetry field in v1alpha1.IstioComponentSetSpec
  perf/benchmark/configs/istio/none/installation.yaml
  perf/benchmark/configs/istio/plaintext/installation.yaml
Labels: cla: yes, size/S

#1202 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1190 Add enabling jitter check and suppress scientific notation
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#1189 Add notes for how to test system Maximum QPS and update README to the latest
  perf/benchmark/README.md
  perf/benchmark/runner/runner.py
  perf_dashboard/benchmarks/templates/benchmarks_overview.html
Labels: cla: yes, size/S

#1203 Update README.md
  cmd/gen-release-notes/README.md
Labels: cla: yes, size/S

#1204 Bump golang version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1207 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#1206 Add performance trending
  perf_dashboard/README.md
  perf_dashboard/analyze_perf_issues/templates/analyze_perf_issues.html
  perf_dashboard/artifacts/templates/artifact.html
  perf_dashboard/benchmarks/templates/benchmarks_overview.html
  perf_dashboard/benchmarks/templates/cpu_vs_conn.html
  perf_dashboard/benchmarks/templates/cpu_vs_qps.html
  perf_dashboard/benchmarks/templates/flame_graph.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/templates/mem_vs_conn.html
  perf_dashboard/benchmarks/templates/mem_vs_qps.html
  perf_dashboard/benchmarks/templates/micro_benchmarks.html
  perf_dashboard/history/templates/history.html
  perf_dashboard/perf_dashboard/urls.py
  perf_dashboard/regression_pattern/views.py
  perf_dashboard/regressions/__init__.py
  perf_dashboard/regressions/admin.py
  perf_dashboard/regressions/apps.py
  perf_dashboard/regressions/migrations/__init__.py
  perf_dashboard/regressions/models.py
  perf_dashboard/regressions/templates/cur_regression.html
  perf_dashboard/regressions/templates/master_regression.html
  perf_dashboard/regressions/templates/monitoring_overview.html
  perf_dashboard/regressions/tests.py
  perf_dashboard/regressions/urls.py
  perf_dashboard/regressions/views.py
  perf_dashboard/static/js/cur_pattern.js
  perf_dashboard/static/js/cur_regression.js
  perf_dashboard/static/js/master_pattern.js
  perf_dashboard/static/js/master_regression.js
  perf_dashboard/static/js/pattern_common_func.js
  perf_dashboard/static/js/regression_common_func.js
  perf_dashboard/templates/index.html
Labels: cla: yes, size/XL

#1208 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1209 Make testing qps range within the system's maximum qps
  perf/benchmark/configs/istio/none/cpu_mem.yaml
  perf/benchmark/configs/istio/plaintext/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full_accesslogpolicy/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_statswasm/cpu_mem.yaml
  perf_dashboard/benchmarks/views.py
  perf_dashboard/static/js/cpu_qps.js
  perf_dashboard/static/js/latency_qps.js
  perf_dashboard/static/js/mem_qps.js
Labels: cla: yes, size/M

#1210 Upgrade to kind v0.9.0
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1212 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/M

#1213 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#1214 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1215 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1217 [release-1.7] Remove deprecated grafana and tracing fields
  perf/istio-install/istioctl_profiles/default-overlay.yaml
Labels: cla: yes, size/S

#1218 Add locales and make sure to upgrade packages
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#1219 Properly set -y for dist upgrade
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1220 Fix dashboard app delopyment and add invalid qps check
  perf/benchmark/runner/runner.py
  perf_dashboard/perf_dashboard/settings.py
Labels: cla: yes, size/XS

#1216 Refine license linter import scope
  cmd/license-lint/collector.go
Labels: cla: yes, size/M

#1223 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1224 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1226 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.yamllint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/S
