Repository istio/tools, pull requests merged in 2020-04, with the labels that each got.

#852 add stackdriver configs for release-1.5
  perf/benchmark/configs/istio/telemetryv2_sd_full/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/installation.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/installation.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/installation.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/latency.yaml
Labels: cla: yes, size/L

#854 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#853 add linkinator to build-tools dockerfile
  docker/build-tools/Dockerfile
Labels: cla: yes, ok-to-test, size/XS

#857 Remove perf dashboard qual host from ALLOWED_HOSTS
  perf_dashboard/perf_dashboard/settings.py
Labels: cla: yes, size/XS

#856 dump envoy config_dump and clusters info to perf GCS bucket
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/S

#859 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#860 [release-1.5] dump envoy config_dump and clusters info to perf GCS bucket
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/S

#861 Fix unfound istio linux release tar.gz issue
  isotope/runner/istio.py
  perf/istio-install/setup_istio.sh
  perf/istio-install/setup_istio_release.sh
  upgrade/run_upgrade_test.sh
Labels: cla: yes, size/S

#855 Transition to gobin
  docker/build-tools/Dockerfile
Labels: cla: yes, size/M

#863 fix plaintext config
  perf/benchmark/configs/istio/plaintext/installation.yaml
Labels: cherrypick/release-1.5, cla: yes, size/XS

#858 add benchmark configs & measurements section and fix history page reference issue
  perf/benchmark/README.md
  perf_dashboard/artifacts/templates/artifact.html
  perf_dashboard/benchmarks/templates/benchmarks_overview.html
  perf_dashboard/benchmarks/templates/cpu_memory.html
  perf_dashboard/benchmarks/templates/flame_graph.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/templates/micro_benchmarks.html
  perf_dashboard/benchmarks/urls.py
  perf_dashboard/benchmarks/views.py
  perf_dashboard/graph_plotting/templates/graph_plotting.html
  perf_dashboard/history/templates/history.html
  perf_dashboard/regression_pattern/templates/cur_pattern.html
  perf_dashboard/regression_pattern/templates/master_pattern.html
  perf_dashboard/static/js/pattern_common_func.js
  perf_dashboard/templates/index.html
Labels: cla: yes, size/L

#865 [release-1.5] fix plaintext config
  perf/benchmark/configs/istio/plaintext/installation.yaml
Labels: cla: yes, size/XS

#866 add telemetry mode to config_dump name and fix upgrade job linux tar issue
  perf/benchmark/run_benchmark_job.sh
  upgrade/run_upgrade_test.sh
Labels: cla: yes, size/M

#868 Bump counterfeiter version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#869 Add jsonnet and jb to build-tools
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#851 Fix connection leak in isotope
  go.mod
  go.sum
  isotope/convert/pkg/graph/script/request_command.go
  isotope/go.mod
  isotope/go.sum
  isotope/service/Dockerfile
  isotope/service/main.go
  isotope/service/pkg/srv/executable.go
  isotope/service/pkg/srv/graph.go
  isotope/service/pkg/srv/handler.go
  isotope/service/pkg/srv/request.go
  licenses/fortio.org/fortio/LICENSE
  licenses/github.com/hashicorp/errwrap/LICENSE
  licenses/github.com/hashicorp/go-multierror/LICENSE
  perf/load/values.yaml
Labels: cla: yes, size/XXL

#870 Fix license lint on golang 1.14
  cmd/license-lint/collector.go
Labels: cla: yes, size/XS

#873 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#874 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#875 [release-1.5] collect envoy config_dump and clusterinfo
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/S

#876 change the rendering date to trace back to 60 days for regression deugging purpose
  perf_dashboard/artifacts/views.py
  perf_dashboard/benchmarks/views.py
Labels: cla: yes, size/XS

#871 Update golangci-lint to 1.24.0
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#877 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#842 remove mixer mode from perf test run and dashboard
  perf/benchmark/configs/README.md
  perf/benchmark/configs/istio/run_perf_test.conf
  perf/benchmark/run_benchmark_job.sh
  perf_dashboard/benchmarks/views.py
  perf_dashboard/regression_pattern/views.py
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/static/js/cur_pattern.js
  perf_dashboard/static/js/latency_common_func.js
  perf_dashboard/static/js/master_pattern.js
Labels: cherrypick/release-1.5, cla: yes, size/L

#872 Update golang to 1.14.1
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#878 remove mixer mode from perf test run and dashboard (#842)
  perf/benchmark/configs/README.md
  perf/benchmark/configs/istio/run_perf_test.conf
  perf/benchmark/run_benchmark_job.sh
  perf_dashboard/benchmarks/views.py
  perf_dashboard/regression_pattern/views.py
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/static/js/cur_pattern.js
  perf_dashboard/static/js/latency_common_func.js
  perf_dashboard/static/js/master_pattern.js
Labels: cla: yes, size/L

#880 Fix istio upgrade jobs
  upgrade/run_upgrade_test.sh
Labels: cla: yes, size/M

#879 make load generator configurable for perf test
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/L

#882 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#864 add trialrun to run as presubmit
  perf/benchmark/configs/trialrun.yaml
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, needs-rebase, size/S

#883 add load_gen_type flag into perf runner
  perf/benchmark/configs/istio/mixer/cpu_mem.yaml
  perf/benchmark/configs/istio/mixer/latency.yaml
  perf/benchmark/configs/istio/none/cpu_mem.yaml
  perf/benchmark/configs/istio/none/latency.yaml
  perf/benchmark/configs/istio/plaintext/cpu_mem.yaml
  perf/benchmark/configs/istio/plaintext/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/latency.yaml
  perf/benchmark/configs/run_perf_test.conf
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/M

#881 make trace back days configurable on perf site
  perf_dashboard/benchmarks/templates/cpu_memory.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/views.py
Labels: cla: yes, size/L

#884 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#885 Use full GIT_SHA to make it consumable by perf site
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#887 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#886 change perf benchmark data output dir name to use the full TAG
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#888 [release-1.5] cherry-pick recent master perf pipeline changes
  perf/benchmark/configs/run_perf_test.conf
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/S

#889 fix file not found issue
  perf_dashboard/helpers/download.py
Labels: cla: yes, size/XS

#592 Exclude outbound ports to prevent bad gateway error
  perf/benchmark/templates/fortio.yaml
Labels: cla: yes, size/XS

#593 Correct graph script to print mixer values
  perf/benchmark/runner/graph.py
Labels: cla: yes, size/XS

#892 fix Asset charts not found when installing istio
  perf/istio-install/setup_istio.sh
Labels: cla: yes, size/XS

#894 Update K8S_CODE_GENERATOR_VERSION to 1.18.1
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#895 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#893 fix INSTALL_WITH_ISTIOCTL charts issue
  perf/benchmark/run_benchmark_job.sh
  perf/istio-install/setup_istio.sh
Labels: cla: yes, size/XS

#891 add Nighthawk generator cmd into perf runner
  perf/benchmark/runner/runner.py
  perf/istio-install/setup_istio.sh
Labels: cla: yes, size/L

#896 Remove perf trial run data from GCS bucket
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#692 perf/benchmark: Integrate Nighthawk
  perf/benchmark/README.md
  perf/benchmark/runner/fortio.py
  perf/benchmark/runner/graph.py
  perf/benchmark/runner/runner.py
  perf/benchmark/setup_test.sh
  perf/benchmark/templates/fortio.yaml
  perf/benchmark/values.yaml
Labels: cla: yes, do-not-merge/work-in-progress, ok-to-test, size/L

#846 add anthosctl into setup cluster
  perf/istio-install/create_cluster.sh
  perf/istio-install/gke_cluster_resources/Kptfile
  perf/istio-install/gke_cluster_resources/cluster.yaml
  perf/istio-install/gke_cluster_resources/nodepool.yaml
Labels: cla: yes, size/L

#902 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_no_modify.sh
  common/scripts/nomodify.md5
Labels: auto-merge, cla: yes, size/S

#904 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#903 Support https redirect in perf dashboard
  perf_dashboard/deploy/perf-dashboard/templates/deployment.yaml
  perf_dashboard/deploy/perf-dashboard/values.yaml
  perf_dashboard/perf_dashboard/settings.py
Labels: cla: yes, size/S

#905 build-tools: use latest stable version of yq
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#899 Mount points in the container are special.
  docker/build-tools/Dockerfile
  docker/build-tools/docker-entrypoint.sh
Labels: cla: yes, size/S

#900 Set KUBECONFIG every time within the container
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#906 Revert "Support https redirect in perf dashboard"
  perf_dashboard/deploy/perf-dashboard/templates/deployment.yaml
  perf_dashboard/deploy/perf-dashboard/values.yaml
  perf_dashboard/perf_dashboard/settings.py
Labels: cla: yes, size/S

#907 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#908 Support https redirect in perf dashboard
  perf_dashboard/deploy/perf-dashboard/templates/deployment.yaml
  perf_dashboard/deploy/perf-dashboard/values.yaml
  perf_dashboard/perf_dashboard/settings.py
  perf_dashboard/perf_dashboard/urls.py
  perf_dashboard/perf_dashboard/views.py
Labels: cla: yes, size/M

#909 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_no_modify.sh
  common/scripts/nomodify.md5
Labels: auto-merge, cla: yes, size/S

#912 Enable mTLS in the upgrade tests and document how to run the upgrade tests
  upgrade/README.md
  upgrade/test_crossgrade.sh
Labels: cla: yes, size/M

#914 Update release managers as CODEOWNERS for release 1.6
  CODEOWNERS
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#913 add new config for stats wasm
  perf/benchmark/configs/istio/plaintext/prerun.sh
  perf/benchmark/configs/istio/telemetryv2_statswasm/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_statswasm/installation.yaml
  perf/benchmark/configs/istio/telemetryv2_statswasm/latency.yaml
  perf/istio-install/istioctl_profiles/default.yaml
Labels: cla: yes, size/M

#901 Update security perf test
  perf/istio-install/values-istio-non-sds.yaml
  perf/security/file-mount-tests/non-sds-1/README.md
  perf/security/file-mount-tests/non-sds-1/cleanup.sh
  perf/security/file-mount-tests/non-sds-1/setup_test.sh
  perf/security/file-mount-tests/non-sds-2/Chart.yaml
  perf/security/file-mount-tests/non-sds-2/README.md
  perf/security/file-mount-tests/non-sds-2/cleanup.sh
  perf/security/file-mount-tests/non-sds-2/setup_test.sh
  perf/security/file-mount-tests/non-sds-2/values.yaml
  perf/security/sds-tests/citadel-1/README.md
  perf/security/sds-tests/citadel-1/cleanup.sh
  perf/security/sds-tests/citadel-1/setup_test.sh
  perf/security/sds-tests/citadel-2/README.md
  perf/security/sds-tests/citadel-2/cleanup.sh
  perf/security/sds-tests/citadel-2/setup_test.sh
  perf/security/sds-tests/citadel-2/templates/workloads-rotate.yaml
  perf/security/sds-tests/citadel-2/values.yaml
  perf/security/sds-tests/workload-sds/Chart.yaml
  perf/security/sds-tests/workload-sds/README.md
  perf/security/sds-tests/workload-sds/setup_test.sh
  perf/security/sds-tests/workload-sds/templates/workload_rotate.yaml
  perf/security/sds-tests/workload-sds/values.yaml
  perf/security/sds-tests/workload-sds/workload.yaml
Labels: cla: yes, size/XXL

#915 Setup mTLS by PeerAuth CR
  perf/load/templates/mtls.yaml
  perf/load/templates/strict.yaml
  perf/load/values.yaml
Labels: cla: yes, size/M

#917 Label handling fixes
  perf/benchmark/runner/runner.py
Labels: cla: yes, do-not-merge/work-in-progress, ok-to-test, size/M

#918 Nighthawk: run via kubectl
  perf/benchmark/runner/runner.py
Labels: cla: yes, ok-to-test, size/S

#916 Refactor istio-install setup
  perf/benchmark/run_benchmark_job.sh
  perf/istio-install/README.md
  perf/istio-install/base/templates/als.yaml
  perf/istio-install/base/templates/istio-gateway.yaml
  perf/istio-install/base/templates/prometheus-install.yaml
  perf/istio-install/base/templates/prometheus-operator.yaml
  perf/istio-install/base/values.yaml
  perf/istio-install/istio_operator.sha
  perf/istio-install/setup_istio.sh
  perf/istio-install/setup_istio_operator.sh
  perf/istio-install/setup_istio_release.sh
  perf/istio-install/setup_prometheus.sh
  perf/istio-install/values-istio-non-sds.yaml
  perf/istio-install/values-istio-postsubmit.yaml
  perf/istio-install/values-istio-sds-auth.yaml
  perf/istio-install/values-large.yaml
  perf/istio-install/values-multi-citadel-non-sds.yaml
  perf/istio-install/values-new-installer.yaml
  perf/istio-install/values.yaml
  perf/prometheus-install/.gitignore
  perf/prometheus-install/ssd-storage-class.yaml
Labels: cla: yes, size/XXL

#921 disable jitter in nighthawk run
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#922 Add centos build-tools image
  docker/build-tools/Dockerfile.centos
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/M

#925 Remove allconfig test
  perf/stability/allconfig/Chart.yaml
  perf/stability/allconfig/setup.sh
  perf/stability/allconfig/templates/app-a.yaml
  perf/stability/allconfig/templates/app-b-headless.yaml
  perf/stability/allconfig/templates/app-c-split.yaml
  perf/stability/allconfig/templates/app-d-explicit-mtls.yaml
  perf/stability/allconfig/templates/app-e-authexcluded-noistio.yaml
  perf/stability/allconfig/templates/app-t-noistio.yaml
  perf/stability/allconfig/templates/badhealth.yaml
  perf/stability/allconfig/templates/fortio-cli.yaml
  perf/stability/allconfig/templates/fortio-headless.yaml
  perf/stability/allconfig/templates/fortio-master.yaml
  perf/stability/allconfig/templates/fortio-noistio.yaml
  perf/stability/allconfig/templates/fortio-tls.yaml
  perf/stability/allconfig/templates/fortio-ttls-small.yaml
  perf/stability/allconfig/templates/fortio-ttls.yaml
  perf/stability/allconfig/templates/fortio.yaml
  perf/stability/allconfig/templates/gateway.yaml
  perf/stability/allconfig/templates/gateway2.yaml
  perf/stability/allconfig/templates/ingress.yaml
  perf/stability/allconfig/templates/iperf3-noistio.yaml
  perf/stability/allconfig/templates/iperf3-tls.yaml
  perf/stability/allconfig/templates/iperf3.yaml
  perf/stability/allconfig/templates/service-externalname-httpbin.yaml
  perf/stability/allconfig/templates/service-externalname-wikipedia.yaml
  perf/stability/allconfig/templates/virtual_service.yaml
  perf/stability/allconfig/values.yaml
Labels: cla: yes, size/XXL

#924 Stop using deprecated Policy
  perf/benchmark/configs/istio/plaintext/prerun.sh
  perf/benchmark/templates/mtls.yaml
Labels: cla: yes, size/S

#923 fix typo in centos
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/XS

#919 Amend handling of modes in runner.py
  perf/benchmark/runner/runner.py
Labels: cla: yes, ok-to-test, size/XS

#920 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#926 Properly shutdown benchmark job
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#928 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#927 add go template logic to handle both fortio and nighthawk test setup
  perf/benchmark/README.md
  perf/benchmark/setup_test.sh
  perf/benchmark/templates/fortio.yaml
  perf/benchmark/values.yaml
Labels: cla: yes, size/M

#929 Fix perf test labelling issues
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/S

#930 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS
