Repository istio/tools, pull requests merged in 2020-01, with the labels that each got.

#658 remove mixer_cache and unnecessary code in fortio.py
  perf/benchmark/runner/fortio.py
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/M

#657 cherrypick #656 to release-1.4
  cmd/kubetype-gen/generators/naming.go
  cmd/kubetype-gen/generators/register.go
Labels: cla: yes, size/M

#660 Update package versions in istio dev
  Makefile.core.mk
  docker/istio-dev/Dockerfile
  docker/istio-dev/README.md
Labels: cla: yes, size/M

#661 trigger tools build for 1.4
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#662 Cherrypick #609 to release 1.4
  docker/build-tools/Dockerfile
  perf/benchmark/README.md
Labels: cla: yes, size/M

#663 fixing mtls enabling issue in twopods test
  perf/benchmark/setup_test.sh
  perf/benchmark/templates/fortio.yaml
  perf/benchmark/templates/mtls.yaml
  perf/benchmark/values.yaml
Labels: cla: yes, size/M

#665 correct the plaintext mode setup and post clean up.
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/S

#664 Remove regression alert section from perf board
  perf_dashboard/regression_alerts/templates/cur_alert.html
  perf_dashboard/regression_alerts/templates/master_alert.html
  perf_dashboard/templates/base.html
Labels: cla: yes, size/L

#666 Rename staticfiles folder and Add essential docker related files for deploy perfboard to K8S
  perf_dashboard/docker-entrypoint.sh
  perf_dashboard/dockerfile
  perf_dashboard/perf_dashboard/settings.py
  perf_dashboard/static/css/fontastic.css
  perf_dashboard/static/css/jquery.mCustomScrollbar.css
  perf_dashboard/static/css/style.blue.css
  perf_dashboard/static/fonts/dashboard.eot
  perf_dashboard/static/fonts/dashboard.svg
  perf_dashboard/static/fonts/dashboard.ttf
  perf_dashboard/static/fonts/dashboard.woff
  perf_dashboard/static/img/flame.svg
  perf_dashboard/static/img/istio-logo.png
  perf_dashboard/static/js/alert_common_func.js
  perf_dashboard/static/js/configuration.js
  perf_dashboard/static/js/cpu-memory.js
  perf_dashboard/static/js/cur_alert.js
  perf_dashboard/static/js/front.js
  perf_dashboard/static/js/jquery.mCustomScrollbar.concat.min.js
  perf_dashboard/static/js/latency.js
  perf_dashboard/static/js/master_alert.js
  perf_dashboard/static/js/microbenchmarks.js
  perf_dashboard/static/js/overview.js
Labels: cla: yes, size/M

#667 set debug=true otherwise static file is not accessible
  perf_dashboard/README.md
  perf_dashboard/perf_dashboard/settings.py
Labels: cla: yes, size/XS

#668 Enable 3rd-party JWTs in KIND in istio-dev container README
  docker/istio-dev/README.md
Labels: cla: yes, size/S

#670 update nomixer label to none
  perf/benchmark/README.md
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/graph.py
  perf_dashboard/benchmarks/templates/cpu-memory.html
  perf_dashboard/benchmarks/templates/latency.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/configurations/templates/configurations.html
  perf_dashboard/regression_alerts/templates/cur_alert.html
  perf_dashboard/regression_alerts/templates/master_alert.html
  perf_dashboard/regression_alerts/views.py
  perf_dashboard/static/js/alert_common_func.js
  perf_dashboard/static/js/configuration.js
  perf_dashboard/static/js/cpu-memory.js
  perf_dashboard/static/js/cur_alert.js
  perf_dashboard/static/js/latency.js
  perf_dashboard/static/js/master_alert.js
Labels: cla: yes, size/L

#671 parse extra_label in benchmark config file
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#672 make istio builds in a reverse chronological order
  perf_dashboard/benchmarks/templates/latency.html
  perf_dashboard/helpers/download.py
Labels: cla: yes, size/S

#674 Update to golang 1.13.6
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#673 add latency vs. qps graphs
  perf_dashboard/artifacts/templates/artifact.html
  perf_dashboard/benchmarks/templates/cpu-memory.html
  perf_dashboard/benchmarks/templates/flame_graph.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/templates/micro_benchmarks.html
  perf_dashboard/benchmarks/urls.py
  perf_dashboard/benchmarks/views.py
  perf_dashboard/regression_alerts/templates/cur_alert.html
  perf_dashboard/regression_alerts/templates/master_alert.html
  perf_dashboard/static/js/latency_common_func.js
  perf_dashboard/static/js/latency_conn.js
  perf_dashboard/static/js/latency_qps.js
  perf_dashboard/templates/index.html
Labels: cla: yes, size/XXL

#675 Update kind to v0.7.0
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#676 Replacing defaultNamespace with meshConfig.rootNamespace
  perf/istio-install/setup_istio.sh
  perf/istio-install/setup_istio_operator.sh
Labels: cla: yes, size/XS

#679 Adding Mako dependencies to docker image used for load testing.
  docker/build-tools/Dockerfile
Labels: cla: yes, ok-to-test, size/S

#680 Move Python3.7 installation to base image as it is being used in multiple images.
  docker/build-tools/Dockerfile
Labels: cla: yes, ok-to-test, size/XS

#677 add recent updates to perf benchmark
  bin/setup_cluster.sh
  perf/benchmark/run_benchmark_job.sh
  perf/istio-install/istioctl_profiles/automtls.yaml
  perf/istio-install/istioctl_profiles/default.yaml
  perf/istio-install/istioctl_profiles/istio-non-sds.yaml
  perf/istio-install/istioctl_profiles/multi-citadel-non-sds.yaml
  perf/istio-install/istioctl_profiles/sds-auth.yaml
  perf/istio-install/setup_istio.sh
Labels: cla: yes, size/L

#684 make release name dynamically populate to frontend
  perf_dashboard/artifacts/templates/artifact.html
  perf_dashboard/artifacts/views.py
  perf_dashboard/benchmarks/templates/cpu_memory.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/regression_alerts/templates/cur_alert.html
  perf_dashboard/regression_alerts/views.py
  perf_dashboard/static/js/cpu_memory.js
Labels: cla: yes, size/M

#685 add none_plaintext_both mode line and refactor benchmark section
  perf_dashboard/benchmarks/templates/cpu_memory.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/static/js/alert_common_func.js
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/static/js/latency_common_func.js
  perf_dashboard/static/js/latency_conn.js
  perf_dashboard/static/js/latency_qps.js
  perf_dashboard/templates/base.html
Labels: cla: yes, size/XXL

#687 [release-1.4] Plaintext mode cherry pick
  perf/benchmark/README.md
  perf/benchmark/configs/plaintex_cpu_mem.yaml
  perf/benchmark/configs/plaintext_latency.yaml
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/graph.py
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/L

#688 Use istioctl to enable metadata_exchange and stats filter
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#682 fix perf test sidecar include/exclude outbound IP range issue
  perf/benchmark/README.md
  perf/benchmark/runner/runner.py
  perf/benchmark/setup_test.sh
  perf/benchmark/templates/fortio.yaml
  perf/benchmark/templates/mtls.yaml
  perf/benchmark/values.yaml
Labels: cla: yes, size/M

#689 [release-1.4] fix perf test sidecar include/exclude outbound IP range issue (#682)
  perf/benchmark/README.md
  perf/benchmark/runner/runner.py
  perf/benchmark/setup_test.sh
  perf/benchmark/templates/fortio.yaml
  perf/benchmark/templates/mtls.yaml
  perf/benchmark/values.yaml
Labels: cla: yes, size/M

#690 Add clientsidecar only configs
  perf/benchmark/README.md
  perf/benchmark/configs/istio/mixer_cpu_mem.yaml
  perf/benchmark/configs/istio/mixer_latency.yaml
  perf/benchmark/configs/istio/none_cpu_mem.yaml
  perf/benchmark/configs/istio/none_latency.yaml
  perf/benchmark/configs/istio/plaintex_cpu_mem.yaml
  perf/benchmark/configs/istio/plaintext_latency.yaml
  perf/benchmark/configs/istio/telemetryv2_cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_latency.yaml
  perf/benchmark/runner/runner.py
Labels: cherrypick/release-1.4, cla: yes, size/M

#691 [release-1.4] Add clientsidecar only configs
  perf/benchmark/README.md
  perf/benchmark/configs/mixer_cpu_mem.yaml
  perf/benchmark/configs/mixer_latency.yaml
  perf/benchmark/configs/nomixer_cpu_mem.yaml
  perf/benchmark/configs/nomixer_latency.yaml
  perf/benchmark/configs/plaintex_cpu_mem.yaml
  perf/benchmark/configs/plaintext_latency.yaml
  perf/benchmark/configs/telemetryv2_cpu_mem.yaml
  perf/benchmark/configs/telemetryv2_latency.yaml
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/M

#694 Trigger a container build.
  docker/build-tools/Dockerfile
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/XS

#696 fix release tar path of latest master build for upgrade job
  upgrade/run_upgrade_test.sh
Labels: cla: yes, size/XS

#693 Automator: update common-files@master in istio/tools@master
  LICENSE
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
Labels: cla: yes, size/M

#697 fix duplicate istio- in upgrade relase tag
  upgrade/run_upgrade_test.sh
Labels: cla: yes, size/XS

#699 Make proxy build tools xenial
  docker/build-tools/Dockerfile
Labels: cla: yes, size/L

#703 fix INSTALL_OPTIONS issue
  perf/benchmark/README.md
  upgrade/run_upgrade_test.sh
  upgrade/test_crossgrade.sh
Labels: cherrypick/release-1.4, cla: yes, size/S

#704 [release-1.5] Make proxy build tools xenial
  docker/build-tools/Dockerfile
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/L

#707 Update docker version for proxy build tools
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#708 [release-1.5] Update docker version for proxy build tools
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#709 Fix name of password file for copying credentials
  docker/build-tools/docker-entrypoint.sh
Labels: cherrypick/release-1.5, cla: yes, size/XS

#710 [release-1.5] Fix name of password file for copying credentials
  docker/build-tools/docker-entrypoint.sh
Labels: cla: yes, size/XS

#711 Bump golang
  docker/build-tools/Dockerfile
Labels: cherrypick/release-1.4, cherrypick/release-1.5, cla: yes, size/XS

#702 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#712 [release-1.5] Bump golang
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#698 Update golangci-lint to v1.23.1
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#714 remove default empty option to avoid hitting missing csv file
  perf_dashboard/benchmarks/templates/cpu_memory.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/configurations/templates/configurations.html
  perf_dashboard/templates/index.html
Labels: cla: yes, size/L

#715 fix istioctl install/upgrade version and command issue
  upgrade/test_crossgrade.sh
Labels: cla: yes, size/S

#713 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#718 add list file to debug upgrade 1.4.3 missing istioctl
  upgrade/test_crossgrade.sh
Labels: cla: yes, size/XS

#716 Remove nullable from generated CRD
  cmd/cue-gen/genoapi.go
Labels: cla: yes, size/XS

#720 Update fortio image to latest
  perf/benchmark/values.yaml
Labels: cla: yes, size/XS

#719 [release-1.5] Remove nullable from generated CRD
  cmd/cue-gen/genoapi.go
Labels: cla: yes, size/XS

#721 bump golang
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#722 Remove hugo shortcode replacement in doc gen
  cmd/protoc-gen-docs/htmlGenerator.go
Labels: cherrypick/release-1.5, cla: yes, size/XS

#723 [release-1.5] Remove hugo shortcode replacement in doc gen
  cmd/protoc-gen-docs/htmlGenerator.go
Labels: cla: yes, size/XS

#724 add placeholder csv files in case there is no csv files to parse
  perf_dashboard/benchmarks/views.py
  perf_dashboard/helpers/download.py
  perf_dashboard/perf_data/cur_temp.csv
  perf_dashboard/perf_data/master_temp.csv
  upgrade/test_crossgrade.sh
Labels: cla: yes, size/L

#725 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
  common/scripts/lint_go.sh
Labels: cla: yes, size/XS

#726 add some debugging info for fixing upgrade job issue
  upgrade/run_upgrade_test.sh
Labels: cla: yes, size/XS

#717 Simplify proxy profiling steps
  .gitignore
  perf/benchmark/flame/README.md
  perf/benchmark/flame/get_proxy_perf.sh
  perf/benchmark/flame/palette.map
Labels: cla: yes, size/L

#727 fixing upgrade job: should check "tag" not only TARGET_TAG
  upgrade/run_upgrade_test.sh
Labels: cla: yes, size/XS
