Repository istio/tools, pull requests merged in 2020-06, with the labels that each got.

#997 [release-1.6] Fix istio-proxy flame graph generation script
  perf/benchmark/flame/get_perfdata.sh
  perf/benchmark/flame/get_proxy_perf.sh
Labels: cla: yes, size/M

#998 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#999 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/XS

#1000 Remove deprecated SDS field in default overlay yaml
  perf/istio-install/istioctl_profiles/default-overlay.yaml
Labels: cherrypick/release-1.6, cla: yes, size/XS

#1001 [release-1.6] Remove deprecated SDS field in default overlay yaml
  perf/istio-install/istioctl_profiles/default-overlay.yaml
Labels: cla: yes, size/XS

#1002 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#1003 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#951 Fix GCS URL
  perf/istio-install/setup_istio.sh
Labels: cla: yes, size/XS

#1004 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: auto-merge, cla: yes, size/XS

#995 Use the brightbox PPA for ruby 2.6.5
  docker/build-tools/Dockerfile
Labels: cla: yes, size/M

#1005 Restore istio-dev image and update README
  Makefile.core.mk
  docker/istio-dev/.gitignore
  docker/istio-dev/Dockerfile
  docker/istio-dev/README.md
  docker/istio-dev/istio-dev.mk
Labels: cla: yes, size/L

#1007 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/M

#1008 Add sampling frequency flag for flame graph
  perf/benchmark/README.md
  perf/benchmark/runner/runner.py
Labels: cherrypick/release-1.6, cla: yes, size/S

#1009 [release-1.6] Add sampling frequency flag for flame graph
  perf/benchmark/README.md
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/S

#992 Fix --perf flag for generating istio-proxy CPU flame graph
  perf/benchmark/flame/README.md
  perf/benchmark/flame/flame.sh
  perf/benchmark/flame/get_proxy_perf.sh
  perf/benchmark/runner/runner.py
  perf/benchmark/values.yaml
  upgrade/run_upgrade_test.sh
  upgrade/test_crossgrade.sh
Labels: cherrypick/release-1.6, cla: yes, size/M

#1011 Make load test and flame graph (when --perf enabled) running in parallel
  perf/benchmark/runner/runner.py
Labels: cherrypick/release-1.6, cla: yes, size/M

#1010 [release-1.6] Fix --perf flag for generating istio-proxy CPU flame graph
  perf/benchmark/flame/README.md
  perf/benchmark/flame/flame.sh
  perf/benchmark/flame/get_proxy_perf.sh
  perf/benchmark/runner/runner.py
  perf/benchmark/values.yaml
  upgrade/run_upgrade_test.sh
  upgrade/test_crossgrade.sh
Labels: cla: yes, size/M

#1013 Fix flame graph README
  perf/benchmark/flame/README.md
Labels: cla: yes, size/XS

#1014 [release-1.6] Make load test and flame graph (when --perf enabled) running in parallel
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/M

#1015 Revert "make trace back days configurable on perf site"
  perf_dashboard/benchmarks/templates/cpu_memory.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/views.py
Labels: cla: yes, size/L

#1017 Trigger --perf for baseline mode
  perf/benchmark/runner/runner.py
Labels: cherrypick/release-1.6, cla: yes, size/S

#1018 Add flame graph --perf run into perf pipeline
  perf/benchmark/configs/istio/none/cpu_mem.yaml
  perf/benchmark/configs/istio/none/latency.yaml
  perf/benchmark/configs/istio/plaintext/cpu_mem.yaml
  perf/benchmark/configs/istio/plaintext/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_statswasm/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_statswasm/latency.yaml
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/runner.py
Labels: cherrypick/release-1.6, cla: yes, size/M

#1020 [release-1.6] Add flame graph --perf run into perf pipeline
  perf/benchmark/configs/istio/none/cpu_mem.yaml
  perf/benchmark/configs/istio/none/latency.yaml
  perf/benchmark/configs/istio/plaintext/cpu_mem.yaml
  perf/benchmark/configs/istio/plaintext/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_statswasm/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_statswasm/latency.yaml
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/M

#1022 Remove enable_perf record
  perf/benchmark/configs/trialrun.yaml
  perf/benchmark/run_benchmark_job.sh
Labels: cherrypick/release-1.6, cla: yes, size/S

#1023 [release-1.6] Remove enable_perf record
  perf/benchmark/configs/trialrun.yaml
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/S

#1019 [release-1.6] Trigger --perf for baseline mode
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/S

#1024 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/copyright-banner-go.txt
  common/scripts/fix_copyright_banner.sh
Labels: auto-merge, cla: yes, size/M

#1026 Fix GCS bucket copy path for flamegraphs
  perf/benchmark/run_benchmark_job.sh
Labels: cherrypick/release-1.6, cla: yes, size/XS

#1025 Allow cue-gen to generate validation schema for status
  cmd/cue-gen/Makefile
  cmd/cue-gen/build.go
  cmd/cue-gen/crd.go
  cmd/cue-gen/genoapi.go
  cmd/cue-gen/test/Makefile
  cmd/cue-gen/test/crdgen_test.go
  cmd/cue-gen/test/generated/kubernetes/customresourcedefinitions.gen.yaml
  cmd/cue-gen/test/istio.io/api/cue.mod
  cmd/cue-gen/test/istio.io/api/cue.yaml
  cmd/cue-gen/test/istio.io/api/foo/v1alpha3/bar.proto
  cmd/cue-gen/test/istio.io/api/foo/v1beta1/bar.proto
  cmd/cue-gen/test/istio.io/api/meta/v1beta1/status.proto
  go.mod
  go.sum
Labels: cla: yes, size/L

#1029 Bump kind version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1021 Collect istio-proxy CPU and memory usage for perf test
  perf/benchmark/README.md
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/fortio.py
  perf/benchmark/runner/prom.py
Labels: cla: yes, size/L

#1027 [release-1.6] Fix GCS bucket copy path for flamegraphs
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#1028 add script to generate flamegraph for pilot/istiod
  perf/benchmark/flame/README.md
  perf/benchmark/flame/flame.sh
  perf/benchmark/flame/get_istiod_pprof.sh
Labels: cla: yes, size/L

#1030 [release-1.6] Collect istio-proxy CPU and memory usage for perf test
  perf/benchmark/README.md
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/fortio.py
  perf/benchmark/runner/prom.py
Labels: cla: yes, size/L

#1031 Add peribolos
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1032 Update Perf test README to the latest
  perf/benchmark/README.md
  perf/benchmark/graphoutput/istio_p90.png
  perf/benchmark/screenshots/bokeh-screenshot.png
Labels: cla: yes, size/L

#1034 Rename arg mode to be protocol_mode and fix perf pipeline issue
  perf/benchmark/README.md
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/fortio.py
  perf/benchmark/runner/prom.py
  perf/benchmark/runner/runner.py
Labels: cherrypick/release-1.6, cla: yes, size/M

#1036 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1035 [release-1.6] Rename arg mode to be protocol_mode and fix perf pipeline issue
  perf/benchmark/README.md
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/fortio.py
  perf/benchmark/runner/prom.py
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/M

#1037 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#1038 Update golangci-lint
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1039 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1033 Remove counterfeiter
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1016 Disable DEBUG for dashboard
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/latency.yaml
  perf/benchmark/runner/runner.py
  perf_dashboard/perf_dashboard/settings.py
Labels: cla: yes, size/XS

#1040 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/fix_copyright_banner.sh
Labels: auto-merge, cla: yes, size/XS

#1043 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, size/XS

#1047 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1045 Deprecate Mixer in perf pipeline and dashboard
  perf/benchmark/configs/istio/mixer/cpu_mem.yaml
  perf/benchmark/configs/istio/mixer/installation.yaml
  perf/benchmark/configs/istio/mixer/latency.yaml
  perf_dashboard/benchmarks/templates/benchmarks_overview.html
  perf_dashboard/benchmarks/templates/cpu_memory.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/regression_pattern/views.py
  perf_dashboard/static/js/configuration.js
  perf_dashboard/static/js/pattern_common_func.js
Labels: cla: yes, size/L
