Repository istio/tools, pull requests merged in 2020-02, with the labels that each got.

#678 Add graph plotting page for rendering user uploaded testing data
  perf_dashboard/artifacts/templates/artifact.html
  perf_dashboard/benchmarks/templates/cpu_memory.html
  perf_dashboard/benchmarks/templates/flame_graph.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/templates/micro_benchmarks.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/graph_plotting/__init__.py
  perf_dashboard/graph_plotting/admin.py
  perf_dashboard/graph_plotting/apps.py
  perf_dashboard/graph_plotting/migrations/__init__.py
  perf_dashboard/graph_plotting/models.py
  perf_dashboard/graph_plotting/templates/graph_plotting.html
  perf_dashboard/graph_plotting/tests.py
  perf_dashboard/graph_plotting/urls.py
  perf_dashboard/graph_plotting/views.py
  perf_dashboard/perf_dashboard/settings.py
  perf_dashboard/perf_dashboard/urls.py
  perf_dashboard/regression_alerts/templates/cur_alert.html
  perf_dashboard/regression_alerts/templates/master_alert.html
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/templates/index.html
Labels: cla: yes, size/XXL

#729 fix upgrade istioctl version compare issue
  upgrade/test_crossgrade.sh
Labels: cla: yes, size/XS

#728 unselect serveronly mode by default
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/static/js/latency_common_func.js
Labels: cla: yes, size/S

#730 disable perf flame graph record for debugging pipeline issue
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#732 Label build-tools images
  docker/build-tools/Dockerfile
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/S

#733 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#734 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#735 update set overlay for telemetryv2
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/S

#736 add configdump and remove envoyfilter after running v2
  perf/benchmark/configs/istio/plaintext_cpu_mem.yaml
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/S

#740 perf_dashboard: bump cur_release to 1.5
  perf_dashboard/docker-compose.yml
  perf_dashboard/dockerfile
Labels: cla: yes, size/XS

#739 small clean up of benchmark script
  perf/benchmark/run_benchmark_job.sh
  perf/istio-install/setup_istio.sh
Labels: cla: yes, size/M

#742 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#743 keep the initial installation for crd
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#744 use graph plotting page to visualize csv instead of graph.py
  perf/benchmark/README.md
Labels: cla: yes, size/S

#741 Bump golang
  docker/build-tools/Dockerfile
Labels: cherrypick/release-1.4, cherrypick/release-1.5, cla: yes, size/XS

#746 [release-1.5] Bump golang
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#745 [release-1.4] Bump golang
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#747 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#748 R1.5 benchmark
  perf/benchmark/configs/istio/plaintext_cpu_mem.yaml
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/runner.py
  perf/benchmark/values.yaml
  perf/istio-install/setup_istio.sh
Labels: cla: yes, size/M

#749 update upgrade job bash to handle latest release sha
  upgrade/run_upgrade_test.sh
Labels: cla: yes, size/S

#750 update logic after helm charts removed from release
  perf/istio-install/setup_istio.sh
Labels: cla: yes, size/S

#751 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#752 [release-1.5] use graph plotting page to visualize csv instead of graph.py
  perf/benchmark/README.md
Labels: cla: yes, size/S

#753 update perf testing iop configs
  perf/istio-install/istioctl_profiles/default.yaml
Labels: cla: yes, size/XS

#738 Initial attempt to refactor the benchmark job structure
  perf/benchmark/README.md
  perf/benchmark/configs/istio/mixer/cpu_mem.yaml
  perf/benchmark/configs/istio/mixer/installation.yaml
  perf/benchmark/configs/istio/mixer/latency.yaml
  perf/benchmark/configs/istio/none/cpu_mem.yaml
  perf/benchmark/configs/istio/none/installation.yaml
  perf/benchmark/configs/istio/none/latency.yaml
  perf/benchmark/configs/istio/plaintext/cpu_mem.yaml
  perf/benchmark/configs/istio/plaintext/installation.yaml
  perf/benchmark/configs/istio/plaintext/latency.yaml
  perf/benchmark/configs/istio/plaintext/postrun.sh
  perf/benchmark/configs/istio/plaintext/prerun.sh
  perf/benchmark/configs/istio/telemetryv2/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2/installation.yaml
  perf/benchmark/configs/istio/telemetryv2/latency.yaml
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/L

#759 add mixer label explicitly for both and serveronly modes
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/static/js/latency_common_func.js
Labels: cla: yes, size/S

#758 add clientonly mode perf lines and set default as disabled
  perf_dashboard/benchmarks/templates/cpu_memory.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/static/js/latency_common_func.js
Labels: cla: yes, size/L

#761 Update Golang to 1.14.0
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#762 update fortio image (resolving broken json filename issue)
  perf/benchmark/setup_test.sh
Labels: cherrypick/release-1.5, cla: yes, size/XS

#763 [release-1.5] update fortio image (resolving broken json filename issue)
  perf/benchmark/setup_test.sh
Labels: cla: yes, size/XS

#764 use fortio image from istio-testing container registry
  perf/benchmark/setup_test.sh
Labels: cherrypick/release-1.5, cla: yes, size/XS

#765 [release-1.5] use fortio image from istio-testing container registry + update to be v1.3.1-1
  perf/benchmark/setup_test.sh
Labels: cla: yes, size/XS

#766 update fortio image version to be v1.3.1-1
  perf/benchmark/setup_test.sh
Labels: cla: yes, size/XS

#767 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#768 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#769 add replica field for fortio deployment
  perf/benchmark/setup_test.sh
  perf/benchmark/templates/fortio.yaml
  perf/benchmark/values.yaml
Labels: cherrypick/release-1.5, cla: yes, size/S

#770 [release-1.5] add replica field for fortio deployment
  perf/benchmark/setup_test.sh
  perf/benchmark/templates/fortio.yaml
  perf/benchmark/values.yaml
Labels: cla: yes, size/S

#756 [release-1.5] Refactor benchmark
  perf/benchmark/README.md
  perf/benchmark/configs/istio/mixer/cpu_mem.yaml
  perf/benchmark/configs/istio/mixer/installation.yaml
  perf/benchmark/configs/istio/mixer/latency.yaml
  perf/benchmark/configs/istio/none/cpu_mem.yaml
  perf/benchmark/configs/istio/none/installation.yaml
  perf/benchmark/configs/istio/none/latency.yaml
  perf/benchmark/configs/istio/plaintext/cpu_mem.yaml
  perf/benchmark/configs/istio/plaintext/installation.yaml
  perf/benchmark/configs/istio/plaintext/latency.yaml
  perf/benchmark/configs/istio/plaintext/postrun.sh
  perf/benchmark/configs/istio/plaintext/prerun.sh
  perf/benchmark/configs/istio/telemetryv2/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2/installation.yaml
  perf/benchmark/configs/istio/telemetryv2/latency.yaml
  perf/benchmark/run_benchmark_job.sh
  perf/istio-install/istioctl_profiles/default.yaml
Labels: cla: yes, size/L

#771 fix memory resource and set typo
  perf/benchmark/setup_test.sh
  perf/benchmark/values.yaml
Labels: cla: yes, size/XS

#772 [release-1.5] fix memory resource and set typo
  perf/benchmark/setup_test.sh
  perf/benchmark/values.yaml
Labels: cla: yes, size/XS
