Repository istio/tools, pull requests merged in 2020-11, with the labels that each got.

#1289 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1290 Automator: update common-files@release-1.8 in istio/tools@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1291 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1292 Remove helm2 and fix helm issue
  docker/build-tools/Dockerfile
  perf/benchmark/run_benchmark_job.sh
  upgrade_downgrade/test_upgrade_downgrade.sh
Labels: cla: yes, size/XS

#1294 Fix race in grafana install
  perf/istio-install/setup_istio.sh
Labels: cla: yes, size/XS

#1295 [release-1.7] Remove helm2 and fix helm issue
  docker/build-tools/Dockerfile
  perf/benchmark/run_benchmark_job.sh
  upgrade/test_crossgrade.sh
Labels: cla: yes, release-notes-none, size/XS

#1296 Install a few Go tools for test infra in the build-tools image
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1288 fix discovery address verification and some refactoring
  upgrade_downgrade/common.sh
  upgrade_downgrade/run_upgrade_downgrade_test.sh
  upgrade_downgrade/test_dual_control_plane_upgrade_downgrade.sh
  upgrade_downgrade/test_upgrade_downgrade.sh
Labels: cla: yes, ok-to-test, size/M

#1300 install a few test infra tools for release-1.8 branch
  docker/build-tools/Dockerfile
  perf/stability/sds-certmanager/crds/certmanager.yaml
  perf/stability/sds-certmanager/templates/certmanager.yaml
Labels: cla: yes, size/L

#1301 Bump certmanager CRD version and fix ordering
  perf/istio-install/base/templates/cert-manager.yaml
  perf/istio-install/setup_istio.sh
Labels: cla: yes, size/XS

#1302 [release-1.8] Remove helm2 and fix helm issue
  docker/build-tools/Dockerfile
  perf/benchmark/run_benchmark_job.sh
  upgrade_downgrade/test_upgrade_downgrade.sh
Labels: cla: yes, release-notes-none, size/XS

#1299 Install a few test infra tools for release-1.6
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1304 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1298 [release-1.7] Install a few Go tools for test infra in the build-tools image
  docker/build-tools/Dockerfile
Labels: cla: yes, release-notes-none, size/XS

#1305 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#1267 add new monitors for release qual test
  perf/stability/README.md
  perf/stability/alertmanager/prometheusrule.yaml
  perf/stability/alertmanager/templates/kube_state_metrics.yaml
  perf/stability/alertmanager/webhook.go
  perf/stability/canary-upgrader/canary_upgrade.sh
  perf/stability/canary-upgrader/templates/canary-upgrader-cron.yaml
  perf/stability/canary-upgrader/values.yaml
  perf/stability/long_running.sh
Labels: cla: yes, size/M

#1306 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#1307 Install the latest gcloud tool and its beta components in the build-tools image
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1308 Fix spell issue
  Makefile
  docker/build-tools/Dockerfile
  isotope/README.md
  isotope/helm-values.yaml
  isotope/runner/kubectl.py
  perf/benchmark/configs/istio/plaintext/latency.yaml
  perf/benchmark/security/generate_policies/README.md
  perf/istio-install/create_cluster.sh
  perf/load/loadclient/values.yaml
  perf/load/pilot/README.md
  perf/load/values-istio-auth.yaml
  perf/other/multicluster-vpc/setup.sh
  perf_dashboard/static/css/style.blue.css
  setup/ipv6/calico.yaml
Labels: cla: yes, size/M

#1309 Remove one command for the build tools image that was mistakenly submitted
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1310 [Cherrypick]Install the latest gcloud tool and its beta components in the build-tools image
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1312 [Cherrypick]Install the latest gcloud tool and its beta components in the build-tools image
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1259 Update dashboard overview page with benchmarks and test configs
  perf_dashboard/analyze_perf_issues/templates/analyze_perf_issues.html
  perf_dashboard/artifacts/templates/artifact.html
  perf_dashboard/benchmarks/templates/benchmarks_overview.html
  perf_dashboard/benchmarks/templates/cpu_vs_conn.html
  perf_dashboard/benchmarks/templates/cpu_vs_qps.html
  perf_dashboard/benchmarks/templates/flame_graph.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/templates/mem_vs_conn.html
  perf_dashboard/benchmarks/templates/mem_vs_qps.html
  perf_dashboard/benchmarks/templates/micro_benchmarks.html
  perf_dashboard/benchmarks/urls.py
  perf_dashboard/benchmarks/views.py
  perf_dashboard/history/templates/history.html
  perf_dashboard/regressions/templates/cur_regression.html
  perf_dashboard/regressions/templates/master_regression.html
  perf_dashboard/regressions/templates/monitoring_overview.html
  perf_dashboard/templates/index.html
Labels: cla: yes, size/L

#1313 Switch perf dashboard deploy to use helm3
  perf_dashboard/Makefile
Labels: cla: yes, size/XS

#1264 Update example benchmark CSV
  perf/benchmark/graph_plotter/example_plot/benchmark.csv
  perf/benchmark/graph_plotter/example_plot/plotter_output.png
Labels: cla: yes, size/L

#1314 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#1317 prometheus: add more customization to deployment
  perf/istio-install/base/templates/prometheus-install.yaml
  perf/istio-install/base/values.yaml
Labels: cla: yes, ok-to-test, size/S

#1318 Remove helm dependency from dual control plane upgrade downgrade tests
  upgrade_downgrade/test_dual_control_plane_upgrade_downgrade.sh
Labels: cla: yes, size/XS

#1319 Reduce 503 error threshold on dual control plane upgrade downgrade tests
  upgrade_downgrade/test_dual_control_plane_upgrade_downgrade.sh
Labels: cla: yes, size/XS

#1320 Add option to run upgrade_downgrade tests in kind
  upgrade_downgrade/kind.sh
  upgrade_downgrade/run_upgrade_downgrade_test.sh
Labels: cla: yes, size/M

#1321 Update Golang to pick up CVE
  docker/build-tools/Dockerfile
Labels: cherrypick/release-1.8, cla: yes, size/XS

#1324 [release-1.8] Update Golang to pick up CVE
  docker/build-tools/Dockerfile
Labels: cla: no, cla: yes, release-notes-none, size/XS

#1325 Automator: update common-files@release-1.8 in istio/tools@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1322 [release-1.7] Update Golang for CVE
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1311 [Cherrypick]Install the latest gcloud tool and its beta components in the build-tools image
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1323 [release-1.6] Update Golang for CVE
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1326 Automator: update common-files@release-1.7 in istio/tools@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1327 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1328 Automator: update common-files@release-1.6 in istio/tools@release-1.6
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1329 Add promoted to release notes
  cmd/gen-release-notes/templates/minorReleaseNotes.md
  cmd/gen-release-notes/templates/releaseNotes.md
Labels: cla: yes, size/XS

#1330 Add dependencies for testing
  docker/build-tools/Dockerfile
Labels: cla: yes, do-not-merge, size/XS

#1331 Fix wrongly added dependency
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1332 Automator: update common-files@release-1.8 in istio/tools@release-1.8
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1334 [master] Pin kubetest2 and boskosctl to a fixed version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#1335 Add additional logs to prow entrypoint
  docker/build-tools/prow-entrypoint.sh
Labels: cla: yes, size/S

#1336 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1339 Automator: update common-files@release-1.8 in istio/tools@release-1.8
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#1316 Fix data fetching issue and present p99.9
  perf_dashboard/benchmarks/templates/micro_benchmarks.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/helpers/download.py
  perf_dashboard/regressions/views.py
Labels: cla: yes, size/L

#1221 Bump current release to 1.8 and update history page
  perf_dashboard/docker-compose.yml
  perf_dashboard/dockerfile
  perf_dashboard/history/templates/history.html
Labels: cla: yes, size/S

#1340 Fix dropdown selected issue
  perf_dashboard/benchmarks/templates/cpu_vs_conn.html
  perf_dashboard/benchmarks/templates/cpu_vs_qps.html
  perf_dashboard/benchmarks/templates/mem_vs_conn.html
  perf_dashboard/benchmarks/templates/mem_vs_qps.html
  perf_dashboard/benchmarks/views.py
Labels: cla: yes, size/M

#1333 [release-1.8] Pin kubetest2 and boskosctl to a fixed version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#1341 Disable baseline for v2 stackdriver
  perf/benchmark/configs/istio/telemetryv2_sd_full/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full_accesslogpolicy/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full_accesslogpolicy/latency.yaml
Labels: cla: yes, size/XS

#1342 [release-1.7] Make helm3 binary available also as helm
  docker/build-tools/Dockerfile
Labels: cla: yes, release-notes-none, size/XS

#1343 Update kubetest2 to fix a bug and by the way update gcloud
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1344 [Release-1.8] Update kubetest2 to fix a bug and BTW update gcloud
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1347 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1345 Update kubetest2 and gcloud to the latest version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#1349 Sync common-files and fix lint error
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  perf/stability/sds-certmanager/crds/certmanager.yaml
  perf/stability/sds-certmanager/templates/certmanager.yaml
Labels: cla: yes, size/L

#1315 perf/benchmark: update README
  README.md
  cmd/testlinter/README.md
  perf/benchmark/README.md
  perf/benchmark/configs/README.md
  perf/istio-install/README.md
  perf/load/README.md
  perf/stability/README.md
  pkg/checker/README.md
Labels: cla: yes, size/L

#1338 Add tcp load test for perf benchmark
  perf/benchmark/README.md
  perf/benchmark/runner/runner.py
  perf/benchmark/templates/fortio.yaml
Labels: cla: yes, size/M

#1303 Dual control plane upgrade/downgrade with boutique shop sample microservices application
  upgrade_downgrade/README.md
  upgrade_downgrade/common.sh
  upgrade_downgrade/fortio_utils.sh
  upgrade_downgrade/run_upgrade_downgrade_test.sh
  upgrade_downgrade/templates/boutique/istio-manifests.yaml
  upgrade_downgrade/templates/boutique/k8s-adservice.yaml
  upgrade_downgrade/templates/boutique/k8s-cartservice.yaml
  upgrade_downgrade/templates/boutique/k8s-checkoutservice.yaml
  upgrade_downgrade/templates/boutique/k8s-currencyservice.yaml
  upgrade_downgrade/templates/boutique/k8s-emailservice.yaml
  upgrade_downgrade/templates/boutique/k8s-frontend.yaml
  upgrade_downgrade/templates/boutique/k8s-loadgenerator.yaml
  upgrade_downgrade/templates/boutique/k8s-paymentservice.yaml
  upgrade_downgrade/templates/boutique/k8s-productcatalogservice.yaml
  upgrade_downgrade/templates/boutique/k8s-recommendationservice.yaml
  upgrade_downgrade/templates/boutique/k8s-redis-cart.yaml
  upgrade_downgrade/templates/boutique/k8s-shippingservice.yaml
  upgrade_downgrade/templates/iop-control-plane.yaml
  upgrade_downgrade/templates/iop-gateways.yaml
  upgrade_downgrade/test_dual_control_plane_upgrade_downgrade.sh
  upgrade_downgrade/test_dual_control_plane_upgrade_downgrade_boutique.sh
  upgrade_downgrade/test_upgrade_downgrade.sh
Labels: cla: yes, ok-to-test, size/XXL

#1337 update release qual webhook logic
  perf/stability/alertmanager/webhook.go
Labels: cla: yes, size/S
