Repository istio/tools, pull requests merged in 2020-03, with the labels that each got.

#774 [release-1.4] remove 1.2 sample test results and cherry-pick graph-plotting README
  perf/benchmark/README.md
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-165728_193ff770_qps_1000_c_1_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-170128_193ff770_qps_1000_c_1_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-170529_193ff770_qps_1000_c_1_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-170929_193ff770_qps_1000_c_2_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-171329_193ff770_qps_1000_c_2_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-171730_193ff770_qps_1000_c_2_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-172130_193ff770_qps_1000_c_4_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-172530_193ff770_qps_1000_c_4_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-172931_193ff770_qps_1000_c_4_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-173331_193ff770_qps_1000_c_8_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-173731_193ff770_qps_1000_c_8_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-174132_193ff770_qps_1000_c_8_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-174532_193ff770_qps_1000_c_16_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-174932_193ff770_qps_1000_c_16_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-175333_193ff770_qps_1000_c_16_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-175733_193ff770_qps_1000_c_32_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-180134_193ff770_qps_1000_c_32_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-180534_193ff770_qps_1000_c_32_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-180937_193ff770_qps_1000_c_64_1024_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-181337_193ff770_qps_1000_c_64_1024_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-181738_193ff770_qps_1000_c_64_1024_base.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-182412_7c63ca64_qps_1000_c_1_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-182812_7c63ca64_qps_1000_c_1_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-183212_7c63ca64_qps_1000_c_2_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-183612_7c63ca64_qps_1000_c_2_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-184013_7c63ca64_qps_1000_c_4_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-184413_7c63ca64_qps_1000_c_4_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-184814_7c63ca64_qps_1000_c_8_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-185214_7c63ca64_qps_1000_c_8_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-185614_7c63ca64_qps_1000_c_16_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-190015_7c63ca64_qps_1000_c_16_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-190416_7c63ca64_qps_1000_c_32_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-190816_7c63ca64_qps_1000_c_32_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-191217_7c63ca64_qps_1000_c_64_1024_nomixer_serveronly.json
  perf/benchmark/results-istio-1.2.0-fortio/2019-07-10-191617_7c63ca64_qps_1000_c_64_1024_nomixer_both.json
  perf/benchmark/results-istio-1.2.0-fortio/compiled-results.json
  perf/benchmark/results-istio-1.2.0-fortio/p50.png
  perf/benchmark/results-istio-1.2.0-fortio/p90.png
  perf/benchmark/results-istio-1.2.0-fortio/p99.png
Labels: cla: yes, size/XXL

#775 fix tar latest istio release path issue for upgrade job
  upgrade/run_upgrade_test.sh
Labels: cherrypick/release-1.5, cla: yes, size/XS

#777 fix sd filter and explicitly enable/disable
  perf/benchmark/configs/istio/mixer/installation.yaml
  perf/benchmark/configs/istio/none/installation.yaml
  perf/benchmark/configs/istio/plaintext/installation.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/installation.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/installation.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/installation.yaml
Labels: cla: yes, size/M

#778 Update docker version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#779 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#780 Revert "Update Golang to 1.14.0"
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#575 Use dockerx
  docker/build-tools/build-and-push.sh
Labels: cla: yes, lifecycle/automatically-closed, size/S

#781 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#783 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#784 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#785 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#786 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#776 [release-1.5] fix tar latest istio release path issue for upgrade job
  upgrade/run_upgrade_test.sh
Labels: cla: yes, size/XS

#787 Update looper test for 1.5
  perf/stability/looper/templates/client.yaml
Labels: cla: yes, size/S

#788 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#790 remove unnecessary get masonclient
  bin/setup_cluster.sh
Labels: cla: yes, size/XS

#791 [release-1.5] remove unnecessary get masonclient
  bin/setup_cluster.sh
Labels: cla: yes, size/XS

#789 Add host --headers flag to fortio command for perf test
  perf/benchmark/README.md
  perf/benchmark/runner/runner.py
Labels: cherrypick/release-1.5, cla: yes, size/S

#794 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#793 [release-1.5] Add host --headers flag to fortio command for perf test
  perf/benchmark/README.md
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/S

#795 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#796 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#792 fix install of istio/test-infra dependencies in build-tools
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#797 convert SOURCE/TARGET TAG to GIT_SHA if necessary for fixing upgrade job issues
  upgrade/run_upgrade_test.sh
Labels: cherrypick/release-1.5, cla: yes, size/M

#799 add sanity check of headers
  perf/benchmark/runner/runner.py
Labels: cherrypick/release-1.5, cla: yes

#800 Enable docker IPv6
  docker/build-tools/prow-entrypoint.sh
Labels: cla: yes, ok-to-test, size/S

#798 [release-1.5] convert SOURCE/TARGET TAG to GIT_SHA if necessary for fixing upgrade job issues
  upgrade/run_upgrade_test.sh
Labels: cla: yes, size/M

#801 [release-1.5] add sanity check of headers
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#802 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#803 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#804 go build binaries to /usr/bin
  docker/build-tools/Dockerfile
Labels: cherrypick/release-1.5, cla: yes, size/XS

#805 fix headers keyerror issue in fortio cmd
  perf/benchmark/runner/runner.py
Labels: cherrypick/release-1.5, cla: yes

#806 [release-1.5] fix headers keyerror issue in fortio cmd
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#807 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#809 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#810 fix perf dashboard fetching latest results issue
  perf_dashboard/helpers/download.py
Labels: cherrypick/release-1.5, cla: yes, size/XS

#812 [release-1.5] fix perf dashboard fetching latest results issue
  perf_dashboard/helpers/download.py
Labels: cla: yes, size/XS

#808 Retain .proto ordering for protoc-gen-docs
  cmd/protoc-gen-docs/htmlGenerator.go
Labels: cla: yes, size/M

#811 add mtls in none_both label to make it clearer
  perf_dashboard/static/js/alert_common_func.js
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/static/js/latency_common_func.js
Labels: cherrypick/release-1.5, cla: yes, size/S

#813 [release-1.5] add mtls in none_both label to make it clearer
  perf_dashboard/static/js/alert_common_func.js
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/static/js/latency_common_func.js
Labels: cla: yes, size/S

#815 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#814 reduce configs to run with pipeline
  perf/benchmark/configs/istio/mixer/cpu_mem.yaml
  perf/benchmark/configs/istio/mixer/latency.yaml
  perf/benchmark/configs/istio/none/latency.yaml
  perf/benchmark/configs/istio/plaintext/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/latency.yaml
  perf/benchmark/runner/runner.py
Labels: cherrypick/release-1.5, cla: yes

#816 [release-1.5] reduce configs to run with pipeline
  perf/benchmark/configs/istio/mixer/cpu_mem.yaml
  perf/benchmark/configs/istio/mixer/latency.yaml
  perf/benchmark/configs/istio/none/cpu_mem.yaml
  perf/benchmark/configs/istio/none/latency.yaml
  perf/benchmark/configs/istio/plaintext/latency.yaml
  perf/benchmark/configs/istio/telemetryv2/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2/latency.yaml
Labels: cla: yes, size/M

#820 Fix oneOf representation in doc and schema
  cmd/cue-gen/crd.go
  cmd/cue-gen/genoapi.go
  cmd/protoc-gen-docs/htmlGenerator.go
  go.mod
  go.sum
  licenses/golang.org/x/mod/LICENSE
  licenses/gopkg.in/yaml.v3/LICENSE
Labels: cla: yes, size/L

#821 Add perf-dashboard object yaml files and Makefile
  perf_dashboard/.dockerignore
  perf_dashboard/Makefile
  perf_dashboard/deploy/perf-dashboard/Chart.lock
  perf_dashboard/deploy/perf-dashboard/Chart.yaml
  perf_dashboard/deploy/perf-dashboard/charts/metrics-server-2.10.1.tgz
  perf_dashboard/deploy/perf-dashboard/requirements.yaml
  perf_dashboard/deploy/perf-dashboard/templates/_helpers.tpl
  perf_dashboard/deploy/perf-dashboard/templates/autoscale.yaml
  perf_dashboard/deploy/perf-dashboard/templates/certificate.yaml
  perf_dashboard/deploy/perf-dashboard/templates/deployment.yaml
  perf_dashboard/deploy/perf-dashboard/templates/ingress.yaml
  perf_dashboard/deploy/perf-dashboard/templates/service.yaml
  perf_dashboard/deploy/perf-dashboard/values.yaml
  perf_dashboard/perf_dashboard/settings.py
Labels: cla: yes, size/L

#817 disable some of unimportant perf test runs
  perf/benchmark/configs/istio/mixer/latency.yaml
  perf/benchmark/configs/istio/none/cpu_mem.yaml
  perf/benchmark/configs/istio/none/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/latency.yaml
Labels: cla: yes, size/M

#818 disable clientonly and serveronly modes in displaying on perf dashboard
  perf_dashboard/benchmarks/views.py
  perf_dashboard/static/js/alert_common_func.js
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/static/js/latency_common_func.js
Labels: cherrypick/release-1.5, cla: yes, size/L

#825 Make messages come before enums
  cmd/protoc-gen-docs/htmlGenerator.go
Labels: cla: yes, size/M

#826 Updated docker-ce and containerd
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#822 [release-1.5] Fix oneOf representation in doc and schema
  cmd/cue-gen/crd.go
  cmd/cue-gen/genoapi.go
  cmd/protoc-gen-docs/htmlGenerator.go
  docker/build-tools/Dockerfile
  go.mod
  go.sum
  licenses/golang.org/x/mod/LICENSE
  licenses/gopkg.in/yaml.v3/LICENSE
Labels: cla: yes, size/L

#824 [release-1.5] disable clientonly and serveronly modes in displaying on perf dashboard
  perf_dashboard/benchmarks/views.py
  perf_dashboard/static/js/alert_common_func.js
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/static/js/latency_common_func.js
Labels: cla: yes, size/L

#830 Automator: update common-files@release-1.5 in istio/tools@release-1.5
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/license-lint.yml
  common/scripts/lint_go.sh
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#831 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#832 add extra_labels mtls for none telemetry mode
  perf/benchmark/configs/istio/none/cpu_mem.yaml
  perf/benchmark/configs/istio/none/latency.yaml
Labels: cherrypick/release-1.5, cla: yes, size/XS

#823 update telemetry v2 labels for perf dashboard
  perf_dashboard/benchmarks/templates/cpu_memory.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/static/js/latency_common_func.js
Labels: cherrypick/release-1.5, cla: yes, size/XL

#835 Helm3 support
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#834 [release-1.5] update telemetry v2 labels for perf dashboard
  perf_dashboard/benchmarks/templates/cpu_memory.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/static/js/latency_common_func.js
Labels: cla: yes, size/XL

#836 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#833 [release-1.5] add extra_labels mtls for none telemetry mode
  perf/benchmark/configs/istio/none/cpu_mem.yaml
  perf/benchmark/configs/istio/none/latency.yaml
Labels: cla: yes, size/XS

#837 add baseline for both benchmark and trending pattern graphs
  perf_dashboard/artifacts/templates/artifact.html
  perf_dashboard/benchmarks/templates/cpu_memory.html
  perf_dashboard/benchmarks/templates/flame_graph.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/templates/micro_benchmarks.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/graph_plotting/templates/graph_plotting.html
  perf_dashboard/history/templates/history.html
  perf_dashboard/perf_dashboard/settings.py
  perf_dashboard/perf_dashboard/urls.py
  perf_dashboard/regression_alerts/views.py
  perf_dashboard/regression_pattern/__init__.py
  perf_dashboard/regression_pattern/admin.py
  perf_dashboard/regression_pattern/apps.py
  perf_dashboard/regression_pattern/migrations/__init__.py
  perf_dashboard/regression_pattern/models.py
  perf_dashboard/regression_pattern/templates/cur_pattern.html
  perf_dashboard/regression_pattern/templates/master_pattern.html
  perf_dashboard/regression_pattern/tests.py
  perf_dashboard/regression_pattern/urls.py
  perf_dashboard/regression_pattern/views.py
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/static/js/cur_alert.js
  perf_dashboard/static/js/cur_pattern.js
  perf_dashboard/static/js/latency_common_func.js
  perf_dashboard/static/js/master_alert.js
  perf_dashboard/static/js/master_pattern.js
  perf_dashboard/static/js/pattern_common_func.js
  perf_dashboard/templates/index.html
Labels: cla: yes, size/XL

#827 update service graph script
  perf/istio-install/setup_istio_new_installer.sh
  perf/load/run_servicegraph_job.sh
Labels: cla: yes, size/L

#841 Fix perf-dashboard deploy for helm2
  perf_dashboard/Makefile
Labels: cla: yes, size/XS

#838 Add consistency for helmv2/v3 testing tools
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#840 [release-1.5] add baseline for both benchmark and trending pattern graphs
  perf_dashboard/artifacts/templates/artifact.html
  perf_dashboard/benchmarks/templates/cpu_memory.html
  perf_dashboard/benchmarks/templates/flame_graph.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/templates/micro_benchmarks.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/graph_plotting/templates/graph_plotting.html
  perf_dashboard/history/templates/history.html
  perf_dashboard/perf_dashboard/settings.py
  perf_dashboard/perf_dashboard/urls.py
  perf_dashboard/regression_alerts/views.py
  perf_dashboard/regression_pattern/__init__.py
  perf_dashboard/regression_pattern/admin.py
  perf_dashboard/regression_pattern/apps.py
  perf_dashboard/regression_pattern/migrations/__init__.py
  perf_dashboard/regression_pattern/models.py
  perf_dashboard/regression_pattern/templates/cur_pattern.html
  perf_dashboard/regression_pattern/templates/master_pattern.html
  perf_dashboard/regression_pattern/tests.py
  perf_dashboard/regression_pattern/urls.py
  perf_dashboard/regression_pattern/views.py
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/static/js/cur_alert.js
  perf_dashboard/static/js/cur_pattern.js
  perf_dashboard/static/js/latency_common_func.js
  perf_dashboard/static/js/master_alert.js
  perf_dashboard/static/js/master_pattern.js
  perf_dashboard/static/js/pattern_common_func.js
  perf_dashboard/templates/index.html
Labels: cla: yes, size/XL

#845 update default perf
  perf/istio-install/istioctl_profiles/default.yaml
Labels: cla: yes, size/XS

#839 Cleanup namespaces with service-graph
  perf/load/common.sh
  perf/load/loadclient/setup_test.sh
  perf/load/templates/service-graph.gen.yaml
Labels: cla: yes, size/S

#848 (feat) make x-axis interval proportionally under linear setting
  perf_dashboard/benchmarks/templates/cpu_memory.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/static/js/cpu_memory.js
  perf_dashboard/static/js/latency_common_func.js
  perf_dashboard/static/js/latency_conn.js
  perf_dashboard/static/js/latency_qps.js
  perf_dashboard/static/js/utils.js
Labels: cherrypick/release-1.5, cla: yes, size/M

#850 Unicode was removed in Python in favor of str
  bin/update_dns.py
Labels: cla: yes, ok-to-test, size/XS

#849 Undefined name: 'start' in load_test.py
  perf/load/pilot/load_test.py
Labels: cla: yes, ok-to-test, size/XS
