Repository istio/tools, pull requests merged in 2020-12, with the labels that each got.

#1351 fix python version and some minor fixes in README.md
  upgrade_downgrade/README.md
  upgrade_downgrade/fortio_utils.sh
Labels: cla: yes, ok-to-test, size/XS

#1352 Pinning GN version
  docker/build-tools/Dockerfile.centos
Labels: cla: yes, size/XS

#1355 Automator: update common-files@release-1.7 in istio/tools@release-1.7
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1354 perf/benchmark: update plaintext postrun script
  perf/benchmark/configs/istio/plaintext/postrun.sh
Labels: cla: yes, size/XS

#1357 Enable plaintext run
  perf/benchmark/configs/run_perf_test.conf
Labels: cla: yes, size/XS

#1353 Add ingressgateway perf number to dashboard
  perf/benchmark/configs/run_perf_test.conf
  perf_dashboard/benchmarks/templates/cpu_vs_conn.html
  perf_dashboard/benchmarks/templates/cpu_vs_qps.html
  perf_dashboard/benchmarks/templates/mem_vs_conn.html
  perf_dashboard/benchmarks/templates/mem_vs_qps.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/static/js/cpu_conn.js
  perf_dashboard/static/js/cpu_qps.js
  perf_dashboard/static/js/mem_conn.js
  perf_dashboard/static/js/mem_qps.js
Labels: cla: yes, size/XL

#1359 Fix tcp fortio json parsing issue
  perf/benchmark/configs/run_perf_test.conf
  perf/benchmark/runner/fortio.py
Labels: cla: yes, size/S

#1360 Add ingressgw perf to CPU vs Conn
  perf_dashboard/benchmarks/templates/cpu_vs_conn.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/regressions/views.py
Labels: cla: yes, size/M

#1361 Update to docker 20.10
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1362 errorPercent key only available when RunType is HTTP
  perf/benchmark/runner/fortio.py
Labels: cla: yes, size/XS

#1363 Fix pipeline issue
  perf/benchmark/runner/fortio.py
Labels: cla: yes, size/XS

#1365 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1366 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1364 fix readme
  cmd/license-lint/README.md
Labels: cla: yes, size/XS

#1356 Minor fixes for upgrade downgrade tests to fix test failures
  upgrade_downgrade/run_upgrade_downgrade_test.sh
  upgrade_downgrade/test_dual_control_plane_upgrade_downgrade_boutique.sh
  upgrade_downgrade/test_upgrade_downgrade.sh
Labels: cla: yes, ok-to-test, size/S

#1367 Add Kind filtering and negation support to release notes
  cmd/gen-release-notes/README.md
  cmd/gen-release-notes/main.go
  cmd/gen-release-notes/note.go
  cmd/gen-release-notes/template.go
  cmd/gen-release-notes/templates/minorReleaseNotes.md
Labels: cla: yes, size/M

#1368 minor fixes in upgrade/downgrade tests
  upgrade_downgrade/test_dual_control_plane_upgrade_downgrade_boutique.sh
  upgrade_downgrade/test_upgrade_downgrade.sh
Labels: cla: yes, ok-to-test, size/S
