Repository istio/tools, pull requests merged in 2020-08, with the labels that each got.

#1102 Add flame graph links
  perf_dashboard/benchmarks/templates/flame_graph.html
  perf_dashboard/benchmarks/views.py
Labels: cla: yes, size/L

#1119 Automator: update common-files@release-1.7 in istio/tools@release-1.7
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1118 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1120 Update golangci-lint to 1.30
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1108 Egress SDS Perf Test
  perf/security/sds-tests/egress-sds/README.md
  perf/security/sds-tests/egress-sds/cleanup.sh
  perf/security/sds-tests/egress-sds/request_script.sh
  perf/security/sds-tests/egress-sds/setup_client.sh
  perf/security/sds-tests/egress-sds/setup_destinationrule.sh
  perf/security/sds-tests/egress-sds/setup_gateway.sh
  perf/security/sds-tests/egress-sds/setup_nginx.sh
  perf/security/sds-tests/egress-sds/setup_test.sh
  perf/security/sds-tests/egress-sds/setup_virtualservice.sh
Labels: cla: yes, size/XL

#1117 Add more flexibility to generate_policies
  perf/benchmark/security/generate_policies/README.md
  perf/benchmark/security/generate_policies/generate.go
  perf/benchmark/security/generate_policies/generate_policies.go
Labels: cla: yes, ok-to-test, size/L

#1122 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1123 Add prometheus pod debugging info
  perf/benchmark/run_benchmark_job.sh
Labels: cherrypick/release-1.7, cla: yes, size/S

#1124 [release-1.7] Add prometheus pod debugging info
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, release-notes-none, size/S

#1125 Update shellcheck URL
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1128 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1129 List pods in istio-system namespace
  perf/benchmark/run_benchmark_job.sh
Labels: cherrypick/release-1.7, cla: yes, size/XS

#1130 [release-1.7] List pods in istio-system namespace
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, release-notes-none, size/XS

#1126 [release-1.7] Update shellcheck URL
  docker/build-tools/Dockerfile
Labels: cla: yes, release-notes-none, size/XS

#1131 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1132 fix prometheus namespace
  perf/benchmark/run_benchmark_job.sh
Labels: cherrypick/release-1.7, cla: yes

#1133 [release-1.7] fix prometheus namespace
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, release-notes-none, size/XS

#1134 Remove Prometheus debug
  perf/benchmark/run_benchmark_job.sh
Labels: cherrypick/release-1.7, cla: yes, size/S

#1135 [release-1.7] Remove Prometheus debug
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, release-notes-none, size/S

#1139 fix benchmark master job
  perf/istio-install/istioctl_profiles/default-overlay.yaml
  perf/istio-install/setup_istio.sh
Labels: cla: yes, size/S

#1136 Enable WASM telemetry for perf
  perf/benchmark/configs/run_perf_test.conf
Labels: cherrypick/release-1.7, cla: yes, size/XS

#1140 [release-1.7] Enable WASM telemetry for perf
  perf/benchmark/configs/run_perf_test.conf
Labels: cla: yes, release-notes-none, size/XS

#1142 make the presubmit job shorter
  perf/benchmark/configs/trialrun.yaml
  perf/benchmark/run_benchmark_job.sh
  perf/istio-install/istioctl_profiles/default-overlay.yaml
  perf/istio-install/istioctl_profiles/long-running.yaml
Labels: cla: yes, size/S

#1141 Bump golang
  docker/build-tools/Dockerfile
Labels: cherrypick/release-1.7, cla: yes, size/XS

#1143 [release-1.7] Bump golang
  docker/build-tools/Dockerfile
Labels: cla: yes, release-notes-none, size/XS

#1145 [release-1.5] Bump golang
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1148 Automator: update common-files@release-1.7 in istio/tools@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1147 Update common files and fix lint
  bin/root-transition.sh
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  perf/load/common.sh
  perf/security/sds-tests/egress-sds/setup_test.sh
  perf/security/sds-tests/ingress-sds/setup_test.sh
Labels: cla: yes, size/S

#1153 Fix lint-yaml
  Makefile.core.mk
Labels: cla: yes, size/XS

#1152 [release-1.7] Update common and fix lint
  Makefile.core.mk
  bin/root-transition.sh
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
  perf/load/common.sh
  perf/security/sds-tests/ingress-sds/setup_test.sh
Labels: cla: yes, size/S

#1154 add k8s servicemonitor
  perf/istio-install/addons/servicemonitors.yaml
  perf/istio-install/setup_istio.sh
Labels: cla: yes, size/M

#1150 clean up mixer in benchmark tests
  perf/benchmark/README.md
  perf/benchmark/configs/istio/none/cpu_mem.yaml
  perf/benchmark/configs/istio/none/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/installation.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/installation.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/installation.yaml
  perf/benchmark/configs/istio/telemetryv2_statswasm/installation.yaml
  perf/benchmark/configs/run_perf_test.conf
  perf/benchmark/runner/prom.py
  perf/benchmark/runner/runner.py
  perf/benchmark/update_mesh_config.py
Labels: cla: yes, size/L

#1146 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci-format.yml
  common/scripts/format_go.sh
Labels: auto-merge, cla: yes, release-notes-none, size/M

#1156 [release-1.7] Fix nighthawk cmd
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/XS

#1157 Bump current release to 1.7 and add WASM data into dashboard
  perf_dashboard/benchmarks/templates/cpu_vs_conn.html
  perf_dashboard/benchmarks/templates/cpu_vs_qps.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/templates/mem_vs_conn.html
  perf_dashboard/benchmarks/templates/mem_vs_qps.html
  perf_dashboard/benchmarks/views.py
  perf_dashboard/docker-compose.yml
  perf_dashboard/dockerfile
  perf_dashboard/static/js/cpu_conn.js
  perf_dashboard/static/js/cpu_qps.js
  perf_dashboard/static/js/latency_common_func.js
  perf_dashboard/static/js/mem_conn.js
  perf_dashboard/static/js/mem_qps.js
Labels: cla: yes, size/L

#1158 update prom query for cadvisor metrics
  perf/benchmark/runner/prom.py
Labels: cherrypick/release-1.7, cla: yes, size/S

#1159 [release-1.7] update prom query for cadvisor metrics (#1158)
  perf/benchmark/runner/prom.py
Labels: cla: yes, size/S

#1155 Fix nighthawk cmd and remove deprecated fields
  perf/benchmark/runner/runner.py
  perf/istio-install/istioctl_profiles/default-overlay.yaml
Labels: cla: yes, size/XS

#1161 Fix upgrade job install/upgrade failure
  upgrade/test_crossgrade.sh
Labels: cla: yes, size/XS

#1149 Release Notes Tooling
  CODEOWNERS
  cmd/gen-release-notes/README.md
  cmd/gen-release-notes/main.go
  cmd/gen-release-notes/templates/minorReleaseNotes.md
  cmd/gen-release-notes/templates/releaseNotes.md
  cmd/gen-release-notes/templates/upgradeNotes.md
Labels: cla: yes, size/L

#1162 Update version of LLVM used
  docker/build-tools/Dockerfile.centos
Labels: cla: yes, size/XS

#1163 Make notes an array
  cmd/gen-release-notes/main.go
Labels: cla: yes, size/M

#1127 [release-1.6] Update shellcheck URL
  docker/build-tools/Dockerfile
Labels: cla: yes, release-notes-none, size/XS

#1144 [release-1.6] Bump golang
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1160 Add PeerAuthN functionality to generate_policies
  perf/benchmark/security/generate_policies/README.md
  perf/benchmark/security/generate_policies/generate.go
  perf/benchmark/security/generate_policies/generate_policies.go
Labels: cla: yes, ok-to-test, size/XL

#1164 Bump golang to 1.15.0
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1165 Use kube DNS pod/svc name via env variable
  perf/benchmark/setup_test.sh
Labels: cla: yes, ok-to-test, size/XS

#1166 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1167 Update upgrade test to use latest version
  upgrade/run_upgrade_test.sh
  upgrade/test_crossgrade.sh
Labels: cla: yes, size/S

#1169 use the correct upgrade cmd as we ask users to do
  upgrade/run_upgrade_test.sh
  upgrade/test_crossgrade.sh
Labels: cla: yes, size/S

#1170 Update fortio image to use the latest release
  perf/benchmark/setup_test.sh
  perf/benchmark/values.yaml
Labels: cla: yes, size/XS

#1171 [release-1.7] Update fortio image to use the latest release
  perf/benchmark/setup_test.sh
  perf/benchmark/values.yaml
Labels: cla: yes, release-notes-none, size/XS

#1168 [release-1.7] Update upgrade test to use latest version
  upgrade/run_upgrade_test.sh
  upgrade/test_crossgrade.sh
Labels: cla: yes, release-notes-none, size/S

#1173 Fixes typo in cue-gen all? version: v1alpha1 string default
  cmd/cue-gen/doc.cue
Labels: cla: yes, ok-to-test, size/XS

#1174 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#1172 Fix upgrade SOURCE_TAG issue
  upgrade/run_upgrade_test.sh
Labels: cla: yes, size/XS

#1175 [release-1.7] Fix upgrade job issue
  upgrade/run_upgrade_test.sh
Labels: cla: yes, size/XS

#1177 Remove duplicated value in overlay yaml
  perf/istio-install/istioctl_profiles/default-overlay.yaml
Labels: cla: yes, size/XS

#1178 [release-1.7] Remove duplicated value in overlay yaml
  perf/istio-install/istioctl_profiles/default-overlay.yaml
Labels: cla: yes, release-notes-none, size/XS

#1176 Dashboard should take release version as priority not dates
  perf_dashboard/helpers/download.py
Labels: cla: yes, size/M

#1138 Revert cue-gen move to v1, move back to v1beta1
  cmd/cue-gen/build.go
  cmd/cue-gen/crd.go
  cmd/cue-gen/genoapi.go
  cmd/cue-gen/test/crdgen_test.go
  cmd/cue-gen/test/generated/kubernetes/customresourcedefinitions.gen.yaml
Labels: cla: yes, size/L

#1181 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1182 Rename upgrade to upgrade_downgrade
  upgrade_downgrade/README.md
  upgrade_downgrade/run_upgrade_downgrade_test.sh
  upgrade_downgrade/templates/fortio-cli.yaml
  upgrade_downgrade/templates/fortio.yaml
  upgrade_downgrade/templates/gateway.yaml
  upgrade_downgrade/test_upgrade_downgrade.sh
Labels: cla: yes, size/S

#1179 Add RequestAuthentication flexibility to generate_policies
  go.mod
  go.sum
  perf/benchmark/security/generate_policies/README.md
  perf/benchmark/security/generate_policies/generate.go
  perf/benchmark/security/generate_policies/generate_policies.go
  perf/benchmark/security/generate_policies/jwt.go
Labels: cla: yes, ok-to-test, size/L

#1184 Release notes work
  cmd/gen-release-notes/README.md
  cmd/gen-release-notes/main.go
  cmd/gen-release-notes/note.go
  cmd/gen-release-notes/template.go
  cmd/gen-release-notes/templates/minorReleaseNotes.md
  cmd/gen-release-notes/templates/releaseNotes.md
Labels: cla: yes, size/XL

#1186 Additional release notes work
  cmd/gen-release-notes/main.go
  cmd/gen-release-notes/note.go
  cmd/gen-release-notes/templates/minorReleaseNotes.md
  cmd/gen-release-notes/templates/releaseNotes.md
  cmd/gen-release-notes/templates/upgradeNotes.md
Labels: cla: yes, size/M

#1187 Add generated DeepCopyInterface method
  cmd/protoc-gen-deepcopy/deepcopy/plugin.go
  cmd/protoc-gen-deepcopy/test/deepcopy_test.go
  cmd/protoc-gen-deepcopy/test/generated/types.pb.go
  cmd/protoc-gen-deepcopy/test/generated/types_deepcopy.gen.go
Labels: cla: yes, size/S
