Repository istio/tools, pull requests merged in 2021-04, with the labels that each got.

#1474 Add security perf test
  perf/benchmark/configs/istio/security_authz/config.json
  perf/benchmark/configs/istio/security_authz/latency.yaml
  perf/benchmark/configs/istio/security_authz/postrun.sh
  perf/benchmark/configs/istio/security_authz/prerun.sh
  perf/benchmark/configs/run_perf_test.conf
Labels: cla: yes, size/M

#1476 Bump to go 1.16.3
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1477 Update GH to 1.8.1
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1479 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1475 Add security perf test for AuthZ, AuthN and RequestAuthn
  perf/benchmark/configs/istio/security_authz_ip/config.json
  perf/benchmark/configs/istio/security_authz_ip/cpu_mem.yaml
  perf/benchmark/configs/istio/security_authz_ip/latency.yaml
  perf/benchmark/configs/istio/security_authz_ip/postrun.sh
  perf/benchmark/configs/istio/security_authz_ip/prerun.sh
  perf/benchmark/configs/istio/security_authz_jwt/config.json
  perf/benchmark/configs/istio/security_authz_jwt/cpu_mem.yaml
  perf/benchmark/configs/istio/security_authz_jwt/latency.yaml
  perf/benchmark/configs/istio/security_authz_jwt/postrun.sh
  perf/benchmark/configs/istio/security_authz_jwt/prerun.sh
  perf/benchmark/configs/istio/security_authz_path/config.json
  perf/benchmark/configs/istio/security_authz_path/cpu_mem.yaml
  perf/benchmark/configs/istio/security_authz_path/latency.yaml
  perf/benchmark/configs/istio/security_authz_path/postrun.sh
  perf/benchmark/configs/istio/security_authz_path/prerun.sh
  perf/benchmark/configs/istio/security_peer_authn/config.json
  perf/benchmark/configs/istio/security_peer_authn/cpu_mem.yaml
  perf/benchmark/configs/istio/security_peer_authn/latency.yaml
  perf/benchmark/configs/istio/security_peer_authn/postrun.sh
  perf/benchmark/configs/istio/security_peer_authn/prerun.sh
  perf/benchmark/configs/run_perf_test.conf
Labels: cla: yes, size/L

#1480 Add home to centos
  docker/build-tools/Dockerfile.centos
Labels: cla: yes, size/XS

#1482 [release-1.8] Add home to centos
  docker/build-tools/Dockerfile.centos
Labels: cla: yes, release-notes-none, size/XS

#1481 [release-1.9] Add home to centos
  docker/build-tools/Dockerfile.centos
Labels: cla: yes, release-notes-none, size/XS

#1484 [release-1.10] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  docker/build-tools/build-and-push.sh
Labels: cla: yes, release-notes-none, size/XS

#1485 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1486 Automator: update common-files@release-1.10 in istio/tools@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1487 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1483 [release-1.10] Add home to centos
  docker/build-tools/Dockerfile.centos
Labels: cla: yes, release-notes-none, size/XS

#1488 Automator: update common-files@release-1.9 in istio/tools@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1489 Automator: update common-files@release-1.8 in istio/tools@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1491 Fix common files in master branch
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#1490 Fix security perf test issue and disable security_authz_jwt first
  perf/benchmark/configs/istio/security_authz_jwt/prerun.sh
  perf/benchmark/configs/run_perf_test.conf
Labels: cla: yes, size/XS

#1492 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1494 Edit running config
  perf/benchmark/configs/run_perf_test.conf
Labels: cla: yes, size/XS

#1496 Security RequestAuthz perf test
  perf/benchmark/configs/istio/security_authz_jwt/cpu_mem.yaml
  perf/benchmark/configs/istio/security_authz_jwt/postrun.sh
  perf/benchmark/configs/istio/security_authz_jwt/prerun.sh
  perf/benchmark/configs/run_perf_test.conf
Labels: cla: yes, size/S

#1493 fix: graph plotter cpu and mem graph error
  perf/benchmark/graph_plotter/graph_plotter.py
Labels: cla: yes, ok-to-test, size/XS

#1497 Update clang version to 11.0.1
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1498 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1499 [release-1.9] update go to use 1.15.11
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1500 Automator: update common-files@release-1.10 in istio/tools@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1501 gobin no longer needed as of go1.16; can use go install instead
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1502 Automator: update common-files@release-1.9 in istio/tools@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1503 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1504 enable telemetry tests and normalize security conn and qps usage
  perf/benchmark/configs/istio/security_authz_ip/cpu_mem.yaml
  perf/benchmark/configs/istio/security_authz_ip/latency.yaml
  perf/benchmark/configs/istio/security_authz_jwt/cpu_mem.yaml
  perf/benchmark/configs/istio/security_authz_jwt/latency.yaml
  perf/benchmark/configs/istio/security_authz_path/cpu_mem.yaml
  perf/benchmark/configs/istio/security_authz_path/latency.yaml
  perf/benchmark/configs/istio/security_peer_authn/cpu_mem.yaml
  perf/benchmark/configs/istio/security_peer_authn/latency.yaml
  perf/benchmark/configs/run_perf_test.conf
Labels: cla: yes, size/S

#1505 update README for stability test
  perf/stability/README.md
  perf/stability/logs-checker/check_k8s_logs.sh
  perf/stability/logs-checker/templates/check_k8s_logs.yaml
  perf/stability/long_running.sh
Labels: cla: yes, size/M

#1506 fix typo in the check logs script
  perf/stability/README.md
  perf/stability/logs-checker/check_k8s_logs.sh
Labels: cla: yes, size/XS

#1508 Updated github cli tools to v1.9.2 in build-tools Dockerfile
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS
