Repository istio/tools, pull requests merged in 2021-06, with the labels that each got.

#1556 Update gh
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1557 Update kubetest2 to a new version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1558 fix fortio/nighthawk deployment
  perf/benchmark/templates/fortio.yaml
  perf/benchmark/values.yaml
Labels: cla: yes, size/XS

#1560 Update build tools to ubuntu:focal
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#1562 [release-1.9] Update to Golang 1.15.13
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1561 Update to Golang 1.16.5
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1566 Automator: update common-files@release-1.9 in istio/tools@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1565 build: install python3.8 in proxy build image
  docker/build-tools/Dockerfile
  docker/build-tools/install-python-3.8.sh
Labels: cla: yes, size/S

#1568 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1569 [release-1.10] Update kubetest2 to the latest valid version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1572 Allow skipping envvarlinter for specific files
  pkg/checker/checker.go
Labels: cherrypick/release-1.10, cla: yes, size/S

#1573 [release-1.10] Allow skipping envvarlinter for specific files
  pkg/checker/checker.go
Labels: cla: yes, release-notes-none, size/S

#1574 Bump GCR auth
  docker/build-tools/Dockerfile
Labels: cherrypick/release-1.10, cla: yes, size/XS

#1576 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1567 [release-1.10] fix fortio/nighthawk deployment
  perf/benchmark/templates/fortio.yaml
  perf/benchmark/values.yaml
Labels: cla: yes, release-notes-none, size/XS

#1578 Update GN to match the version used in V8 v9.2.
  docker/build-tools/Dockerfile.centos
Labels: cla: yes, size/XS

#1575 [release-1.10] Bump GCR auth
  docker/build-tools/Dockerfile
Labels: cla: yes, release-notes-none, size/XS

#1563 [release-1.10] Update to Golang 1.16.5
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1580 Automator: update common-files@release-1.10 in istio/tools@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1577 add debug info to check the flamegraph status
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/runner.py
Labels: cla: yes, size/S

#1581 install linux tools for perf data
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#1583 skip confirmation for apt-get
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, size/XS

#1584 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1582 remove reduntant type conversion
  isotope/convert/pkg/graph/unmarshal_test.go
Labels: cla: yes, ok-to-test, size/XS

#1585 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#1586 Add Trivy
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1587 Update kubetest2 to the latest version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1589 Update LLVM/clang to 10.0 for centos
  docker/build-tools/Dockerfile.centos
Labels: cla: yes, size/XS

#1590 Update kubetest2 to the latest version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1591 [Release-1.10] Update kubetest2 to the latest version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1592 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1593 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS
