Repository istio/tools, pull requests merged in 2021-11, with the labels that each got.

#1737 Update gcloud to 362
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1738 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1741 Upgrade cosign to support arm64 platform
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS, ok-to-test

#1742 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1743 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1744 Update Golang to 1.17.3
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1747 Add crane to docker image
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1745 Update hadolint version plus lint fixes
  docker/build-tools/Dockerfile
Labels: cla: yes, size/M

#1748 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1749 [release-1.12] Use golang 1.17.3
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1751 [release-1.11] Update go to 1.16.10
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1752 Automator: update common-files@release-1.12 in istio/tools@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1753 Always enable ipv6 sysctl
  docker/build-tools/prow-entrypoint.sh
Labels: cla: yes, size/S

#1754 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1750 [release-1.10] Update to golang 1.16.10
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1755 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: cla: yes, size/M, auto-merge, release-notes-none

#1756 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1757 Use sigs.k8s.io/yaml instead of ghodss
  cmd/annotations_prep/main.go
  cmd/cue-gen/genoapi.go
  cmd/cue-gen/test/crdgen_test.go
  cmd/gen-release-notes/main.go
  cmd/license-lint/config.go
  go.mod
  go.sum
  isotope/convert/cmd/graphviz.go
  isotope/convert/cmd/kubernetes.go
  isotope/convert/pkg/graph/script/command.go
  isotope/convert/pkg/kubernetes/kubernetes.go
  isotope/go.mod
  isotope/go.sum
  isotope/service/pkg/srv/graph.go
  perf/benchmark/security/generate_policies/generate_policies.go
Labels: cla: yes, size/M

#1758 [release-1.12] Update gcloud to 362
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS, release-notes-none

#1759 Update gcloud to 362 (#1737)
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1760 Automator: update common-files@release-1.12 in istio/tools@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1762 Automator: update common-files@release-1.11 in istio/tools@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1765 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1764 docs gen: allow mix of `<mode>` and `none`
  cmd/protoc-gen-docs/htmlGenerator.go
Labels: cla: yes, size/M

#1766 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none
