Repository istio/tools, pull requests merged in 2021-07, with the labels that each got.

#1346 build tools for arm64
  docker/build-tools/Dockerfile
  docker/build-tools/proxy-tsan-instrumented-libcxx.sh
Labels: cla: yes, ok-to-test, size/L

#1594 Add "file"
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1597 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1598 Add buf back to build-tools
  docker/build-tools/Dockerfile
Labels: cla: yes, size/M

#1599 Add gcloud beta component back which was accidentally removed
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1601 Fix protoc arm64 build
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1600 Do not build centos build-tools container on Arm
  docker/build-tools/build-and-push.sh
Labels: cla: yes, ok-to-test, size/XS

#1602 update gh version to the latest
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1603 [release-1.10] Add Trivy
  docker/build-tools/Dockerfile
Labels: cla: yes, release-notes-none, size/XS

#1604 [release-1.9] Add Trivy
  docker/build-tools/Dockerfile
Labels: cla: yes, release-notes-none, size/S

#1606 Automator: update common-files@release-1.10 in istio/tools@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1607 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1608 Automator: update common-files@release-1.9 in istio/tools@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1609 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1610 fix depedencies which are broken for Arm64 builds
  docker/build-tools/Dockerfile
Labels: cla: yes, ok-to-test, size/S

#1612 Update to Golang 1.16.6
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1613 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1614 Test reverting back to earlier buf
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1611 Fix broken link in CUE readme
  cmd/cue-gen/README.md
Labels: cla: yes, size/XS

#1616 [release-1.10] Update golang to v1.16.6
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1615 [release-1.9] Update go CVE version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1617 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1618 Update to latest buf
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1619 Automator: update common-files@release-1.9 in istio/tools@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1620 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1621 Automator: update common-files@release-1.10 in istio/tools@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1623 Build 1.11 release
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/XS

#1626 Set release managers as CODEOWNERS for release-1.11.
  CODEOWNERS
Labels: cla: yes, size/XS

#1628 Use go 1.16.6 in the actual build script
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/XS

#1622 downgrade ubuntu to bionic for arm64 build-tools-proxy to bump glibc version
  docker/build-tools/Dockerfile
Labels: cla: yes, ok-to-test, size/S

#1629 [release-1.11] Automated branching step 4
  common/Makefile.common.mk
Labels: cla: yes, release-notes-none, size/XS

#1630 Automator: update common-files@release-1.11 in istio/tools@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1631 Install alpha component in gcloud
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1632 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1633 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1634 Update kubetest2 to the latest version
  docker/build-tools/Dockerfile
Labels: cherrypick/release-1.10, cherrypick/release-1.11, cla: yes, size/XS

#1637 Update gcloud version
  docker/build-tools/Dockerfile
Labels: cherrypick/release-1.10, cherrypick/release-1.11, cla: yes

#1635 [release-1.11] Update kubetest2 to the latest version
  docker/build-tools/Dockerfile
Labels: cla: yes, release-notes-none, size/XS

#1636 [release-1.10] Update kubetest2 to the latest version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1640 fix prometheusrule.yaml
  perf/stability/alertmanager/prometheusrule.yaml
Labels: cla: yes, size/S

#1642 Bump kind version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1641 Replace KUBE_DNS config with DNS_SVC and DNS_POD
  perf/benchmark/setup_test.sh
Labels: cla: yes, ok-to-test, size/XS

#1644 Automator: update common-files@release-1.10 in istio/tools@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1639 [release-1.10] Update gcloud version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1646 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1638 [release-1.11] Update gcloud version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1645 Fix release notes to use GH PR view
  cmd/gen-release-notes/main.go
Labels: cla: yes, size/S

#1647 cherry pick ubuntu downgrade to bionic for arm64 build-tools-proxy
  docker/build-tools/Dockerfile
Labels: cla: yes, ok-to-test, size/S

#1648 Automator: update common-files@release-1.11 in istio/tools@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1649 Update kpt version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1652 Add debug to release notes tooling
  cmd/gen-release-notes/main.go
Labels: cla: yes, size/M

#1653 Pass ENV to gh
  cmd/gen-release-notes/main.go
Labels: cla: yes, size/S

#1655 Fix release notes to use GH PR view. (#1645)
  cmd/gen-release-notes/main.go
Labels: cherrypick/release-1.10, cherrypick/release-1.9, cla: yes, size/M

#1658 Support zero remotes
  cmd/gen-release-notes/main.go
Labels: cherrypick/release-1.10, cherrypick/release-1.11, cherrypick/release-1.9, cla: yes, size/S

#1657 [release-1.9] Fix release notes to use GH PR view. (#1645)
  cmd/gen-release-notes/main.go
Labels: cla: yes, release-notes-none, size/M

#1660 [release-1.11] Support zero remotes
  cmd/gen-release-notes/main.go
Labels: cla: yes, release-notes-none, size/S

#1661 [release-1.9] Support zero remotes
  cmd/gen-release-notes/main.go
Labels: cla: yes, release-notes-none, size/S

#1656 [release-1.10] Fix release notes to use GH PR view. (#1645)
  cmd/gen-release-notes/main.go
Labels: cla: yes, release-notes-none, size/M

#1659 [release-1.10] Support zero remotes
  cmd/gen-release-notes/main.go
Labels: cla: yes, release-notes-none, size/S
