Repository istio/tools, pull requests merged in 2021-01, with the labels that each got.

#1371 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1369 Disable plaintext perf run
  perf/benchmark/configs/run_perf_test.conf
  perf_dashboard/static/js/cpu_conn.js
  perf_dashboard/static/js/cpu_qps.js
  perf_dashboard/static/js/latency_common_func.js
  perf_dashboard/static/js/mem_conn.js
  perf_dashboard/static/js/mem_qps.js
Labels: cla: yes, size/S

#1372 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1373 Fix a broken link at perf/benchmark/README
  perf/benchmark/README.md
Labels: cla: yes, ok-to-test, size/XS

#1374 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#1377 Fixes to annotation generator
  cmd/annotations_prep/main.go
Labels: cla: yes, size/L

#1375 Update to golang 1.16
  docker/build-tools/Dockerfile
Labels: cla: yes, size/L

#1378 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1379 Fix custom variable names with annotation generator
  cmd/annotations_prep/main.go
Labels: cla: yes, size/XS

#1380 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1381 Fix accidental /gobin removal
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#1383 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1385 cue-gen: make CRD schema creation faster
  cmd/cue-gen/build.go
  cmd/cue-gen/genoapi.go
Labels: cla: yes, size/S

#1387 Update gogo proto to 1.3.2
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1389 Update go.mod to use gogo/protobuf v1.3.2
  go.mod
  go.sum
Labels: cla: yes, size/S

#1390 Add tsan instrumented libcxx build to proxy build tools.
  docker/build-tools/Dockerfile
  docker/build-tools/proxy-tsan-instrumented-libcxx.sh
Labels: cla: yes, size/M

#1391 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1388 Make protoc plugins less sensative to inputs
  cmd/protoc-gen-deepcopy/main.go
  cmd/protoc-gen-jsonshim/main.go
Labels: cla: yes, size/S

#1392 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1386 [release-1.7] Update version of LLVM used
  docker/build-tools/Dockerfile.centos
Labels: cla: yes, release-notes-none, size/XS

#1394 update kubetest2 version
  docker/build-tools/Dockerfile
Labels: cla: yes, ok-to-test, size/XS

#1384 Add missing protocol mode setting from configs/istio/none_tcp/latency.yaml
  perf/benchmark/configs/istio/none_tcp/latency.yaml
Labels: cla: yes, ok-to-test, size/XS

#1395 [release-1.8] update kubetest2 version
  docker/build-tools/Dockerfile
Labels: cla: yes, release-notes-none, size/XS

#1397 [release-1.9] update build image for 1.9
  CODEOWNERS
  common/Makefile.common.mk
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/XS

#1400 Automator: update common-files@release-1.9 in istio/tools@release-1.9
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1402 run UPDATE_BRANCH=release-1.9 make update-common
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#1393 Make docs plugin behave more like other plugins
  cmd/protoc-gen-docs/htmlGenerator.go
  cmd/protoc-gen-docs/main.go
  pkg/protomodel/frontMatter.go
Labels: cla: yes, size/M

#1403 Automator: update common-files@release-1.9 in istio/tools@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1404 run UPDATE_BRANCH=release-1.9 make update-common
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#1408 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1409 Update docs plugin to output to correct directory
  cmd/protoc-gen-docs/htmlGenerator.go
Labels: cla: yes, size/M

#1410 Pin kuberntes/test-infra version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1399 [release-1.7] update kubetest2 version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1412 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#1413 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#1414 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1415 Cleanup cached gcloud files
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1416 Automator: update common-files@master in istio/tools@master
  .gitattributes
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1417 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1418 Update kubetest2 to the latest version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1419 [release-1.9] Pin kuberntes/test-infra version
  docker/build-tools/Dockerfile
Labels: cla: yes, release-notes-none, size/XS

#1420 Automator: update common-files@release-1.9 in istio/tools@release-1.9
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#1422 Automator: update common-files@release-1.8 in istio/tools@release-1.8
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/L

#1423 Remove fortio from docker container
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1421 Bump kind version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1424 Add buf to build container
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1425 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1426 Automator: update common-files@release-1.7 in istio/tools@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1427 Update to Golang 1.16rc1
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1429 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1430 [release-1.9] Manual cherrypick of #1423 (remove fortio) and #1427 (golang 1.16rc1)
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS
