Repository istio/tools, pull requests merged in 2021-10, with the labels that each got.

#1714 Update kubetest2 to the latest version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1715 Remove iptables workaround
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/XS

#1713 Update protoc
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1716 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1717 Update clang to 12.0.1
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#1719 Update go to 1.17.1
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1718 cue-gen: do not panic when package does not have `.`
  cmd/cue-gen/build.go
Labels: cla: yes, size/XS

#1720 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1721 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: cla: yes, size/S, auto-merge, release-notes-none

#1728 Automator: update common-files@release-1.11 in istio/tools@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1731 [release-1.11] update gcloud SDK to the newest version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS, release-notes-none
