Repository istio/tools, pull requests merged in 2021-09, with the labels that each got.

#1687 fixed issues for generation of releasenotes
  cmd/gen-release-notes/README.md
  cmd/gen-release-notes/main.go
Labels: cla: yes, size/XS

#1688 Revert "fixed issues for generation of releasenotes"
  cmd/gen-release-notes/README.md
  cmd/gen-release-notes/main.go
Labels: cla: yes, size/XS

#1689 Update goc replacing use of deprecated go/loader
  cmd/goc/instrument.go
Labels: cla: yes, size/M

#1690 update gcloud SDK to the newest version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1691 Update gh to latest 2.0.0. Also add less as a dependency.
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS, cherrypick/release-1.9, cherrypick/release-1.10, cherrypick/release-1.11

#1692 [release-1.11] Update gh to latest 2.0.0. Also add less as a dependency.
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS, release-notes-none

#1695 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1696 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1694 Manual cherry-pick of 1691, update gh
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1697 Update containerd to 1.4.4
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1693 Manual cherry-pick of #1691, update gh
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1698 Automator: update common-files@release-1.10 in istio/tools@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1700 Update Golang to 1.16.8
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS, cherrypick/release-1.10, cherrypick/release-1.11

#1702 [release-1.11] Update Golang to 1.16.8
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS, release-notes-none

#1701 [release-1.10] Update Golang to 1.16.8
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS, release-notes-none

#1699 Add docs evaluation tooling
  cmd/evaluate-docs/README.md
  cmd/evaluate-docs/main.go
  cmd/evaluate-docs/scorer.go
  cmd/evaluate-docs/scorer_hits.go
Labels: cla: yes, size/L

#1703 Update shellcheck to 0.7.2
  docker/build-tools/Dockerfile
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/XS

#1704 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1705 Automator: update common-files@release-1.9 in istio/tools@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1706 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1707 Revert "Update shellcheck to 0.7.2"
  docker/build-tools/Dockerfile
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/XS

#1708 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1710 Automator: update common-files@release-1.11 in istio/tools@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1711 Automator: update common-files@release-1.10 in istio/tools@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1709 Adding cosign to build-tools
  docker/build-tools/Dockerfile
  docker/build-tools/build-and-push.sh
Labels: cla: yes, size/S
