Repository istio/tools, pull requests merged in 2021-12, with the labels that each got.

#1768 Update go-junit-report to the new commit
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1772 drain before response.Body.Close()
  isotope/service/pkg/srv/executable.go
Labels: cla: yes, size/XS

#1769 [release-1.11] Update go-junit-report to the new commit
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1770 [release-1.10] Update go-junit-report to the new commit
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1771 [release-1.12] Update go-junit-report to the new commit
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1774 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1775 Revert "[release-1.11] Update go-junit-report to the new commit"
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1776 include DNS_CAPTURE in stability test
  perf/istio-install/istioctl_profiles/long-running.yaml
Labels: cla: yes, size/XS

#1777 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1778 Automator: update common-files@release-1.12 in istio/tools@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#1773 [release-1.9] Update go-junit-report to the new commit
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1780 [release-1.11] Update to golang 1.16.11
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1779 Update go to 1.17.4
  docker/build-tools/Dockerfile
Labels: cla: yes, cherrypick/release-1.12

#1784 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1783 [release-1.12] Update go to 1.17.4
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#1785 Update to Golang 1.17.5
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.12

#1786 Bump golang to 1.16.12
  docker/build-tools/Dockerfile
Labels: size/XS

#1788 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1787 [release-1.12] Update to Golang 1.17.5
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#1789 Fork 2 gogo-based protoc tools to support golang protobuf
  cmd/protoc-gen-golang-deepcopy/Makefile
  cmd/protoc-gen-golang-deepcopy/README.md
  cmd/protoc-gen-golang-deepcopy/main.go
  cmd/protoc-gen-golang-deepcopy/test/Makefile
  cmd/protoc-gen-golang-deepcopy/test/deepcopy_test.go
  cmd/protoc-gen-golang-deepcopy/test/generated/types.pb.go
  cmd/protoc-gen-golang-deepcopy/test/generated/types_deepcopy.gen.go
  cmd/protoc-gen-golang-deepcopy/test/types.proto
  cmd/protoc-gen-golang-jsonshim/Makefile
  cmd/protoc-gen-golang-jsonshim/README.md
  cmd/protoc-gen-golang-jsonshim/main.go
  cmd/protoc-gen-golang-jsonshim/test/Makefile
  cmd/protoc-gen-golang-jsonshim/test/external.proto
  cmd/protoc-gen-golang-jsonshim/test/generated/external.pb.go
  cmd/protoc-gen-golang-jsonshim/test/generated/external_json.gen.go
  cmd/protoc-gen-golang-jsonshim/test/generated/types.pb.go
  cmd/protoc-gen-golang-jsonshim/test/generated/types_json.gen.go
  cmd/protoc-gen-golang-jsonshim/test/jsonshim_test.go
  cmd/protoc-gen-golang-jsonshim/test/types.proto
  go.mod
Labels: size/XL

#1792 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1793 Automator: update common-files@release-1.12 in istio/tools@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1790 [release-1.11] Update go-junit-report to the new commit
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#1794 Update to use latest code generation tools from k8s
  docker/build-tools/Dockerfile
Labels: size/XS

#1795 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1796 Update kubectl to 1.23.1
  docker/build-tools/Dockerfile
Labels: size/XS

#1797 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1798 mitigate log4j vuln in adservice
  upgrade_downgrade/templates/boutique/k8s-adservice.yaml
Labels: size/XS
