Repository istio/tools, pull requests merged in 2021-03, with the labels that each got.

#1456 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1458 fix dockerfile lints
  Makefile.core.mk
  docker/build-tools/Dockerfile
  docker/build-tools/Dockerfile.centos
  perf/docker/Dockerfile.rabbitmq
  perf/docker/Dockerfile.redis
  perf/load/auto-mtls/Dockerfile
Labels: cla: yes, size/M

#1457 Revert "Revert cue-gen move to v1, move back to v1beta1 (#1138)"
  cmd/cue-gen/build.go
  cmd/cue-gen/crd.go
  cmd/cue-gen/genoapi.go
  cmd/cue-gen/test/crdgen_test.go
  cmd/cue-gen/test/generated/kubernetes/customresourcedefinitions.gen.yaml
Labels: cla: yes, size/L

#1459 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1460 fix manifests lint
  Makefile.core.mk
  isotope/runner/resources/helm-service-account.yaml
  perf/benchmark/Chart.yaml
  perf/load/Chart.yaml
  perf/load/auto-mtls/Chart.yaml
  perf/load/auto-mtls/templates/config-changer.yaml
  perf/load/loadclient/Chart.yaml
  perf/load/pilot/Chart.yaml
  perf/load/templates/config-changer.yaml
  perf/load/templates/h2upgrade.yaml
  perf/other/multicluster-vpc/reviews-v3.yaml
  perf/security/sds-tests/workload-sds/Chart.yaml
  perf/security/sds-tests/workload-sds/templates/workload_rotate.yaml
  perf/security/workload-deployments/Chart.yaml
  perf/security/workload-deployments/templates/httpbin_template.yaml
  perf/stability/alertmanager/Chart.yaml
  perf/stability/alertmanager/templates/kube_state_metrics.yaml
  perf/stability/canary-upgrader/Chart.yaml
  perf/stability/canary-upgrader/templates/canary-upgrader-cron.yaml
  perf/stability/gateway-bouncer/templates/bouncer.yaml
  perf/stability/gateway-bouncer/templates/fortio-client.yaml
  perf/stability/gateway-bouncer/templates/fortio-server.yaml
  perf/stability/gateway-bouncer/templates/ingress.yaml
  perf/stability/gateway-bouncer/templates/pilot.yaml
  perf/stability/graceful-shutdown/Chart.yaml
  perf/stability/graceful-shutdown/templates/redeployer-cron.yaml
  perf/stability/http10/Chart.yaml
  perf/stability/intermediary/Chart.yaml
  perf/stability/istio-chaos-partial/Chart.yaml
  perf/stability/istio-chaos-partial/templates/chaos-cron.yaml
  perf/stability/istio-chaos-total/Chart.yaml
  perf/stability/istio-chaos-total/templates/chaos-cron.yaml
  perf/stability/istio-upgrader/Chart.yaml
  perf/stability/istio-upgrader/templates/redeployer-cron.yaml
  perf/stability/logs-checker/Chart.yaml
  perf/stability/logs-checker/templates/check_k8s_logs.yaml
  perf/stability/looper/Chart.yaml
  perf/stability/looper/templates/client.yaml
  perf/stability/multicluster-vpn/Chart.yaml
  perf/stability/mysql/Chart.yaml
  perf/stability/mysql/templates/client.yaml
  perf/stability/rabbitmq/Chart.yaml
  perf/stability/rabbitmq/templates/rabbitmq.yaml
  perf/stability/redis/Chart.yaml
  perf/stability/redis/templates/redis.yaml
  perf/stability/sds-certmanager/templates/certmanager.yaml
  perf/stability/sds-certmanager/templates/fortio-client.yaml
  perf/stability/sds-certmanager/templates/fortio-server.yaml
  perf/stability/sds-certmanager/templates/ingress.yaml
  perf/stability/sds-certmanager/templates/pilot.yaml
  setup/ipv6/calico.yaml
Labels: cla: yes, size/L

#1462 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1461 Attempt to fix automator
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1465 Update to golang 1.16.1
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1466 Update Golang to 1.16.2 and golangci-lint to 1.38.0
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1467 [release-1.9] Update Golang to 1.15.10
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1468 Fixup lint error for new golangci
  cmd/goc/instrument.go
  go.mod
  go.sum
Labels: cla: yes, size/XS

#1469 Automator: update common-files@release-1.9 in istio/tools@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1470 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1471 add prestop to service graph
  cmd/goc/instrument.go
  isotope/service/Dockerfile
  perf/load/bootstrap-vm.sh
  perf/load/templates/service-graph.gen.yaml
  perf/load/values.yaml
Labels: cla: yes, size/S

#1473 Update kubetest2 to the latest to include the fix in https://github.com/kubernetes-sigs/kubetest2/pull/115
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS
