Repository istio/tools, pull requests merged in 2021-02, with the labels that each got.

#1431 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1433 Fix local perf dir
  perf/benchmark/runner/runner.py
Labels: cla: yes, ok-to-test, size/XS

#1435 Update kubectl to the latest version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1436 [release-1.9] Move back to Golang 1.15.7 - 1.16 not released
  docker/build-tools/Dockerfile
Labels: cla: yes, size/L

#1437 Automator: update common-files@release-1.9 in istio/tools@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1438 ignore when process already dead
  perf/benchmark/run_benchmark_job.sh
Labels: cherrypick/release-1.8, cherrypick/release-1.9, cla: yes

#1439 [release-1.8] ignore when process already dead
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, release-notes-none, size/XS

#1432 Add VM test
  perf/load/bootstrap-vm.sh
  perf/load/common.sh
  perf/load/templates/service-graph.gen.yaml
  perf/load/values.yaml
Labels: cla: yes, size/L

#1441 [release-1.8] Update Golang to 1.15.8
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1442 Automator: update common-files@release-1.8 in istio/tools@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1443 Update kubectl to the latest version (#1435)
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1440 [release-1.9] ignore when process already dead
  perf/benchmark/run_benchmark_job.sh
Labels: cla: yes, release-notes-none, size/XS

#1444 bump perf dashboard page to 1.9
  perf_dashboard/docker-compose.yml
  perf_dashboard/dockerfile
Labels: cla: yes, size/XS

#1446 Ad fmt to gen to check go and python formatting
  Makefile.core.mk
  cmd/cue-gen/crd.go
  cmd/cue-gen/genoapi.go
  cmd/cue-gen/schema_visitor.go
  cmd/cue-gen/test/crdgen_test.go
  cmd/envvarlinter/envvar_test.go
  cmd/gen-release-notes/main.go
  cmd/gen-release-notes/note.go
  cmd/goc/main.go
  cmd/kubetype-gen/generators/register.go
  cmd/kubetype-gen/generators/types.go
  cmd/kubetype-gen/main.go
  cmd/kubetype-gen/metadata/metadata.go
  cmd/kubetype-gen/scanner/scanner.go
  cmd/license-lint/collector.go
  cmd/license-lint/main.go
  cmd/protoc-gen-deepcopy/deepcopy/plugin.go
  cmd/protoc-gen-docs/htmlGenerator.go
  cmd/protoc-gen-jsonshim/test/jsonshim_test.go
  cmd/testlinter/e2etest_lint_test.go
  cmd/testlinter/integtest_lint_test.go
  cmd/testlinter/unittest_lint_test.go
  perf/benchmark/security/generate_policies/generate_policies.go
  perf/benchmark/security/generate_policies/jwt.go
  perf/stability/looper/main.go
  pkg/checker/checker.go
Labels: cla: yes, size/L

#1434 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/S

#1447 Bump golang to 1.16
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1448 Bump golangci-lint version
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1449 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1450 Update various build tools
  docker/build-tools/Dockerfile
Labels: cla: yes, size/S

#1451 Use the same version of helm that is istio/istio dependency
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1452 Update golangcli-lint to 1.37.1
  docker/build-tools/Dockerfile
Labels: cla: yes, size/XS

#1453 Update kubetest2 version to include the change in https://github.com/kubernetes-sigs/kubetest2/pull/93
  cmd/envvarlinter/rules/no_os_env.go
  cmd/envvarlinter/rules_matcher.go
  cmd/testlinter/rules_matcher.go
  docker/build-tools/Dockerfile
  perf/benchmark/security/generate_policies/generate.go
Labels: cla: yes, size/S

#1454 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1455 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
