Repository istio/tools, pull requests merged in 2022-12, with the labels that each got.

#2260 Update Golang to 1.19.4
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.15, cherrypick/release-1.16

#2261 [release-1.14] Update to Go 1.18.9
  docker/build-tools/Dockerfile
Labels: size/XS

#2265 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2266 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2262 [release-1.15] Update Golang to 1.19.4
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2267 Automator: update common-files@release-1.15 in istio/tools@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2270 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2273 Add the gke-gcloud-auth-plugin to build-tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2274 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2275 Automator: update common-files@master in istio/tools@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2277 [release-1.15] Add the gke-gcloud-auth-plugin to build-tools
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2278 Update Hugo to match istio.io specified version
  docker/build-tools/Dockerfile
Labels: size/XS

#2279 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2280 Automator: update common-files@master in istio/tools@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2282 Automator: update common-files@release-1.15 in istio/tools@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2281 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2285 update docker and rust
  docker/build-tools/Dockerfile
Labels: size/XS

#2287 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2286 Update protobuf tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2289 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2284 dashboard: Refactor benchmark views.py
  perf_dashboard/benchmarks/views.py
Labels: size/L, ok-to-test

#2288 misc tool updates
  docker/build-tools/Dockerfile
Labels: size/XS

#2290 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2291 update containerd
  docker/build-tools/Dockerfile
  perf/benchmark/run_benchmark_job.sh
Labels: size/XS

#2292 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2283 [release-1.14] Add the gke-gcloud-auth-plugin to build-tools (#2273)
  docker/build-tools/Dockerfile
Labels: size/XS

#2293 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2294 update buf build
  docker/build-tools/Dockerfile
Labels: size/XS

#2295 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
