Repository istio/tools, pull requests merged in 2022-03, with the labels that each got.

#1884 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1887 Do not lint strings.Title
  cmd/annotations_prep/main.go
Labels: size/XS

#1885 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#1886 Update tooling to latest versions for cosign, trivy, containerd and d…
  docker/build-tools/Dockerfile
Labels: size/XS

#1889 Update the kubernetes/test-infra tools
  docker/build-tools/Dockerfile
Labels: size/XS

#1891 [release-1.12] Update golang
  docker/build-tools/Dockerfile
Labels: size/XS

#1892 [release-1.13] update golang
  docker/build-tools/Dockerfile
Labels: size/XS

#1890 [release-1.11] Use latest golang 1.16.15
  docker/build-tools/Dockerfile
Labels: size/XS

#1894 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1895 Automator: update common-files@release-1.13 in istio/tools@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1896 Automator: update common-files@release-1.12 in istio/tools@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1897 Automator: update common-files@release-1.11 in istio/tools@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1893 Bump to more recent git version
  docker/build-tools/Dockerfile
Labels: size/S

#1898 Add grpc protoc generator
  docker/build-tools/Dockerfile
Labels: size/XS

#1899 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1901 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1902 Update various tools
  docker/build-tools/Dockerfile
Labels: size/S

#1903 Issues with goimports with gci linter; revert
  docker/build-tools/Dockerfile
Labels: size/XS

#1904 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#1905 build-tools/Dockerfile: install zlib1g-dev
  docker/build-tools/Dockerfile
Labels: size/XS, ok-to-test

#1906 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#1908 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1911 Update scripts to pass linter
  perf/benchmark/run_benchmark_job.sh
  perf/istio-install/create_cluster.sh
  perf/load/run_servicegraph_job.sh
  perf/other/multicluster-vpc/setup.sh
  setup/ipv6/wait_for_control_plane.sh
  setup/stability-extra/multicluster-vpn/setup.sh
  vendors/google/install_asm.sh
Labels: size/S

#1912 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#1910 Install gogo and golang protobuf protoc plugins
  docker/build-tools/Dockerfile
Labels: size/XS

#1767 Disable intra-word emphasis in protoc-gen-docs
  cmd/protoc-gen-docs/htmlGenerator.go
  cmd/protoc-gen-docs/testdata/test1.proto
Labels: cla: yes, size/XS, ok-to-test

#1913 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1914 buf: upgrade to v1.1.0
  docker/build-tools/Dockerfile
Labels: size/XS

#1909 Switch to Golang 1.18.0
  docker/build-tools/Dockerfile
Labels: size/XS

#1915 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1916 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/L, auto-merge, release-notes-none

#1917 feat: add custom ingress svc name in env
  perf/load/common.sh
  perf/load/loadclient/setup_test.sh
Labels: size/S

#1918 Updating gcloud version to 377.0.0
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.13

#1919 Updating gcloud version to 377.0.0 (#1918)
  docker/build-tools/Dockerfile
Labels: size/XS

#1920 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1921 Update hugo to 0.95.0
  docker/build-tools/Dockerfile
Labels: size/XS

#1922 Update nodejs due to CVE
  docker/build-tools/Dockerfile
Labels: size/XS

#1923 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1924 Update kubetype to support golang/protobuf
  cmd/kubetype-gen/generators/types.go
Labels: size/S

#1925 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1928 Drop all gogo protobuf usage
  cmd/kubetype-gen/generators/types.go
  cmd/protoc-gen-deepcopy/Makefile
  cmd/protoc-gen-deepcopy/README.md
  cmd/protoc-gen-deepcopy/deepcopy/plugin.go
  cmd/protoc-gen-deepcopy/main.go
  cmd/protoc-gen-deepcopy/test/Makefile
  cmd/protoc-gen-deepcopy/test/deepcopy_test.go
  cmd/protoc-gen-deepcopy/test/generated/types.pb.go
  cmd/protoc-gen-deepcopy/test/generated/types_deepcopy.gen.go
  cmd/protoc-gen-deepcopy/test/types.proto
  cmd/protoc-gen-docs/htmlGenerator.go
  cmd/protoc-gen-golang-deepcopy/README.md
  cmd/protoc-gen-golang-deepcopy/test/Makefile
  cmd/protoc-gen-golang-deepcopy/test/deepcopy_test.go
  cmd/protoc-gen-golang-deepcopy/test/generated/types_deepcopy.gen.go
  cmd/protoc-gen-golang-jsonshim/README.md
  cmd/protoc-gen-golang-jsonshim/test/Makefile
  cmd/protoc-gen-golang-jsonshim/test/jsonshim_test.go
  cmd/protoc-gen-jsonshim/Makefile
  cmd/protoc-gen-jsonshim/README.md
  cmd/protoc-gen-jsonshim/jsonshim/plugin.go
  cmd/protoc-gen-jsonshim/main.go
  cmd/protoc-gen-jsonshim/test/Makefile
  cmd/protoc-gen-jsonshim/test/external.proto
  cmd/protoc-gen-jsonshim/test/generated/external.pb.go
  cmd/protoc-gen-jsonshim/test/generated/external_json.gen.go
  cmd/protoc-gen-jsonshim/test/generated/types.pb.go
  cmd/protoc-gen-jsonshim/test/generated/types_json.gen.go
  cmd/protoc-gen-jsonshim/test/jsonshim_test.go
  cmd/protoc-gen-jsonshim/test/types.proto
  docker/build-tools/Dockerfile
  go.mod
  go.sum
  licenses/istio.io/gogo-genproto/LICENSE
Labels: size/XXL

#1926 Bump FPM to pull in some deb fixes
  docker/build-tools/Dockerfile
Labels: size/S

#1931 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1933 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1934 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1935 Fix incorrect refactor of kubetype-gen
  cmd/kubetype-gen/generators/types.go
Labels: size/XS

#1936 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1937 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1938 Update a few tools: gh, hadolint, trivy
  docker/build-tools/Dockerfile
Labels: size/XS
