Repository istio/tools, pull requests merged in 2022-11, with the labels that each got.

#2199 Update kind and trivy
  docker/build-tools/Dockerfile
Labels: size/XS

#2200 Update to Go 1.19.3
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.15, cherrypick/release-1.16

#2205 [release-1.16] Update to Go 1.19.3
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2203 [release-1.14] Update go to 1.18.8 in release-1.14
  docker/build-tools/Dockerfile
Labels: size/XS

#2204 [release-1.15] Update to Go 1.19.3
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2206 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2207 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2198 Feature/add multinamespace multicluster
  isotope/README.md
  isotope/convert/README.md
  isotope/convert/cmd/graphviz.go
  isotope/convert/cmd/kubernetes.go
  isotope/convert/pkg/consts/consts.go
  isotope/convert/pkg/graph/script/concurrent_command_test.go
  isotope/convert/pkg/graph/script/request_command.go
  isotope/convert/pkg/graph/script/request_command_test.go
  isotope/convert/pkg/graph/script/script_test.go
  isotope/convert/pkg/graph/svc/marshal_test.go
  isotope/convert/pkg/graph/svc/service.go
  isotope/convert/pkg/graph/unmarshal.go
  isotope/convert/pkg/graph/unmarshal_test.go
  isotope/convert/pkg/kubernetes/fortio_client.go
  isotope/convert/pkg/kubernetes/kubernetes.go
  isotope/convert/pkg/kubernetes/rbac.go
  isotope/example-topologies/chain-2-services-different-cluster.yaml
  isotope/example-topologies/chain-2-services-different-namespace.yaml
  isotope/go.mod
  isotope/go.sum
  isotope/service/README.md
  isotope/service/main.go
  isotope/service/pkg/srv/executable.go
  isotope/service/pkg/srv/request.go
Labels: size/XL

#2208 Automator: update common-files@release-1.15 in istio/tools@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2209 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2210 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2211 Bump rust to 1.65.0
  docker/build-tools/Dockerfile
Labels: size/XS

#2212 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2213 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2214 Use shallow git clone
  docker/build-tools/Dockerfile
Labels: size/S, ok-to-test

#2216 docker: drop UPX
  docker/build-tools/Dockerfile
Labels: size/XS

#2217 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2219 Add back upx and do not compress helm
  docker/build-tools/Dockerfile
Labels: size/S

#2218 Update some tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2220 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2222 Update k8s bom utility
  docker/build-tools/Dockerfile
Labels: size/XS

#2223 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2221 [release-1.16] Update Hugo to match istio.io
  docker/build-tools/Dockerfile
Labels: size/XS

#2224 Drop UPX properly this time
  docker/build-tools/Dockerfile
Labels: size/XS

#2225 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2226 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2228 Update nodejs to latest LTS version
  docker/build-tools/Dockerfile
Labels: size/XS

#2229 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#2230 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#2231 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2233 benchmark: fix create_cluster.sh
  perf/istio-install/create_cluster.sh
Labels: size/M, ok-to-test

#2234 Fix file exclusion if flag not set in cue-gen
  cmd/cue-gen/genoapi.go
Labels: size/S, ok-to-test

#2235 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2237 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#2236 Update various tools
  docker/build-tools/Dockerfile
Labels: size/S

#2240 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2243 Move cargo bin to /usr/bin
  docker/build-tools/Dockerfile
Labels: size/XS

#2247 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2239 benchmark: change dash to underscore in directory name
  perf/benchmark/configs/istio/ext_authz/README.md
  perf/benchmark/configs/istio/ext_authz/ext-authz_patch.yaml
  perf/benchmark/configs/istio/ext_authz/installation.yaml
  perf/benchmark/configs/istio/ext_authz/policy.yaml
  perf/benchmark/configs/istio/ext_authz/postrun.sh
  perf/benchmark/configs/istio/ext_authz/prerun.sh
  perf/benchmark/configs/istio/ext_authz/results/p50.png
  perf/benchmark/configs/istio/ext_authz/results/p90.png
  perf/benchmark/configs/istio/ext_authz/results/p99.png
  perf/benchmark/configs/istio/ext_authz/results/p999.png
Labels: size/XS, ok-to-test

#2250 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#2249 update various tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2252 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/fix_copyright_banner.sh
Labels: size/XS, auto-merge, release-notes-none

#2253 Update docker and containerd
  docker/build-tools/Dockerfile
Labels: size/XS

#2254 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2255 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#2248 chore: fix root run dev container
  docker/build-tools/docker-entrypoint.sh
Labels: size/XS

#2256 Update a few tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2257 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2238 Fix performance dashboard build & Upgrade Django version
  perf_dashboard/Dockerfile
  perf_dashboard/Makefile
  perf_dashboard/analyze_perf_issues/templates/analyze_perf_issues.html
  perf_dashboard/analyze_perf_issues/urls.py
  perf_dashboard/artifacts/templates/artifact.html
  perf_dashboard/artifacts/urls.py
  perf_dashboard/benchmarks/templates/cpu_vs_conn.html
  perf_dashboard/benchmarks/templates/cpu_vs_qps.html
  perf_dashboard/benchmarks/templates/flame_graph.html
  perf_dashboard/benchmarks/templates/latency_vs_conn.html
  perf_dashboard/benchmarks/templates/latency_vs_qps.html
  perf_dashboard/benchmarks/templates/mem_vs_conn.html
  perf_dashboard/benchmarks/templates/mem_vs_qps.html
  perf_dashboard/benchmarks/templates/micro_benchmarks.html
  perf_dashboard/benchmarks/urls.py
  perf_dashboard/history/templates/history.html
  perf_dashboard/history/urls.py
  perf_dashboard/perf_dashboard/urls.py
  perf_dashboard/regressions/apps.py
  perf_dashboard/regressions/templates/cur_regression.html
  perf_dashboard/regressions/templates/master_regression.html
  perf_dashboard/regressions/templates/monitoring_overview.html
  perf_dashboard/regressions/urls.py
  perf_dashboard/requirements.txt
  perf_dashboard/templates/base.html
  perf_dashboard/templates/index.html
Labels: size/L, ok-to-test
