Repository istio/tools, pull requests merged in 2022-07, with the labels that each got.

#2050 Update toolchain dependencies
  docker/build-tools/Dockerfile
Labels: size/S

#2051 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2052 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#2054 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#2053 Update to Go 1.18.4
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.14

#2055 [release-1.14] Update Go to 1.18.4
  docker/build-tools/Dockerfile
Labels: size/XS

#2057 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2059 [release-1.13] Update golang to 1.17.12
  docker/build-tools/Dockerfile
Labels: size/XS

#2058 Bump kind version to support running 1.25 images
  docker/build-tools/Dockerfile
Labels: size/XS

#2060 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2062 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#2063 Automator: update common-files@release-1.13 in istio/tools@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2065 update kubetest2 version sha (#2013)
  docker/build-tools/Dockerfile
Labels: size/XS

#2066 update kubetest2 version sha (#2013)
  docker/build-tools/Dockerfile
Labels: size/XS

#2067 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2068 Bump golangci-lint to v1.47.2
  docker/build-tools/Dockerfile
Labels: size/XS

#2071 Automator: update common-files@release-1.13 in istio/tools@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2070 Fix linter error in go code
  cmd/protoc-gen-docs/htmlGenerator.go
  cmd/protoc-gen-golang-jsonshim/test/jsonshim_test.go
  common/.commonfiles.sha
  common/config/.golangci.yml
  perf/benchmark/security/generate_policies/generate_policies.go
Labels: size/M

#2072 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2074 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2075 Update some tools
  docker/build-tools/Dockerfile
Labels: size/S

#2076 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2077 update gcloud version to 393.0.0
  docker/build-tools/Dockerfile
Labels: size/XS

#2079 update gcloud version to 393.0.0 (#2077)
  docker/build-tools/Dockerfile
Labels: size/XS

#2080 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2081 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2082 Update docs to trigger arm64 build
  docker/build-tools/Dockerfile
Labels: size/XS

#2083 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2084 license-lint: remove redundant license files
  cmd/license-lint/collector.go
Labels: size/XS
