Repository istio/tools, pull requests merged in 2022-05, with the labels that each got.

#1980 Automator: update common-files@master in istio/tools@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1981 Ignore deleted files when using gh pr
  cmd/gen-release-notes/main.go
Labels: size/XS

#1982 Updating gcloud version to 377.0.0
  docker/build-tools/Dockerfile
Labels: size/XS

#1986 [release-1.14] Ignore deleted files when using gh pr
  cmd/gen-release-notes/main.go
Labels: size/XS, release-notes-none

#1987 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/XS, auto-merge, release-notes-none

#1988 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1990 [release-1.13] Update to Golang 1.17.10
  docker/build-tools/Dockerfile
Labels: size/XS

#1989 Bump to kind 0.13.0
  docker/build-tools/Dockerfile
Labels: size/XS

#1992 Automator: update common-files@release-1.13 in istio/tools@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1993 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1994 Update bazelisk to match core builder
  docker/build-tools/Dockerfile.centos
Labels: size/XS

#1995 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1997 Add required python modules for centos
  docker/build-tools/Dockerfile.centos
Labels: size/XS

#1998 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1999 Update some tool versions
  docker/build-tools/Dockerfile
Labels: size/S

#2000 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1996 Bump golangci-lint to 1.46.1
  docker/build-tools/Dockerfile
Labels: size/XS

#2001 Revert kind to 0.13.0
  docker/build-tools/Dockerfile
Labels: size/XS

#2002 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1991 [release-1.12] Update Golang to 1.17.10
  docker/build-tools/Dockerfile
Labels: size/XS

#2003 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
Labels: size/XS, auto-merge, release-notes-none

#2005 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#2007 Automator: update common-files@release-1.12 in istio/tools@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2009 Upgrade Node.js, TypeScript, TSLint, Babel, etc. in `build-tools`
  docker/build-tools/Dockerfile
Labels: size/M, ok-to-test

#2008 Fix various typos in the source code
  bin/README.md
  cmd/kubetype-gen/README.md
  docker/build-tools/Dockerfile
  perf/istio-install/README.md
  perf/load/auto-mtls/README.md
  perf/security/sds-tests/egress-sds/README.md
  perf/security/sds-tests/ingress-sds/README.md
  perf/security/sds-tests/workload-sds/README.md
  perf/stability/control-plane/README.md
Labels: size/M, ok-to-test
