Repository istio/tools, pull requests merged in 2022-06, with the labels that each got.

#2010 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#2011 Add a stability test for WasmPlugin
  perf/stability/stability.mk
  perf/stability/wasm-extensions/Chart.yaml
  perf/stability/wasm-extensions/templates/client.yaml
  perf/stability/wasm-extensions/templates/server.yaml
  perf/stability/wasm-extensions/templates/serviceaccount.yaml
  perf/stability/wasm-extensions/templates/wasm-configurator.yaml
  perf/stability/wasm-extensions/values.yaml
  perf/stability/wasm-extensions/wasm-extension.yaml
Labels: size/L

#2014 Update kind to 0.14.0
  docker/build-tools/Dockerfile
Labels: size/XS

#2016 [release-1.14] Update go to 1.18.3
  docker/build-tools/Dockerfile
Labels: size/XS

#2019 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2015 Update go to 1.18.3
  docker/build-tools/Dockerfile
Labels: size/XS

#2020 remove stale auto-qual-test directory
  perf/auto-qual-test/README.md
  perf/auto-qual-test/base/clusterrolebinding.yaml
  perf/auto-qual-test/base/deploy_latest_daily.sh
  perf/auto-qual-test/base/deploy_updater.sh
  perf/auto-qual-test/base/kustomization.yaml
  perf/auto-qual-test/base/qual-test-update-job.yaml
  perf/auto-qual-test/base/qual-test-version.yaml
  perf/auto-qual-test/base/redeploy.sh
  perf/auto-qual-test/base/serviceaccount.yaml
  perf/auto-qual-test/overlays/v1.2/kustomization.yaml
  perf/auto-qual-test/overlays/v1.2/qual-test-version-1.2.yaml
Labels: size/L

#2021 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2022 Update some tools
  docker/build-tools/Dockerfile
Labels: size/S

#2023 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2025 Initial support for multi-architecture build-tools builds
  docker/build-tools/Dockerfile
  docker/build-tools/build-and-push.sh
Labels: size/M

#2026 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2027 trim build-tools image a bit
  docker/build-tools/Dockerfile
Labels: size/XS

#2029 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#2030 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2028 Remove some old unused binaries
  docker/build-tools/Dockerfile
Labels: size/S

#2031 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2032 Allow MANIFEST_ARCH to be unset
  docker/build-tools/build-and-push.sh
Labels: size/XS

#2033 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2035 build-tools: support building with container
  docker/build-tools/build-and-push.sh
Labels: size/XS

#2036 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2037 Detect host MTU and use that as the docker MTU
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS

#2038 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2039 docker: mtu is a int, not a string
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS

#2042 [release-1.13] Manual cherry-pick of #2028
  docker/build-tools/Dockerfile
Labels: size/S

#2041 [release-1.14] Manual cherry-pick of #2028
  docker/build-tools/Dockerfile
Labels: size/S

#2017 [release-1.13] Update go to 1.17.11
  docker/build-tools/Dockerfile
Labels: size/XS

#2034 [1.14] Backport multi-arch changes
  docker/build-tools/Dockerfile
  docker/build-tools/build-and-push.sh
Labels: size/M

#2043 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2044 Automator: update common-files@release-1.13 in istio/tools@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2040 [release-1.12] Update Go to 1.17.11. Remove some tools.
  docker/build-tools/Dockerfile
Labels: size/S

#2045 Automator: update common-files@release-1.12 in istio/tools@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2046 build-tools: cache from existing image
  docker/build-tools/build-and-push.sh
Labels: size/S

#2048 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#2047 Update go modules
  go.mod
  go.sum
  licenses/cloud.google.com/go/compute/LICENSE
  licenses/github.com/googleapis/enterprise-certificate-proxy/LICENSE
  licenses/github.com/invopop/yaml/LICENSE
  licenses/github.com/pelletier/go-toml/v2/LICENSE
Labels: size/XL

#2049 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
