Repository istio/tools, pull requests merged in 2022-02, with the labels that each got.

#1849 Update bom to 0.2.2
  docker/build-tools/Dockerfile
Labels: size/XS

#1850 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1851 Update to buf `v1.0.0-rc12`
  docker/build-tools/Dockerfile
Labels: size/XS

#1853 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1854 [release-1.12] Always enable ipv6 sysctl
  docker/build-tools/prow-entrypoint.sh
Labels: size/S, release-notes-none

#1855 Automator: update common-files@release-1.12 in istio/tools@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1858 [release-1.13] Update golang linter
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#1861 Automator: update common-files@release-1.13 in istio/tools@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1863 Update to Golang 1.17.7
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.12, cherrypick/release-1.13

#1865 [release-1.13] Update to Golang 1.17.7
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#1867 Automator: update common-files@release-1.13 in istio/tools@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1868 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1869 bump perf to release 1.13
  perf_dashboard/docker-compose.yml
  perf_dashboard/dockerfile
Labels: cherrypick/release-1.13

#1864 [release-1.12] Update to Golang 1.17.7
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#1871 Automator: update common-files@release-1.12 in istio/tools@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1866 [release-1.11] Update golang1.16.14
  docker/build-tools/Dockerfile
Labels: size/XS

#1872 Automator: update common-files@release-1.11 in istio/tools@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1873 Remove legacy upgrade/downgrade jobs
  upgrade_downgrade/README.md
  upgrade_downgrade/common.sh
  upgrade_downgrade/fortio_utils.sh
  upgrade_downgrade/kind.sh
  upgrade_downgrade/run_upgrade_downgrade_test.sh
  upgrade_downgrade/templates/boutique/istio-manifests.yaml
  upgrade_downgrade/templates/boutique/k8s-adservice.yaml
  upgrade_downgrade/templates/boutique/k8s-cartservice.yaml
  upgrade_downgrade/templates/boutique/k8s-checkoutservice.yaml
  upgrade_downgrade/templates/boutique/k8s-currencyservice.yaml
  upgrade_downgrade/templates/boutique/k8s-emailservice.yaml
  upgrade_downgrade/templates/boutique/k8s-frontend.yaml
  upgrade_downgrade/templates/boutique/k8s-loadgenerator.yaml
  upgrade_downgrade/templates/boutique/k8s-paymentservice.yaml
  upgrade_downgrade/templates/boutique/k8s-productcatalogservice.yaml
  upgrade_downgrade/templates/boutique/k8s-recommendationservice.yaml
  upgrade_downgrade/templates/boutique/k8s-redis-cart.yaml
  upgrade_downgrade/templates/boutique/k8s-shippingservice.yaml
  upgrade_downgrade/templates/fortio-cli.yaml
  upgrade_downgrade/templates/fortio.yaml
  upgrade_downgrade/templates/gateway.yaml
  upgrade_downgrade/templates/iop-control-plane.yaml
  upgrade_downgrade/templates/iop-gateways.yaml
  upgrade_downgrade/test_dual_control_plane_upgrade_downgrade.sh
  upgrade_downgrade/test_dual_control_plane_upgrade_downgrade_boutique.sh
  upgrade_downgrade/test_upgrade_downgrade.sh
Labels: size/XXL

#1875 Add trailing newline before exit
  cmd/gen-release-notes/main.go
Labels: size/XS

#1876 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1877 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, auto-merge, release-notes-none

#1878 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#1879 Log total runtime in standard prow logger
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS

#1880 Automator: update common-files@release-1.12 in istio/tools@release-1.12
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#1881 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
