Repository istio/tools, pull requests merged in 2022-10, with the labels that each got.

#2156 Update Go to 1.18.7
  docker/build-tools/Dockerfile
Labels: size/XS

#2155 Update Go to 1.19.2
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.15

#2157 [release-1.15] Update Go to 1.19.2
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2158 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2160 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2161 Automator: update common-files@release-1.15 in istio/tools@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2163 Update tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2164 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2149 add ext-authz benchmark files
  perf/benchmark/configs/istio/ext-authz/README.md
  perf/benchmark/configs/istio/ext-authz/ext-authz_patch.yaml
  perf/benchmark/configs/istio/ext-authz/installation.yaml
  perf/benchmark/configs/istio/ext-authz/policy.yaml
  perf/benchmark/configs/istio/ext-authz/postrun.sh
  perf/benchmark/configs/istio/ext-authz/prerun.sh
  perf/benchmark/configs/istio/ext-authz/results/p50.png
  perf/benchmark/configs/istio/ext-authz/results/p90.png
  perf/benchmark/configs/istio/ext-authz/results/p99.png
  perf/benchmark/configs/istio/ext-authz/results/p999.png
Labels: size/L, ok-to-test

#2166 Fix failing test
  isotope/convert/pkg/graph/unmarshal_test.go
Labels: size/XS

#2168 markdown: move BlackFriday to goldmark
  cmd/gen-release-notes/main.go
  cmd/protoc-gen-docs/README.md
  cmd/protoc-gen-docs/htmlGenerator.go
  go.mod
  go.sum
  licenses/github.com/russross/blackfriday/v2/LICENSE.txt
  licenses/github.com/yuin/goldmark/LICENSE
  pkg/markdown/md.go
Labels: size/L

#2170 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#2169 proto-gen-doc: fix markdown render
  go.mod
  licenses/github.com/davecgh/go-spew/LICENSE
  licenses/github.com/pmezard/go-difflib/LICENSE
  licenses/github.com/stretchr/testify/LICENSE
  pkg/markdown/md.go
  pkg/markdown/md_test.go
  pkg/markdown/testdata/AnalysisMessageWeakSchema.input
  pkg/markdown/testdata/AnalysisMessageWeakSchema.output
  pkg/markdown/testdata/links.input
  pkg/markdown/testdata/links.output
  pkg/markdown/testdata/telemetry.input
  pkg/markdown/testdata/telemetry.output
Labels: size/L

#2171 Update some tool versions
  docker/build-tools/Dockerfile
Labels: size/XS

#2172 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#2173 Fix hadolint binary for the arm container
  docker/build-tools/Dockerfile
Labels: size/S

#2174 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2175 Update docker and gcloud
  docker/build-tools/Dockerfile
Labels: size/XS

#2176 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2152 Correct wrong description of QPS in doc
  perf/benchmark/README.md
Labels: size/XS, ok-to-test

#2177 Use google.golang.org/protobuf/proto as proto package
  cmd/protoc-gen-golang-deepcopy/main.go
  cmd/protoc-gen-golang-deepcopy/test/generated/types.pb.go
  cmd/protoc-gen-golang-deepcopy/test/generated/types_deepcopy.gen.go
Labels: size/XS, ok-to-test

#2181 Container test failing due to dependency issue in CentOS
  docker/build-tools/Dockerfile.centos
Labels: size/XS

#2182 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/XS, auto-merge, release-notes-none

#2183 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/XS, auto-merge, release-notes-none

#2179 [release-1.16] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  docker/build-tools/build-and-push.sh
Labels: size/XS, release-notes-none

#2187 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#2186 [master] Container test failing due to dependency issue in CentOS
  docker/build-tools/Dockerfile.centos
Labels: size/XS, release-notes-none

#2184 Add tooling support for rust/cargo
  docker/build-tools/Dockerfile
Labels: size/M

#2189 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2190 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: size/XS, auto-merge, release-notes-none

#2178 Update docker due to CVE
  docker/build-tools/Dockerfile
Labels: size/XS

#2192 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2185 [release-1.16] Revert the skip-broken for Centos once upstream is fixed
  docker/build-tools/Dockerfile.centos
Labels: cherrypick/master

#2193 [master] Revert the skip-broken for Centos once upstream is fixed
  docker/build-tools/Dockerfile.centos
Labels: size/XS, release-notes-none

#2194 Update various tools
  docker/build-tools/Dockerfile
Labels: size/S

#2195 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
