Repository istio/tools, pull requests merged in 2022-09, with the labels that each got.

#2114 Update Hugo to latest 0.101.0
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.15

#2123 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2124 [release-1.15] Manual cherry-pick of #2114 - Update Hugo
  docker/build-tools/Dockerfile
Labels: size/XS

#2125 Automator: update common-files@release-1.15 in istio/tools@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2126 Update kind
  docker/build-tools/Dockerfile
Labels: size/XS

#2129 [release-1.14] Update to Go 1.18.6
  docker/build-tools/Dockerfile
Labels: size/XS

#2128 Update to Go 1.19.1
  docker/build-tools/Dockerfile
Labels: cherrypick/release-1.15

#2131 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2132 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2130 [release-1.15] Update to Go 1.19.1
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2133 Automator: update common-files@release-1.15 in istio/tools@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2134 A few minor tools updates
  docker/build-tools/Dockerfile
Labels: size/XS

#2135 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2137 Print errors to os.Stderr
  cmd/license-lint/main.go
Labels: size/S, ok-to-test

#2138 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2139 Update buf
  docker/build-tools/Dockerfile
Labels: size/XS

#2140 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2136 fix release qualification test
  perf/stability/alertmanager/templates/alertmanager-webhook.yaml
  perf/stability/alertmanager/values.yaml
  perf/stability/long_running.sh
Labels: size/M

#2142 Update tools
  docker/build-tools/Dockerfile
Labels: size/S

#2064 (isotope) feat: Simulated error-rate + multi-arch docker image
  isotope/service/Dockerfile
  isotope/service/pkg/srv/graph.go
  isotope/service/pkg/srv/handler.go
Labels: size/M, ok-to-test

#2145 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#2146 Use istio-injection=enabled as default for stability test
  perf/load/common.sh
Labels: size/XS

#2147 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/S, auto-merge, release-notes-none

#2148 Update several tools, notably kind 0.16.0
  docker/build-tools/Dockerfile
Labels: size/S

#2150 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2153 Update several tools including Hugo version which istio.io just moved to
  docker/build-tools/Dockerfile
Labels: size/XS

#2154 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
