Repository istio/tools, pull requests merged in 2022-04, with the labels that each got.

#1939 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1940 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1941 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1930 Upgrade docker, containerd and explicitly set version of go
  docker/build-tools/Dockerfile
Labels: size/S

#1942 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1943 Fix Docker credential handling on Macs
  docker/build-tools/docker-entrypoint.sh
Labels: size/S

#1944 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1946 Update common-files (with new linter) and lint fixes
  cmd/cue-gen/build.go
  cmd/license-lint/analysis.go
  common/.commonfiles.sha
  common/config/.golangci.yml
  pkg/protomodel/frontMatter.go
Labels: size/M

#1947 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#1949 [release-1.13] Update Golang to 1.17.9
  docker/build-tools/Dockerfile
Labels: size/XS

#1948 Update to Golang 1.18.1 and Trivy 0.25.3
  docker/build-tools/Dockerfile
Labels: size/XS

#1951 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1950 [release-1.12] Update Golang to 1.17.9
  docker/build-tools/Dockerfile
Labels: size/XS

#1952 Automator: update common-files@release-1.13 in istio/tools@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1953 Automator: update common-files@release-1.12 in istio/tools@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1954 Update some tools - also fix git warning
  docker/build-tools/Dockerfile
Labels: size/XS

#1955 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1956 Update build-tools to ubuntu:jammy
  docker/build-tools/Dockerfile
Labels: size/S

#1958 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1957 update build image for release-1.14
  common/Makefile.common.mk
  docker/build-tools/build-and-push.sh
Labels: size/XS

#1960 [release-1.14] Automated branching step 4
  CODEOWNERS
Labels: size/XS, release-notes-none

#1961 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#1962 [release-1.14] Update script comment to force image build
  docker/build-tools/build-and-push.sh
Labels: size/XS

#1963 [release-1.14] Move UPDATE_BRANCH to release-1.14
  common/Makefile.common.mk
Labels: size/XS

#1965 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1964 Docker not start as part of prow jobs
  docker/build-tools/Dockerfile
Labels: size/XS

#1966 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1967 [release-1.14] Docker not start as part of prow jobs
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#1968 Always run gcloud auth configure-docker in prow entrypoint
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS

#1971 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1972 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, auto-merge, release-notes-none

#1973 added analysis in readme
  perf/stability/control-plane/README.md
  perf/stability/control-plane/testdata/cpu_load.png
  perf/stability/control-plane/testdata/memory_usage.png
  perf/stability/control-plane/testdata/xds_req_size.png
Labels: size/S

#1974 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1976 Revert "[release-1.14] Docker not start as part of prow jobs"
  docker/build-tools/Dockerfile
Labels: size/XS

#1978 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/S, auto-merge, release-notes-none

#1977 [release-1.14] Revert updating build-tools to ubuntu:jammy
  docker/build-tools/Dockerfile
Labels: size/S

#1979 Automator: update common-files@release-1.14 in istio/tools@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
