Repository istio/tools, pull requests merged in 2022-01, with the labels that each got.

#1800 Run go mod tidy -go=1.17
  go.mod
Labels: size/L

#1802 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#1803 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1804 Move to containerd
  perf/istio-install/README.md
  perf/istio-install/create_cluster.sh
  perf/istio-install/gke_cluster_resources/nodepool.yaml
  perf/other/multicluster-vpc/setup.sh
Labels: size/S

#1805 Update to Golang 1.17.6
  docker/build-tools/Dockerfile
Labels: size/XS

#1806 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1807 Fix outdated addons
  perf/istio-install/addons/cert-manager.yaml
  perf/istio-install/base/files/crds.yaml
  perf/istio-install/base/templates/prometheus-install.yaml
  perf/istio-install/base/templates/prometheus-operator.yaml
  perf/istio-install/setup_istio.sh
Labels: size/XXL

#1808 Fix an issue when using gen-release-notes manually
  cmd/gen-release-notes/main.go
Labels: size/XS

#1809 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1810 feat: support custom injection label
  perf/load/auto-mtls/setup.sh
  perf/load/common.sh
  perf/load/loadclient/setup_test.sh
  perf/load/pilot/setup.sh
  perf/load/setup_large_test.sh
Labels: size/S

#1812 chore: turn README to README.md for better format
  perf/load/loadclient/README.md
  perf/load/rotate/README.md
Labels: size/XS

#1811 chore: remove mixer config as its deprecation
  perf/load/values-istio-auth.yaml
Labels: size/XS

#1813 feat: support custom PERF_NAMESPACE_DELAY when starting up
  perf/load/common.sh
  perf/load/setup_large_test.sh
Labels: size/XS

#1816 chore: remove config in istio 1.5 or prior
  perf/load/templates/strict.yaml
Labels: size/XS

#1815 feat: support custom request cpu/memory of istio/proxy
  perf/load/templates/service-graph.gen.yaml
  perf/load/values.yaml
Labels: size/XS

#1817 build centos clang+llvm in cloud build
  clang-toolchain/Dockerfile
  clang-toolchain/README.md
  clang-toolchain/build_clang_llvm.sh
  clang-toolchain/cloudbuild.yaml
  clang-toolchain/install_build_deps.sh
Labels: size/L

#1818 bump to release 1.12
  perf_dashboard/docker-compose.yml
  perf_dashboard/dockerfile
Labels: size/XS

#1819 build clang: fix python version
  clang-toolchain/build_clang_llvm.sh
Labels: size/XS

#1820 centos uses clang+llvm 12
  docker/build-tools/Dockerfile.centos
Labels: size/S

#1821 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1822 Bump dependencies for 1/19
  go.mod
  go.sum
Labels: size/L

#1824 fix regression in centos build image
  docker/build-tools/Dockerfile.centos
Labels: size/XS

#1825 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1827 fix the wrong resource annotations name
  perf/benchmark/flame/README.md
Labels: size/XS, ok-to-test

#1826 update the image of proxy
  perf/benchmark/flame/README.md
Labels: size/XS, ok-to-test

#1830 Add k8s-sigs/bom to buildtools
  docker/build-tools/Dockerfile
Labels: size/XS

#1831 [release-1.13] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  docker/build-tools/build-and-push.sh
Labels: size/XS, release-notes-none

#1832 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1828 [release-1.12] Update go 1.17.6
  docker/build-tools/Dockerfile
Labels: size/XS

#1833 Automator: update common-files@release-1.12 in istio/tools@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1834 Automator: update common-files@release-1.13 in istio/tools@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1835 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#1836 Update helm to v3.8.0
  docker/build-tools/Dockerfile
Labels: size/XS

#1837 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1838 Update golang linter
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#1839 Bump versions for helm lint
  perf/auto-qual-test/base/qual-test-update-job.yaml
  perf/load/templates/config-changer.yaml
  perf/stability/canary-upgrader/templates/canary-upgrader-cron.yaml
  perf/stability/gateway-bouncer/templates/bouncer.yaml
  perf/stability/graceful-shutdown/templates/redeployer-cron.yaml
  perf/stability/istio-chaos-partial/templates/chaos-cron.yaml
  perf/stability/istio-chaos-total/templates/chaos-cron.yaml
  perf/stability/istio-upgrader/templates/redeployer-cron.yaml
  perf/stability/logs-checker/templates/check_k8s_logs.yaml
  perf_dashboard/deploy/perf-dashboard/templates/ingress.yaml
Labels: size/M

#1829 [release-1.11] Update go 1.16.13
  docker/build-tools/Dockerfile
Labels: size/XS

#1842 Fixes for linting with new common-files update
  cmd/annotations_prep/main.go
  cmd/cue-gen/assets.gen.go
  cmd/cue-gen/genoapi.go
  cmd/gen-release-notes/main.go
  cmd/kubetype-gen/metadata/metadata.go
  cmd/license-lint/main.go
  cmd/mvpage/mover.go
  isotope/convert/cmd/graphviz.go
  isotope/convert/cmd/kubernetes.go
  isotope/convert/pkg/graph/script/request_command.go
  isotope/convert/pkg/graph/svc/unmarshal.go
  isotope/convert/pkg/kubernetes/kubernetes.go
  isotope/service/main.go
  isotope/service/pkg/srv/executable.go
  isotope/service/pkg/srv/graph.go
  isotope/service/pkg/srv/handler.go
  isotope/service/pkg/srv/prometheus/handler.go
Labels: size/M

#1840 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/lint_go.sh
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1843 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1844 Update bom dependency to v0.2.0
  docker/build-tools/Dockerfile
Labels: size/XS

#1845 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1846 Bump sigs.k8s.io/bom to v0.2.1
  docker/build-tools/Dockerfile
Labels: size/XS, ok-to-test

#1847 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1848 Always log boskos failures
  bin/setup_cluster.sh
Labels: size/XS

#1781 add perf tests for authz dry-run
  perf/benchmark/configs/istio/security_authz_dry_run/config.json
  perf/benchmark/configs/istio/security_authz_dry_run/cpu_mem.yaml
  perf/benchmark/configs/istio/security_authz_dry_run/installation.yaml
  perf/benchmark/configs/istio/security_authz_dry_run/latency.yaml
  perf/benchmark/configs/istio/security_authz_dry_run/postrun.sh
  perf/benchmark/configs/istio/security_authz_dry_run/prerun.sh
  perf/benchmark/configs/run_perf_test.conf
  perf/benchmark/security/generate_policies/generate_policies.go
Labels: size/L
