Repository istio/tools, pull requests merged in 2023-10, with the labels that each got.

#2669 CRD gen: better doc extraction
  cmd/cue-gen/genoapi.go
Labels: size/S

#2670 crd gen: hide from docs regardless of where in the comment it is
  cmd/cue-gen/genoapi.go
Labels: size/XS, release-notes-none

#2671 Run trivy on repo; update dependencies
  go.mod
  go.sum
  isotope/go.mod
  isotope/go.sum
Labels: size/XXL

#2673 html docs gen: skip codegen comments
  cmd/protoc-gen-docs/htmlGenerator.go
  go.mod
  go.sum
Labels: size/M, release-notes-none

#2672 Make devcontainer valid json
  .devcontainer/devcontainer.json
Labels: size/S, release-notes-none

#2675 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2676 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2674 Introduce `protoc-gen-crd`
  cmd/protoc-gen-crd/README.md
  cmd/protoc-gen-crd/main.go
  cmd/protoc-gen-crd/openapiGenerator.go
  cmd/protoc-gen-crd/pkg/protocgen/generate.go
  go.mod
  go.sum
  licenses/github.com/getkin/kin-openapi/LICENSE
  licenses/github.com/invopop/yaml/LICENSE
  licenses/github.com/mohae/deepcopy/LICENSE
  licenses/github.com/perimeterx/marshmallow/LICENSE
Labels: size/XXL

#2677 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2678 Build protoc-gen-crd in build-tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2679 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2680 Update golang
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.19

#2684 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2681 [release-1.18] Update golang
  docker/build-tools/Dockerfile
Labels: size/XS

#2682 [release-1.17] Update golang
  docker/build-tools/Dockerfile
Labels: size/XS

#2683 [release-1.19] Update golang (#2680)
  docker/build-tools/Dockerfile
Labels: size/XS

#2686 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2688 Automator: update common-files@release-1.19 in istio/tools@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2687 protoc-gen-crd: add option to make spec required
  cmd/protoc-gen-crd/openapiGenerator.go
Labels: size/XS, release-notes-none

#2668 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2689 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2690 Update golang
  docker/build-tools/Dockerfile
Labels: size/XS

#2694 Update golang.org/x/net and grpc-go
  go.mod
  go.sum
Labels: size/L

#2695 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2691 [release-1.17] Update golang
  docker/build-tools/Dockerfile
Labels: size/XS

#2692 [release-1.18] Update golang
  docker/build-tools/Dockerfile
Labels: size/XS

#2697 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2696 Automator: update common-files@release-1.19 in istio/tools@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2698 Automator: update common-files@release-1.18 in istio/tools@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2702 Allow prow-entrypoint to set insecure registries to docker daemon
  docker/build-tools/prow-entrypoint.sh
Labels: size/S

#2703 [release-1.20] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  docker/build-tools/build-and-push.sh
Labels: size/XS

#2701 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2704 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2705 Dockerfle cleanup
  docker/build-tools/Dockerfile
Labels: size/S, ok-to-test

#2706 Automator: update common-files@release-1.20 in istio/tools@release-1.20
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2710 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#2709 [release-1.20] Update rust
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2711 Automator: update common-files@release-1.20 in istio/tools@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2712 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2713 Update golangci-lint
  docker/build-tools/Dockerfile
Labels: size/XS

#2714 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2715 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#2717 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#2719 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2720 Automator: update common-files@master in istio/tools@master
  LICENSE
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none
