Repository istio/tools, pull requests merged in 2023-03, with the labels that each got.

#2393 update misc tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2394 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2395 Automator: update common-files@master in istio/tools@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2396 Add rsync to proxy
  docker/build-tools/Dockerfile
Labels: size/XS

#2397 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2398 drop gcloud logs
  docker/build-tools/docker-entrypoint.sh
Labels: size/XS

#2401 [release-1.16] update golang 1.19.7
  docker/build-tools/Dockerfile
Labels: size/XS

#2402 [release-1.15] golang 1.19.7
  docker/build-tools/Dockerfile
Labels: size/XS

#2403 [release-1.17] Update Go to 1.20.2
  docker/build-tools/Dockerfile
Labels: size/XS

#2400 update golang 1.20.2
  docker/build-tools/Dockerfile
Labels: size/XS

#2404 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2406 Automator: update common-files@release-1.15 in istio/tools@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2407 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2408 go-mod-upgrade, fix dependabot alert (authorization by-pass)
  go.mod
  go.sum
  isotope/go.mod
  isotope/go.sum
  licenses/cloud.google.com/go/compute/metadata/LICENSE
  licenses/github.com/golang-jwt/jwt/v5/LICENSE
  licenses/github.com/perimeterx/marshmallow/LICENSE
  perf/benchmark/security/generate_policies/jwt.go
Labels: size/XXL

#2399 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2409 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2413 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/M, auto-merge, release-notes-none

#2415 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#2414 Automator: update common-files@release-1.15 in istio/tools@release-1.15
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#2416 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#2411 update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2418 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2420 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#2421 Automator: update common-files@release-1.15 in istio/tools@release-1.15
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#2422 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#2423 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
Labels: size/L, auto-merge, release-notes-none
