Repository istio/tools, pull requests merged in 2023-06, with the labels that each got.

#2489 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2492 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2490 bump golangci-lint
  docker/build-tools/Dockerfile
Labels: size/XS

#2494 [1.18] bump golang 1.20.5
  docker/build-tools/Dockerfile
Labels: size/XS

#2497 Automator: update common-files@release-1.18 in istio/tools@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2496 [1.16] Bump golang 1.19.10
  docker/build-tools/Dockerfile
Labels: size/XS

#2498 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#2499 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2495 [1.17] Bump golang 1.20.5
  docker/build-tools/Dockerfile
Labels: size/XS

#2500 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2501 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#2503 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2507 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2506 make proxy image configurable
  perf/benchmark/templates/fortio.yaml
  perf/benchmark/values.yaml
Labels: size/XS

#2508 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2491 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/M

#2509 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2510 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2511 Add docker buildx plugin (needed for later Docker versions)
  docker/build-tools/Dockerfile
Labels: size/XS

#2513 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#2514 Make golangci-lint static
  docker/build-tools/Dockerfile
  perf_dashboard/settings/views.py
Labels: size/XS

#2512 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2516 Move from golang:1.20.5, based on bookwarm, to bullseye
  docker/build-tools/Dockerfile
Labels: size/XS

#2518 [release-1.16] Pin golang base container to bullseye
  docker/build-tools/Dockerfile
Labels: size/XS

#2519 [release-1.18] Pin golang base container to bullseye
  docker/build-tools/Dockerfile
Labels: size/XS

#2521 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2522 Automator: update common-files@release-1.18 in istio/tools@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2520 [release-1.17] Pin golang base container to bullseye
  docker/build-tools/Dockerfile
Labels: size/XS

#2524 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2527 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2528 Fix GCP_SECRETS leaking data
  docker/build-tools/prow-entrypoint.sh
Labels: size/M

#2529 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2531 Revamp release-notes tool
  cmd/gen-release-notes/main.go
  cmd/schema-validator/validate.go
  pkg/schemavalidation/validation.go
Labels: size/L

#2532 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2533 Drop obsolete schema validator
  cmd/schema-validator/testdata/features.yaml
  cmd/schema-validator/testdata/features_broken.yaml
  cmd/schema-validator/testdata/features_schema.json
  cmd/schema-validator/validate.go
  cmd/schema-validator/validate_test.go
Labels: size/XL, release-notes-none

#2534 [release-1.18] Revamp release-notes tool
  cmd/gen-release-notes/main.go
  cmd/schema-validator/validate.go
  pkg/schemavalidation/validation.go
Labels: size/L, release-notes-none

#2537 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2538 GCP_SECRETS: allow writing to file as well
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS, release-notes-none

#2539 Release notes: skip batch jobs
  cmd/gen-release-notes/main.go
Labels: size/XS, release-notes-none

#2535 [release-1.17] Revamp release-notes tool
  cmd/gen-release-notes/main.go
  cmd/schema-validator/validate.go
  pkg/schemavalidation/validation.go
Labels: size/L, release-notes-none

#2541 mkdir the file before attempting to write
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS, release-notes-none

#2542 1.18: sync build-tools with master
  cmd/gen-release-notes/main.go
  cmd/schema-validator/testdata/features.yaml
  cmd/schema-validator/testdata/features_broken.yaml
  cmd/schema-validator/testdata/features_schema.json
  cmd/schema-validator/validate.go
  cmd/schema-validator/validate_test.go
  docker/build-tools/prow-entrypoint.sh
Labels: size/XL

#2545 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2544 1.16: sync build-tools with master
  cmd/gen-release-notes/main.go
  cmd/schema-validator/testdata/features.yaml
  cmd/schema-validator/testdata/features_broken.yaml
  cmd/schema-validator/testdata/features_schema.json
  cmd/schema-validator/validate.go
  cmd/schema-validator/validate_test.go
  docker/build-tools/prow-entrypoint.sh
  pkg/schemavalidation/validation.go
Labels: size/XXL

#2546 Automator: update common-files@release-1.18 in istio/tools@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2547 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2543 1.17: sync build-tools with master
  cmd/gen-release-notes/main.go
  cmd/schema-validator/testdata/features.yaml
  cmd/schema-validator/testdata/features_broken.yaml
  cmd/schema-validator/testdata/features_schema.json
  cmd/schema-validator/validate.go
  cmd/schema-validator/validate_test.go
  docker/build-tools/prow-entrypoint.sh
Labels: size/XL

#2548 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
