Repository istio/tools, pull requests merged in 2023-01, with the labels that each got.

#2296 Update tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2297 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2298 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#2299 minor updates to trivy and gh cli
  docker/build-tools/Dockerfile
Labels: size/XS

#2300 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2301 Add networking tools from istio/base
  docker/build-tools/Dockerfile
Labels: size/XS

#2303 update containerd
  docker/build-tools/Dockerfile
Labels: size/XS

#2304 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2305 Minor tools update
  docker/build-tools/Dockerfile
Labels: size/XS

#2302 Update to Go 1.19.5
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.15, cherrypick/release-1.16

#2308 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2309 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
Labels: size/XS, auto-merge, release-notes-none

#2306 [release-1.15] Update to Go 1.19.5
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2307 [release-1.16] Update to Go 1.19.5
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2310 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2311 Automator: update common-files@release-1.15 in istio/tools@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2259 Update to not copy docker sockets in docker entry-point
  docker/build-tools/Dockerfile
  docker/build-tools/docker-entrypoint.sh
Labels: size/XS

#2313 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2314 Bmup gcloud to fix kubectl
  docker/build-tools/Dockerfile
Labels: size/XS

#2318 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2320 [release-1.17] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  docker/build-tools/build-and-push.sh
Labels: size/XS, release-notes-none

#2321 feat: extend trace propagation to include cloud-specific headers & OTEL
  isotope/service/pkg/srv/header.go
Labels: size/S, ok-to-test

#2322 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2323 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2325 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2324 Update various tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2326 [release-1.17] Update various tools
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2328 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2329 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2331 minor changes to docker-ce and patch update for rust
  docker/build-tools/Dockerfile
Labels: size/XS

#2332 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2327 Update git
  docker/build-tools/Dockerfile
Labels: size/XS

#2333 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2319 Add ingressgateway_tls config and changes to the benchmark runner
  perf/benchmark/configs/istio/ingressgateway_tls/cpu_mem.yaml
  perf/benchmark/configs/istio/ingressgateway_tls/installation.yaml
  perf/benchmark/configs/istio/ingressgateway_tls/latency.yaml
  perf/benchmark/configs/istio/none/cpu_mem.yaml
  perf/benchmark/configs/istio/none/latency.yaml
  perf/benchmark/configs/istio/none_tcp/cpu_mem.yaml
  perf/benchmark/configs/istio/none_tcp/latency.yaml
  perf/benchmark/configs/istio/plaintext/cpu_mem.yaml
  perf/benchmark/configs/istio/plaintext/latency.yaml
  perf/benchmark/configs/istio/security_authz_dry_run/cpu_mem.yaml
  perf/benchmark/configs/istio/security_authz_dry_run/latency.yaml
  perf/benchmark/configs/istio/security_authz_ip/cpu_mem.yaml
  perf/benchmark/configs/istio/security_authz_ip/latency.yaml
  perf/benchmark/configs/istio/security_authz_jwt/cpu_mem.yaml
  perf/benchmark/configs/istio/security_authz_jwt/latency.yaml
  perf/benchmark/configs/istio/security_authz_path/cpu_mem.yaml
  perf/benchmark/configs/istio/security_authz_path/latency.yaml
  perf/benchmark/configs/istio/security_peer_authn/cpu_mem.yaml
  perf/benchmark/configs/istio/security_peer_authn/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full_accesslogpolicy/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_full_accesslogpolicy/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_sd_nologging/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_statswasm/cpu_mem.yaml
  perf/benchmark/configs/istio/telemetryv2_statswasm/latency.yaml
  perf/benchmark/configs/run_perf_test.conf
  perf/benchmark/run_benchmark_job.sh
  perf/benchmark/runner/runner.py
  perf/benchmark/setup_test.sh
  perf/benchmark/templates/fortio.yaml
  perf/benchmark/values.yaml
Labels: size/L, ok-to-test

#2338 Automator: update common-files@release-1.15 in istio/tools@release-1.15
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#2339 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2340 Make creating cluster optional when using the benchmark runner
  perf/benchmark/run_benchmark_job.sh
Labels: size/M, ok-to-test

#2335 [release-1.16] Update git
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2336 [release-1.17] Update git
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2341 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#2342 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2343 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2334 [release-1.15] Update git
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2344 Debian `cmake` package missing standard targets/templates (enables`fips`-less builds of ztunnel)
  docker/build-tools/Dockerfile
Labels: size/XS, ok-to-test

#2345 Automator: update common-files@release-1.15 in istio/tools@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2346 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2348 Followup fix for #2344
  docker/build-tools/Dockerfile
Labels: size/XS, ok-to-test

#2349 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2350 Update tools
  docker/build-tools/Dockerfile
Labels: size/XS
