Repository istio/tools, pull requests merged in 2023-08, with the labels that each got.

#2606 [release-1.17] Update Go to 1.20.7
  docker/build-tools/Dockerfile
Labels: size/XS

#2609 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2611 Automator: update common-files@release-1.18 in istio/tools@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2610 Update cue to 0.5.0
  cmd/cue-gen/assets.gen.go
  cmd/cue-gen/build.go
  cmd/cue-gen/crd.go
  cmd/cue-gen/genoapi.go
  cmd/cue-gen/schema_visitor.go
  go.mod
  go.sum
  licenses/github.com/ProtonMail/go-crypto/LICENSE
  licenses/github.com/cloudflare/circl/LICENSE
  licenses/github.com/cloudflare/circl/ecc/p384/LICENSE
  licenses/github.com/getkin/kin-openapi/LICENSE
  licenses/github.com/google/s2a-go/LICENSE.md
  licenses/github.com/jdkato/prose/LICENSE
  licenses/github.com/mitchellh/go-wordwrap/LICENSE.md
  licenses/github.com/montanaflynn/stats/LICENSE
  licenses/github.com/perimeterx/marshmallow/LICENSE
  licenses/golang.org/x/sync/LICENSE
  licenses/google.golang.org/appengine/LICENSE
  licenses/google.golang.org/genproto/googleapis/api/LICENSE
  licenses/google.golang.org/genproto/googleapis/rpc/LICENSE
Labels: size/XXL

#2614 [release-1.19] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  docker/build-tools/build-and-push.sh
Labels: size/XS

#2615 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2616 Automator: update common-files@release-1.19 in istio/tools@release-1.19
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2617 [release-1.19] Update Go to 1.21.rc4
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2618 Automator: update common-files@release-1.19 in istio/tools@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2598 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2619 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2622 Remove arbitrary sleep(1) from Go testing
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none, cherrypick/release-1.19

#2623 [release-1.19] Remove arbitrary sleep(1) from Go testing
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2620 Update main branch to Go 1.21.0
  docker/build-tools/Dockerfile
Labels: size/XS

#2621 [release-1.19] Update release branch to Go 1.21.0
  docker/build-tools/Dockerfile
Labels: size/XS

#2624 cargo git directory volume
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2626 Update to golangci-lint 1.54.0
  docker/build-tools/Dockerfile
Labels: size/XS

#2627 Automator: update common-files@release-1.19 in istio/tools@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2629 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#2630 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#2631 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2632 Update tooling to k8s 1.28.0
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.19

#2633 [release-1.19] Update tooling to k8s 1.28.0
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2635 Automator: update common-files@release-1.19 in istio/tools@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2628 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2639 Pin pycodestyle version
  docker/build-tools/Dockerfile
Labels: size/XS

#2640 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2636 updates to the perf tools
  perf/benchmark/configs/istio/none/latency.yaml
  perf/benchmark/graph_plotter/graph_plotter.py
  perf/benchmark/runner/fortio.py
  perf/benchmark/runner/runner.py
  perf/istio-install/README.md
  perf/istio-install/base/templates/prometheus-install.yaml
Labels: size/M

#2637 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2641 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2458 clang: update to 14 and bionic
  docker/build-tools/Dockerfile
  docker/build-tools/install-python.sh
  docker/build-tools/proxy-tsan-instrumented-libcxx.sh
Labels: size/M, lifecycle/staleproof

#2638 Netperf benches
  ambient-tests/.gitignore
  ambient-tests/Makefile
  ambient-tests/README.md
  ambient-tests/docker/.dockerignore
  ambient-tests/docker/Dockerfile
  ambient-tests/docker/Makefile
  ambient-tests/docker/README.md
  ambient-tests/docker/server-and-sleep.sh
  ambient-tests/requirements.txt
  ambient-tests/scripts/config.sh
  ambient-tests/scripts/fortio/gen-csv.sh
  ambient-tests/scripts/fortio/graphs.py
  ambient-tests/scripts/fortio/results_to_csv.py
  ambient-tests/scripts/fortio/run.sh
  ambient-tests/scripts/lib.py
  ambient-tests/scripts/netperf/gen-csv.sh
  ambient-tests/scripts/netperf/graphs.py
  ambient-tests/scripts/netperf/results_to_csv.py
  ambient-tests/scripts/netperf/run.sh
  ambient-tests/scripts/setup.sh
  ambient-tests/yaml/cluster.yaml
  ambient-tests/yaml/deploy.yaml
Labels: size/XL

#2643 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2644 add ncurses
  docker/build-tools/Dockerfile
Labels: size/XS

#2645 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2646 add libtinfo5
  docker/build-tools/Dockerfile
Labels: size/XS

#2647 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
