Repository istio/tools, pull requests merged in 2023-07, with the labels that each got.

#2549 build: drop CentOS 7 builder
  clang-toolchain/Dockerfile
  clang-toolchain/README.md
  clang-toolchain/build_clang_llvm.sh
  clang-toolchain/cloudbuild.yaml
  clang-toolchain/install_build_deps.sh
  docker/build-tools/Dockerfile.centos
  docker/build-tools/build-and-push.sh
Labels: size/L

#2552 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2555 Add AR authentication
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS, release-notes-none, cherrypick/release-1.17, cherrypick/release-1.18

#2550 build-tools: allow ability to not run docker
  docker/build-tools/prow-entrypoint.sh
Labels: size/M, release-notes-none

#2558 [release-1.16] Add AR authentication
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS, release-notes-none

#2556 [release-1.17] Add AR authentication
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS, release-notes-none

#2557 [release-1.18] Add AR authentication
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS, release-notes-none

#2560 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2561 Automator: update common-files@release-1.18 in istio/tools@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2559 Add new `org-gen` tool, replacing the one in istio/community
  cmd/org-gen/main.go
  docker/build-tools/Dockerfile
  pkg/orggen/org.go
  pkg/orggen/org/util.go
Labels: size/L, release-notes-none

#2563 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2562 docker: build in parallel and fix TODO for org-gen
  docker/build-tools/Dockerfile
Labels: size/M, release-notes-none

#2564 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2565 docker: fix jq defaulting
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS, release-notes-none

#2567 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2570 [release-1.17] Add GCR *and* AR authentication
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS, release-notes-none

#2569 [release-1.16] Add GCR *and* AR authentication
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS, release-notes-none

#2571 [release-1.18] Add GCR *and* AR authentication
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS, release-notes-none

#2553 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2572 Revert "Change su-exec to static binary (#2515)"
  docker/build-tools/Dockerfile
Labels: size/XS

#2573 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2574 Variablize GCP registries
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS

#2575 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2576 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2577 Automator: update common-files@release-1.18 in istio/tools@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2578 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2579 Refactoring: Fix html indent of annotation_prep
  cmd/annotations_prep/main.go
Labels: size/M, ok-to-test

#2580 Update golang to 1.20.6
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.17, cherrypick/release-1.18

#2581 [release-1.16] update golang
  docker/build-tools/Dockerfile
Labels: size/XS

#2584 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2582 [release-1.18] Update golang to 1.20.6
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2583 [release-1.17] Update golang to 1.20.6
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2585 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2586 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2587 Automator: update common-files@release-1.18 in istio/tools@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2589 Docker: add otel-cli tool
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2588 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2590 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2591 podman: update build-and-push script
  docker/build-tools/build-and-push.sh
Labels: size/S, ok-to-test

#2593 Add support for prow tracing
  docker/build-tools/prow-entrypoint.sh
Labels: size/M

#2594 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2595 Fix tracing script masking return code
  docker/build-tools/prow-entrypoint.sh
Labels: size/XS, release-notes-none

#2596 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#2592 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2597 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2599 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/tracing.sh
Labels: size/L, auto-merge, release-notes-none

#2601 Remove obsolete istio-dev image
  Makefile.core.mk
  docker/istio-dev/.gitignore
  docker/istio-dev/Dockerfile
  docker/istio-dev/README.md
  docker/istio-dev/istio-dev.mk
Labels: size/L, release-notes-none

#2602 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/tracing.sh
Labels: size/S, auto-merge, release-notes-none

#2603 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
