Repository istio/tools, pull requests merged in 2023-09, with the labels that each got.

#2649 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2652 update golang to 1.21.1
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.19

#2651 [release-1.17] update golang
  docker/build-tools/Dockerfile
Labels: size/XS

#2654 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2650 [release-1.18] update golang
  docker/build-tools/Dockerfile
Labels: size/XS

#2653 [release-1.19] update golang to 1.21.1
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2655 Automator: update common-files@release-1.19 in istio/tools@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2656 Automator: update common-files@release-1.18 in istio/tools@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2658 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2657 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2659 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2660 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2663 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2662 update graph_plotter.py to use the actualQPS instead of hardcoding 1000
  perf/benchmark/graph_plotter/graph_plotter.py
Labels: size/XS

#2665 install extensions to help in development
  .devcontainer/devcontainer.json
Labels: size/M

#2664 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2666 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/M, auto-merge, release-notes-none

#2667 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/S, auto-merge, release-notes-none
