Repository istio/tools, pull requests merged in 2023-04, with the labels that each got.

#2426 Update for using build-tools with codespaces
  docker/build-tools/Dockerfile
Labels: size/S

#2419 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2424 Update go to 1.20.3
  docker/build-tools/Dockerfile
Labels: size/XS

#2425 [release-1.16] Update golang
  docker/build-tools/Dockerfile
Labels: size/XS

#2427 [release-1.17] Update go to 1.20.3
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2429 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2430 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/S, auto-merge, release-notes-none

#2431 Manual update of common-files
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS

#2432 Automator: update common-files@release-1.17 in istio/tools@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2428 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2433 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2434 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#2436 Update deps to k8s 1.27.0
  go.mod
  go.sum
Labels: size/M

#2438 Automator: update common-files@release-1.16 in istio/tools@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2437 Update codegenerator used by client-go
  docker/build-tools/Dockerfile
Labels: size/XS

#2439 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2441 remove deprecated pipenv command from benchmark readme
  perf/benchmark/README.md
Labels: size/XS, ok-to-test

#2440 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/M

#2444 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2446 [release-1.18] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  docker/build-tools/build-and-push.sh
Labels: size/XS, release-notes-none

#2447 Automator: update common-files@release-1.18 in istio/tools@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2448 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#2442 [release-1.18] update k8s tools to 1.27.1
  docker/build-tools/Dockerfile
Labels: size/XS
