Repository istio/tools, pull requests merged in 2023-12, with the labels that each got.

#2743 Update Go to 1.21.5
  docker/build-tools/Dockerfile
Labels: size/XS

#2745 [release-1.19] Update Go to 1.21.5
  docker/build-tools/Dockerfile
Labels: size/XS

#2747 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2746 [release-1.18] Update Go to 1.20.12
  docker/build-tools/Dockerfile
Labels: size/XS

#2744 [release-1.20] Update Go to 1.21.5
  docker/build-tools/Dockerfile
Labels: size/XS

#2748 Automator: update common-files@release-1.19 in istio/tools@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2749 Automator: update common-files@release-1.20 in istio/tools@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2750 Automator: update common-files@release-1.18 in istio/tools@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2753 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#2751 Update patch releasenotes format
  Makefile.core.mk
  cmd/gen-release-notes/templates/minorReleaseNotes.md
  cmd/gen-release-notes/templates/releaseNotes.md
Labels: size/XS

#2754 Update various tools
  docker/build-tools/Dockerfile
Labels: size/M

#2755 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2757 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2760 Bump oc
  docker/build-tools/Dockerfile
Labels: size/XS
