Repository istio/tools, pull requests merged in 2024-08, with the labels that each got.

#2997 update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2999 [release-1.22] bump go to 1.22.6
  docker/build-tools/Dockerfile
Labels: size/XS

#3001 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3002 [release-1.23] update hugo to match master
  docker/build-tools/Dockerfile
Labels: size/XS

#3003 Update Go to 1.23rc2
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#3004 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2998 [release-1.21] bump go to 1.22.6
  docker/build-tools/Dockerfile
Labels: size/XS

#3000 [release-1.23] bump go to 1.22.6
  docker/build-tools/Dockerfile
Labels: size/XS

#3005 Automator: update common-files@release-1.22 in istio/tools@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3006 Automator: update common-files@release-1.23 in istio/tools@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3007 update more tools
  docker/build-tools/Dockerfile
Labels: size/S

#3009 Bump to go 1.23.0
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#3010 Bump golangci-lint to 1.60.1, fixing go 1.23
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#3012 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3015 CRD generation tooling: use our own prefix
  cmd/protoc-gen-crd/openapiGenerator.go
  go.mod
  go.sum
  licenses/github.com/gobuffalo/flect/LICENSE
Labels: size/L

#3017 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3013 update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#3016 1.23 backport: CRD generation tooling: use our own prefix (#3015)
  cmd/protoc-gen-crd/openapiGenerator.go
  go.mod
  go.sum
  licenses/github.com/gobuffalo/flect/LICENSE
Labels: size/M, release-notes-none

#3018 Automator: update common-files@release-1.23 in istio/tools@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3019 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3020 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#3021 Update tools
  docker/build-tools/Dockerfile
Labels: size/S
