Repository istio/tools, pull requests merged in 2024-02, with the labels that each got.

#2796 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2799 Update bom
  docker/build-tools/Dockerfile
Labels: size/XS

#2800 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2802 Update kind
  docker/build-tools/Dockerfile
Labels: size/XS

#2803 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2805 [release-1.19] Update golang to 1.21.7
  docker/build-tools/Dockerfile
Labels: size/XS

#2806 [release-1.20] update golang to 1.21.7
  docker/build-tools/Dockerfile
Labels: size/XS

#2804 Update golang to 1.22
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.21

#2809 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2801 Update docker
  docker/build-tools/Dockerfile
Labels: size/XS

#2810 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2811 Update golangci-lint that supports go1.22
  docker/build-tools/Dockerfile
Labels: size/XS

#2813 Update golangci-lint (again)
  docker/build-tools/Dockerfile
Labels: size/XS

#2814 Automator: update common-files@release-1.19 in istio/tools@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2808 [release-1.21] Update golang to 1.22
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2815 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#2816 Automator: update common-files@master in istio/tools@master
  SUPPORT.md
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2817 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, auto-merge, release-notes-none

#2819 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#2820 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#2821 Correct typo from 'destionation' to 'destination'
  perf/benchmark/configs/istio/plaintext/postrun.sh
  perf/benchmark/configs/istio/plaintext/prerun.sh
Labels: size/XS

#2818 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2823 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2824 Automator: update common-files@release-1.21 in istio/tools@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2826 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2827 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2825 better description render
  cmd/annotations_prep/main.go
  go.mod
  go.sum
  licenses/github.com/gomarkdown/markdown/LICENSE.txt
Labels: size/M

#2830 Drop IBM cluster storage
  perf/istio-install/base/templates/prometheus-install.yaml
Labels: size/S, cherrypick/release-1.21

#2812 Update go1.22
  go.mod
  go.sum
  isotope/go.mod
  isotope/go.sum
  licenses/github.com/stretchr/objx/LICENSE
Labels: size/L

#2831 [release-1.21] Drop IBM cluster storage
  perf/istio-install/base/templates/prometheus-install.yaml
Labels: size/S, release-notes-none

#2832 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2833 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2834 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb-native.yaml
Labels: size/L, auto-merge, release-notes-none

#2835 Automator: update common-files@release-1.20 in istio/tools@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2836 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2837 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2838 protoc-gen-crd: remove spam on generation
  cmd/protoc-gen-crd/main.go
Labels: size/XS, release-notes-none

#2839 protoc-gen-crd: allow marking an API version as deprecated
  cmd/protoc-gen-crd/openapiGenerator.go
Labels: size/XS, release-notes-none

#2841 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
