Repository istio/tools, pull requests merged in 2024-09, with the labels that each got.

#3025 Bump go to 1.23.1
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#3026 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3027 [release-1.23] Update go
  docker/build-tools/Dockerfile
Labels: size/XS

#3028 [release-1.22] update go
  docker/build-tools/Dockerfile
Labels: size/XS

#3024 update more tools
  docker/build-tools/Dockerfile
Labels: size/S

#3022 Add rustfilt and cargo binaries to PATH
  docker/build-tools/Dockerfile
Labels: size/XS

#3030 Don't put rustfilt in cargo path
  docker/build-tools/Dockerfile
Labels: size/XS

#3032 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3033 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#3031 update tools
  docker/build-tools/Dockerfile
Labels: size/S

#3034 update docker and buildx
  docker/build-tools/Dockerfile
Labels: size/XS

#3035 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3036 update docker and apko
  docker/build-tools/Dockerfile
Labels: size/XS

#3038 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3039 Automator: update common-files@release-1.21 in istio/tools@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
