Repository istio/tools, pull requests merged in 2024-03, with the labels that each got.

#2842 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#2840 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2844 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2845 Update Go to 1.22.1
  docker/build-tools/Dockerfile
Labels: size/XS

#2849 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2846 [release-1.21] Update Go to 1.22.1
  docker/build-tools/Dockerfile
Labels: size/XS

#2847 [release-1.20] Update Go to 1.21.8
  docker/build-tools/Dockerfile
Labels: size/XS

#2850 Automator: update common-files@release-1.21 in istio/tools@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2848 [release-1.19] Update Go to 1.21.8
  docker/build-tools/Dockerfile
Labels: size/XS

#2851 Automator: update common-files@release-1.20 in istio/tools@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2843 Delete perf option
  perf/benchmark/configs/istio/none/latency.yaml
  perf/benchmark/graph_plotter/graph_plotter.py
  perf/benchmark/runner/runner.py
Labels: size/S

#2854 crds: document all possible enum values
  cmd/protoc-gen-crd/openapiGenerator.go
Labels: size/S, release-notes-none

#2855 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2856 [qual tests] Update kube-state-metrics
  perf/stability/alertmanager/templates/kube_state_metrics.yaml
Labels: cherrypick/release-1.19, cherrypick/release-1.20, cherrypick/release-1.21

#2860 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2857 [release-1.19] [qual tests] Update kube-state-metrics
  perf/stability/alertmanager/templates/kube_state_metrics.yaml
Labels: size/S, release-notes-none

#2858 [release-1.20] [qual tests] Update kube-state-metrics
  perf/stability/alertmanager/templates/kube_state_metrics.yaml
Labels: size/S, release-notes-none

#2859 [release-1.21] [qual tests] Update kube-state-metrics
  perf/stability/alertmanager/templates/kube_state_metrics.yaml
Labels: size/S, release-notes-none

#2864 Bump google.golang.org/protobuf from 1.32.0 to 1.33.0
  go.mod
  go.sum
Labels: size/S

#2865 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#2866 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2867 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2868 org: allow `thelinuxfoundation` to be an admin
  pkg/orggen/org.go
Labels: size/XS, release-notes-none

#2869 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
