Repository istio/tools, pull requests merged in 2024-12, with the labels that each got.

#3074 feat: change build container to use hugo-extended
  docker/build-tools/Dockerfile
Labels: size/XS

#3073 Update tools
  docker/build-tools/Dockerfile
Labels: size/S

#3075 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3077 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#3076 [release-1.24] cherry-pick #3074
  docker/build-tools/Dockerfile
Labels: size/XS

#3079 Automator: update common-files@release-1.24 in istio/tools@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3080 Automator: update common-files@release-1.22 in istio/tools@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3078 update tools
  docker/build-tools/Dockerfile
Labels: size/XS

#3081 pin traverse before breakage
  docker/build-tools/Dockerfile
Labels: size/XS

#3082 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#3083 Automator: update common-files@release-1.24 in istio/tools@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3084 Update more tools
  docker/build-tools/Dockerfile
Labels: size/XS

#3085 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3087 update docker
  docker/build-tools/Dockerfile
Labels: size/XS

#3088 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3089 Improve protoc-gen-docs to make nicer reference docs on istio.io
  cmd/protoc-gen-docs/htmlGenerator.go
Labels: size/M, cherrypick/release-1.24

#3092 [release-1.24] Improve protoc-gen-docs to make nicer reference docs on istio.io
  cmd/protoc-gen-docs/htmlGenerator.go
Labels: size/M, release-notes-none

#3093 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3094 Automator: update common-files@release-1.24 in istio/tools@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3050 CRDs: use cel preprocessor
  cmd/protoc-gen-crd/openapiGenerator.go
  go.mod
  go.sum
  licenses/github.com/antlr4-go/antlr/v4/LICENSE
  licenses/github.com/google/cel-go/LICENSE
  licenses/github.com/howardjohn/celpp/LICENSE
  licenses/github.com/stoewer/go-strcase/LICENSE
  licenses/google.golang.org/genproto/googleapis/rpc/LICENSE
Labels: size/XL, lifecycle/automatically-closed

#3091 Add rustup llvm toolchain
  docker/build-tools/Dockerfile
Labels: size/S

#3097 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#3098 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#3099 Add vtprotobuf plugin
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#3100 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
