Repository istio/tools, pull requests merged in 2024-06, with the labels that each got.

#2947 protoc-gen-crd: allow list-value validations and enforce correct Durations
  cmd/protoc-gen-crd/openapiGenerator.go
Labels: size/S

#2948 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/S, auto-merge, release-notes-none

#2949 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2952 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2950 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2955 [release-1.20] update go
  docker/build-tools/Dockerfile
Labels: size/XS

#2957 Automator: update common-files@release-1.20 in istio/tools@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2958 build-tools: take advantage of modern docker features
  docker/build-tools/Dockerfile
Labels: size/L, release-notes-none

#2960 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2954 [release-1.21] update go
  docker/build-tools/Dockerfile
Labels: size/XS

#2959 update misc tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2961 Make su-exec have a compatible glibc
  docker/build-tools/Dockerfile
Labels: size/S, release-notes-none

#2963 Copy go binary to build-tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2964 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2965 Automator: update common-files@release-1.21 in istio/tools@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2966 Automator: update common-files@release-1.22 in istio/tools@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2967 Fix bad paths in docker images
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2968 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2962 update misc tools
  docker/build-tools/Dockerfile
Labels: size/M

#2970 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2971 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#2972 NOP change to 1.22 docker image to retrigger build
  docker/build-tools/Dockerfile
Labels: size/XS
