Repository istio/tools, pull requests merged in 2024-07, with the labels that each got.

#2969 Update misc tools
  cmd/license-lint/collector.go
  docker/build-tools/Dockerfile
Labels: size/S

#2973 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2976 [release-1.21] Update go
  docker/build-tools/Dockerfile
Labels: size/XS

#2975 [release-1.22] update go
  docker/build-tools/Dockerfile
Labels: size/XS

#2977 Automator: update common-files@release-1.21 in istio/tools@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2978 Automator: update common-files@release-1.22 in istio/tools@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2974 update go
  docker/build-tools/Dockerfile
Labels: size/XS

#2983 Allow zero duration in fields that require it
  cmd/protoc-gen-crd/openapiGenerator.go
Labels: size/S, release-notes-none

#2984 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2979 adding SE status generation
  cmd/kubetype-gen/generators/types.go
Labels: size/M

#2986 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2987 [release-1.23] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  docker/build-tools/build-and-push.sh
Labels: size/XS

#2988 Automator: update common-files@release-1.23 in istio/tools@release-1.23
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2982 Explicitly encode status schema into CRDs
  cmd/protoc-gen-crd/openapiGenerator.go
Labels: size/S

#2989 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2985 update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2990 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2992 Automator: update common-files@master in istio/tools@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2994 Fix int-or-str formatting
  cmd/protoc-gen-crd/openapiGenerator.go
Labels: size/XS, release-notes-none

#2995 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2991 update more tools
  docker/build-tools/Dockerfile
Labels: size/S

#2993 Update rust to v1.80
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2996 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
