Repository istio/tools, pull requests merged in 2024-01, with the labels that each got.

#2763 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2762 Bump github.com/go-git/go-git/v5 from 5.4.2 to 5.11.0 with gen
  go.mod
  go.sum
  licenses/dario.cat/mergo/LICENSE
  licenses/github.com/cyphar/filepath-securejoin/LICENSE
  licenses/github.com/mitchellh/go-homedir/LICENSE
  licenses/github.com/pjbgf/sha1cd/LICENSE
  licenses/github.com/skeema/knownhosts/LICENSE
Labels: size/XL

#2764 Update rustc
  docker/build-tools/Dockerfile
Labels: size/XS

#2765 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2769 Renamed perf graph labels
  perf/benchmark/configs/istio/none/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/latency.yaml
  perf/benchmark/graph_plotter/README.md
  perf/benchmark/graph_plotter/graph_plotter.py
  perf/benchmark/runner/fortio.py
  perf/benchmark/runner/runner.py
Labels: size/M

#2771 Update golang to 1.21.6
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.19, cherrypick/release-1.20

#2774 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2772 [release-1.20] Update golang to 1.21.6
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2770 improve resource annotation table UX
  cmd/annotations_prep/main.go
Labels: size/S

#2776 Automator: update common-files@release-1.20 in istio/tools@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2775 Automator: update common-files@release-1.19 in istio/tools@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2778 [release-1.20] improve resource annotation table UX
  cmd/annotations_prep/main.go
Labels: size/S, release-notes-none

#2779 Automator: update common-files@release-1.20 in istio/tools@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2781 Cleanup test-infra cli tools
  docker/build-tools/Dockerfile
Labels: size/S

#2780 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/M

#2783 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2786 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#2785 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2788 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2787 Update docker
  docker/build-tools/Dockerfile
Labels: size/XS

#2789 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2790 Revert "Update docker"
  docker/build-tools/Dockerfile
Labels: size/XS

#2791 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2792 [release-1.21] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  docker/build-tools/build-and-push.sh
Labels: size/XS, release-notes-none

#2793 Automator: update common-files@release-1.21 in istio/tools@release-1.21
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2784 Delete perf option
  perf/benchmark/configs/istio/none/latency.yaml
  perf/benchmark/configs/istio/telemetryv2_stats/latency.yaml
  perf/benchmark/runner/fortio.py
  perf/benchmark/runner/runner.py
Labels: size/S

#2794 Unpin the pycodestyle and bump up the autopep8
  docker/build-tools/Dockerfile
Labels: size/XS

#2795 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2798 Automator: update common-files@master in istio/tools@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none
