Repository istio/tools, pull requests merged in 2024-05, with the labels that each got.

#2907 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2908 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2909 Add apko
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2910 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2911 improve error message
  cmd/gen-release-notes/main.go
Labels: size/XS

#2912 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/XS

#2914 build-tools: make static images
  docker/build-tools/Dockerfile
Labels: size/M, release-notes-none

#2915 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#2913 docker: update image to `ubuntu:noble`
  docker/build-tools/Dockerfile
Labels: size/M, release-notes-none

#2916 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#2917 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2919 docker: fixes for noble
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2922 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2920 crd gen: single proto source per type
  cmd/protoc-gen-crd/openapiGenerator.go
Labels: size/L, release-notes-none

#2923 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2924 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2925 [release-1.22] Update golang to 1.22.3
  docker/build-tools/Dockerfile
Labels: size/XS

#2926 [release-1.21] update to go 1.22 for istio 1.21
  docker/build-tools/Dockerfile
Labels: size/XS

#2927 [release-1.20] update to go 1.20.10
  docker/build-tools/Dockerfile
Labels: size/XS

#2928 Automator: update common-files@release-1.20 in istio/tools@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2921 Add new protoc-gen-alias command to allow backwards version compat
  cmd/protoc-gen-alias/Makefile
  cmd/protoc-gen-alias/README.md
  cmd/protoc-gen-alias/main.go
  cmd/protoc-gen-alias/test/Makefile
  cmd/protoc-gen-alias/test/alias_test.go
  cmd/protoc-gen-alias/test/v1/external.pb.go
  cmd/protoc-gen-alias/test/v1/external.proto
  cmd/protoc-gen-alias/test/v1/types.pb.go
  cmd/protoc-gen-alias/test/v1/types.proto
  cmd/protoc-gen-alias/test/v1alpha/types_alias.gen.go
Labels: size/L, release-notes-none

#2929 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2930 Add protoc-gen-alias to the docker image
  docker/build-tools/Dockerfile
Labels: size/XS, release-notes-none

#2931 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2932 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2933 Update codegen to workaround k8s client-go limits
  cmd/kubetype-gen/scanner/scanner.go
  cmd/protoc-gen-alias/main.go
  cmd/protoc-gen-alias/test/v1alpha/types_alias.gen.go
Labels: size/M, release-notes-none

#2935 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2936 protoc-gen-docs: mark proto3 as supported
  cmd/protoc-gen-docs/htmlGenerator.go
Labels: size/XS, release-notes-none

#2937 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2941 updated ambient-test README.md
  ambient-tests/README.md
  ambient-tests/push_error.png
Labels: size/M

#2938 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2942 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2944 Update misc tools
  docker/build-tools/Dockerfile
Labels: size/S

#2945 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2943 protoc-gen-crd: apply CEL validation to values of a map
  cmd/protoc-gen-crd/openapiGenerator.go
Labels: size/S, release-notes-none

#2946 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
