Repository istio/tools, pull requests merged in 2025-06, with the labels that each got.

#3215 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3217 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3214 Update tools
  docker/build-tools/Dockerfile
Labels: size/S

#3218 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3219 bump:hugo to version 0.147.8
  docker/build-tools/Dockerfile
Labels: size/XS, ok-to-test

#3225 [release-1.25] bump go to 1.23.10
  docker/build-tools/Dockerfile
Labels: size/XS

#3230 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3232 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3226 bump go to 1.24.4
  docker/build-tools/Dockerfile
Labels: size/XS

#3234 Add svg-symbol-sprite in dockerfile
  docker/build-tools/Dockerfile
Labels: size/XS

#3229 update tools
  docker/build-tools/Dockerfile
Labels: size/S

#3237 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none
