Repository istio/tools, pull requests merged in 2025-08, with the labels that each got.

#3251 Update tools
  docker/build-tools/Dockerfile
Labels: size/S

#3253 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3254 Bump go modules
  go.mod
  go.sum
Labels: size/L, release-notes-none

#3260 Update apko
  docker/build-tools/Dockerfile
Labels: size/XS

#3259 update protoc and apko
  docker/build-tools/Dockerfile
Labels: size/XS

#3263 Automator: update common-files@release-1.25 in istio/tools@release-1.25
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3265 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3266 Revert to Helm 3.18.4
  docker/build-tools/Dockerfile
Labels: size/XS

#3269 Update tools
  docker/build-tools/Dockerfile
Labels: size/S

#3270 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
