Repository istio/tools, pull requests merged in 2025-07, with the labels that each got.

#3239 Update tools
  docker/build-tools/Dockerfile
Labels: size/XS

#3241 Automator: update common-files@release-1.27 in istio/tools@release-1.27
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3247 Dockerfile: cleanup in tools
  docker/build-tools/Dockerfile
Labels: size/S

#3248 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3252 Automator: update common-files@release-1.27 in istio/tools@release-1.27
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
