Repository istio/tools, pull requests merged in 2025-02, with the labels that each got.

#3129 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3126 update tools
  docker/build-tools/Dockerfile
Labels: size/S

#3130 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3131 golang update
  docker/build-tools/Dockerfile
Labels: size/XS, cherrypick/release-1.25

#3135 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3132 [release-1.25] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  docker/build-tools/build-and-push.sh
Labels: size/XS, release-notes-none

#3136 Automator: update common-files@release-1.25 in istio/tools@release-1.25
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3137 update tools
  docker/build-tools/Dockerfile
Labels: size/S

#3138 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3139 update tools
  docker/build-tools/Dockerfile
Labels: size/XS

#3140 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3141 update tools
  docker/build-tools/Dockerfile
  go.mod
  go.sum
  isotope/go.mod
  isotope/go.sum
  licenses/github.com/pjbgf/sha1cd/LICENSE
Labels: size/L

#3143 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3146 Automator: update common-files@master in istio/tools@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#3145 Added libssl-dev to support building the OpenSSL variant of ztunnel
  docker/build-tools/Dockerfile
Labels: size/XS, ok-to-test

#3144 update tools
  docker/build-tools/Dockerfile
Labels: size/XS

#3148 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
