Repository istio/tools, pull requests merged in 2025-04, with the labels that each got.

#3178 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3174 Automator: update common-files@release-1.23 in istio/tools@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3179 Update tools
  docker/build-tools/Dockerfile
  go.mod
  go.sum
  isotope/go.mod
  isotope/go.sum
  licenses/github.com/go-viper/mapstructure/v2/LICENSE
  licenses/github.com/hashicorp/hcl/LICENSE
  licenses/github.com/magiconair/properties/LICENSE.md
  licenses/github.com/sagikazarmark/locafero/LICENSE
  licenses/github.com/sagikazarmark/slog-shim/LICENSE
  licenses/github.com/sourcegraph/conc/LICENSE
  licenses/gopkg.in/ini.v1/LICENSE
Labels: size/XXL

#3184 [release-1.23] bump Go
  docker/build-tools/Dockerfile
Labels: size/XS

#3185 [release-1.24] bump Go
  docker/build-tools/Dockerfile
Labels: size/XS

#3183 [release-1.25] bump Go
  docker/build-tools/Dockerfile
Labels: size/XS

#3180 bump golangci-lint to v2
  docker/build-tools/Dockerfile
Labels: size/XS

#3189 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/scripts/format_go.sh
  common/scripts/lint_go.sh
  common/scripts/setup_env.sh
Labels: size/XL, auto-merge, release-notes-none

#3190 Automator: update common-files@release-1.25 in istio/tools@release-1.25
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3192 [release-1.26] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  docker/build-tools/build-and-push.sh
Labels: size/XS, release-notes-none

#3193 Automator: update common-files@release-1.26 in istio/tools@release-1.26
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3182 update tools
  docker/build-tools/Dockerfile
  go.mod
  go.sum
  isotope/go.mod
  isotope/go.sum
  licenses/sigs.k8s.io/randfill/LICENSE
Labels: size/L

#3194 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3196 Automator: update common-files@master in istio/tools@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
